effects = {
    "g_Brett Kavanaugh Hearing Automatic x Levels Remix": {
        "beats": [
            [    1,    "hooked wandering bottom",    16],
            [    1,    "Autogen bassline top",    2],
            [    17,    "UV pulse slow",    2],
            [    17,    "Autogen bassline top",    2],
            [    19,    "Autogen bassline bottom",    2],
            [    19,    "Autogen UV Strobe",    1],
            [    21,    "Autogen bassline bottom",    2],
            [    21,    "RBBB 1 bar",    4],
            [    25,    "Autogen bassline top",    2],
            [    25,    "Autogen bassline bottom",    2],
            [    27,    "Autogen UV Strobe",    1],
            [    27,    "Autogen bassline sidechain bottom",    2],
            [    29,    "Autogen Strobe",    1],
            [    29,    "hooked wandering bottom",    16],
            [    45,    "UV pulse",    1],
            [    45,    "Autogen bassline bottom",    2],
            [    47,    "Autogen Strobe",    1],
            [    47,    "Rainbow bad",    2],
            [    49,    "hooked wandering bottom",    16],
            [    49,    "Ghosts riser",    4],
            [    65,    "RBBB 1 bar",    4],
            [    65,    "Autogen UV Strobe",    1],
            [    69,    "Autogen bassline sidechain bottom",    2],
            [    69,    "Ghosts riser",    4],
            [    73,    "rainbow good slow top",    16],
            [    73,    "UV pulse",    1],
            [    89,    "hooked wandering top",    16],
            [    89,    "Autogen Strobe",    1],
            [    105,    "UV pulse",    1],
            [    105,    "RBBB 1 bar",    4],
            [    109,    "Autogen bassline top",    2],
            [    109,    "hooked wandering bottom",    16],
            [    125,    "Autogen Strobe",    1],
            [    125,    "Autogen Strobe",    1],
            [    126,    "Autogen bassline top",    2],
            [    126,    "Autogen UV Strobe",    1],
            [    128,    "Autogen bassline sidechain bottom",    2],
            [    128,    "Autogen bassline bottom",    2],
            [    130,    "rainbow good slow top",    16],
            [    130,    "hooked wandering bottom",    16],
            [    146,    "UV pulse slow",    2],
            [    146,    "hooked wandering bottom",    16],
            [    162,    "Autogen bassline top",    2],
            [    162,    "RBBB 1 bar",    4],
            [    166,    "UV pulse",    1],
            [    166,    "Autogen UV Strobe",    1],
            [    167,    "Rainbow bad",    2],
            [    167,    "UV pulse",    1],
            [    169,    "Autogen bassline top",    2],
            [    169,    "Rainbow bad",    2],
            [    171,    "Autogen bassline sidechain bottom",    2],
            [    171,    "hooked wandering top",    16],
            [    187,    "Rainbow bad",    2],
            [    187,    "Autogen bassline bottom",    2],
            [    189,    "RBBB 1 bar",    4],
            [    189,    "Rainbow bad",    2],
            [    193,    "UV pulse",    1],
            [    193,    "Autogen bassline top",    2],
            [    195,    "hooked wandering top",    16],
            [    195,    "Autogen UV Strobe",    1],
            [    211,    "rainbow good slow top",    16],
            [    211,    "Rainbow bad",    2],
            [    227,    "hooked wandering top",    16],
            [    227,    "Autogen bassline top",    2],
            [    243,    "UV pulse",    1],
            [    243,    "rainbow good slow top",    16],
            [    259,    "hooked wandering top",    16],
            [    259,    "hooked wandering bottom",    16],
            [    275,    "Autogen bassline sidechain bottom",    2],
            [    275,    "Autogen UV Strobe",    1],
            [    277,    "Autogen UV Strobe",    1],
            [    277,    "Autogen bassline sidechain bottom",    2],
            [    279,    "hooked wandering bottom",    16],
            [    279,    "Autogen bassline bottom",    2],
            [    295,    "Autogen bassline bottom",    2],
            [    295,    "UV pulse",    1],
            [    297,    "hooked wandering top",    16],
            [    297,    "hooked wandering bottom",    16],
            [    313,    "UV pulse slow",    2],
            [    313,    "UV pulse slow",    2],
            [    315,    "hooked wandering top",    16],
            [    315,    "rainbow good slow top",    16],
            [    331,    "UV pulse",    1],
            [    331,    "UV pulse slow",    2],
            [    333,    "Rainbow bad",    2],
            [    333,    "Autogen Strobe",    1],
            [    335,    "hooked wandering bottom",    16],
            [    335,    "Rainbow bad",    2],
            [    351,    "Autogen Strobe",    1],
            [    351,    "Autogen UV Strobe",    1],
            [    352,    "Autogen UV Strobe",    1],
            [    352,    "Autogen UV Strobe",    1],
            [    353,    "hooked wandering top",    16],
            [    353,    "UV pulse",    1]
        ],
        "bpm": 130,
        "delay_lights": 0.39053846153846156,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/Brett Kavanaugh Hearing Automatic x Levels Remix.ogg"
    }
}