effects = {
    "g_Brett Kavanaugh Hearing Automatic x Levels Remix": {
        "beats": [
            [    1,    "Rainbow bad",    2],
            [    1,    "hooked wandering top",    16],
            [    17,    "Autogen UV Strobe",    1],
            [    17,    "hooked wandering top",    16],
            [    33,    "Autogen Strobe",    1],
            [    33,    "Autogen bassline top",    2],
            [    35,    "Ghosts riser",    4],
            [    35,    "hooked wandering bottom",    16],
            [    51,    "UV pulse",    1],
            [    51,    "Autogen bassline bottom",    2],
            [    53,    "hooked wandering bottom",    16],
            [    53,    "Ghosts riser",    4],
            [    69,    "UV pulse slow",    2],
            [    69,    "Autogen bassline top",    2],
            [    71,    "UV pulse slow",    2],
            [    71,    "Ghosts riser",    4],
            [    75,    "hooked wandering bottom",    16],
            [    75,    "UV pulse slow",    2],
            [    91,    "Autogen UV Strobe",    1],
            [    91,    "hooked wandering top",    16],
            [    107,    "Autogen bassline bottom",    2],
            [    107,    "hooked wandering top",    16],
            [    123,    "Autogen Strobe",    1],
            [    123,    "Autogen bassline sidechain bottom",    2],
            [    125,    "hooked wandering top",    16],
            [    125,    "Ghosts riser",    4],
            [    141,    "UV pulse slow",    2],
            [    141,    "Ghosts riser",    4],
            [    145,    "hooked wandering top",    16],
            [    145,    "Autogen bassline top",    2],
            [    161,    "hooked wandering bottom",    16],
            [    161,    "hooked wandering top",    16],
            [    177,    "Rainbow bad",    2],
            [    177,    "hooked wandering bottom",    16],
            [    193,    "Autogen bassline top",    2],
            [    193,    "Autogen bassline top",    2],
            [    195,    "Autogen bassline bottom",    2],
            [    195,    "Autogen bassline bottom",    2],
            [    197,    "UV pulse",    1],
            [    197,    "rainbow good slow top",    16],
            [    213,    "UV pulse slow",    2],
            [    213,    "RBBB 1 bar",    4],
            [    217,    "Autogen bassline bottom",    2],
            [    217,    "hooked wandering bottom",    16],
            [    233,    "UV pulse slow",    2],
            [    233,    "Autogen Strobe",    1],
            [    235,    "Autogen bassline sidechain bottom",    2],
            [    235,    "Rainbow bad",    2],
            [    237,    "Autogen Strobe",    1],
            [    237,    "hooked wandering bottom",    16],
            [    253,    "hooked wandering top",    16],
            [    253,    "Rainbow bad",    2],
            [    269,    "Autogen bassline top",    2],
            [    269,    "Autogen UV Strobe",    1],
            [    271,    "hooked wandering top",    16],
            [    271,    "Rainbow bad",    2],
            [    287,    "UV pulse",    1],
            [    287,    "Ghosts riser",    4],
            [    291,    "Autogen bassline sidechain bottom",    2],
            [    291,    "UV pulse slow",    2],
            [    293,    "Rainbow bad",    2],
            [    293,    "UV pulse",    1],
            [    295,    "Autogen Strobe",    1],
            [    295,    "UV pulse",    1],
            [    296,    "RBBB 1 bar",    4],
            [    296,    "Autogen bassline bottom",    2],
            [    300,    "Rainbow bad",    2],
            [    300,    "rainbow good slow top",    16],
            [    316,    "hooked wandering top",    16],
            [    316,    "hooked wandering top",    16],
            [    332,    "UV pulse slow",    2],
            [    332,    "rainbow good slow top",    16],
            [    348,    "Autogen bassline top",    2],
            [    348,    "Autogen Strobe",    1],
            [    350,    "UV pulse slow",    2],
            [    350,    "UV pulse slow",    2],
            [    352,    "RBBB 1 bar",    4],
            [    352,    "UV pulse",    1],
            [    356,    "hooked wandering bottom",    16],
            [    356,    "Autogen Strobe",    1]
        ],
        "bpm": 130,
        "delay_lights": 0.39053846153846156,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/Brett Kavanaugh Hearing Automatic x Levels Remix.ogg"
    }
}