effects = {
    "g_Cheesecake": {
        "beats": [
            [    1,    "rainbow good slow top",    16],
            [    1,    "UV pulse slow",    2],
            [    17,    "Ghosts riser",    4],
            [    17,    "Ghosts riser",    4],
            [    21,    "UV pulse",    1],
            [    21,    "rainbow good slow top",    16],
            [    37,    "rainbow good slow top",    16],
            [    37,    "Ghosts riser",    4],
            [    53,    "RBBB 1 bar",    4],
            [    53,    "Autogen Strobe",    1],
            [    57,    "hooked wandering bottom",    16],
            [    57,    "Rainbow bad",    2],
            [    73,    "Autogen bassline top",    2],
            [    73,    "Autogen bassline sidechain bottom",    2],
            [    75,    "Autogen Strobe",    1],
            [    75,    "Ghosts riser",    4],
            [    79,    "Rainbow bad",    2],
            [    79,    "rainbow good slow top",    16],
            [    95,    "hooked wandering bottom",    16],
            [    95,    "Ghosts riser",    4],
            [    111,    "hooked wandering top",    16],
            [    111,    "UV pulse slow",    2],
            [    127,    "hooked wandering bottom",    16],
            [    127,    "hooked wandering top",    16],
            [    143,    "Rainbow bad",    2],
            [    143,    "Rainbow bad",    2],
            [    145,    "Autogen bassline bottom",    2],
            [    145,    "UV pulse",    1],
            [    147,    "UV pulse slow",    2],
            [    147,    "UV pulse",    1],
            [    149,    "Autogen bassline bottom",    2],
            [    149,    "UV pulse slow",    2],
            [    151,    "RBBB 1 bar",    4],
            [    151,    "UV pulse slow",    2],
            [    155,    "Autogen Strobe",    1],
            [    155,    "RBBB 1 bar",    4],
            [    159,    "hooked wandering top",    16],
            [    159,    "Autogen bassline sidechain bottom",    2],
            [    175,    "UV pulse",    1],
            [    175,    "Autogen UV Strobe",    1],
            [    176,    "Autogen Strobe",    1],
            [    176,    "Rainbow bad",    2],
            [    178,    "Autogen UV Strobe",    1],
            [    178,    "Autogen bassline bottom",    2],
            [    180,    "hooked wandering top",    16],
            [    180,    "rainbow good slow top",    16],
            [    196,    "UV pulse slow",    2],
            [    196,    "Autogen bassline top",    2],
            [    198,    "hooked wandering bottom",    16],
            [    198,    "Autogen bassline bottom",    2],
            [    214,    "rainbow good slow top",    16],
            [    214,    "UV pulse",    1],
            [    230,    "Autogen bassline sidechain bottom",    2],
            [    230,    "UV pulse",    1],
            [    232,    "hooked wandering bottom",    16],
            [    232,    "Autogen Strobe",    1]
        ],
        "bpm": 96,
        "delay_lights": 0.256,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/Cheesecake.ogg"
    }
}