effects = {
    "g_Cheesecake": {
        "beats": [
            [    1,    "g_UV Strobe",    1],
            [    2,    "g_solid mixed double",    16],
            [    2,    "g_UV",    16],
            [    18,    "g_solid mixed cycle",    16],
            [    34,    "g_solid mixed cycle",    16],
            [    34,    "g_UV",    16],
            [    50,    "RGB Flash",    1],
            [    51,    "g_green sidechain bottom pulse",    16],
            [    67,    "g_solid mixed cycle",    16],
            [    67,    "g_UV",    16],
            [    83,    "g_cyan top pulse",    16],
            [    99,    "g_green sidechain bottom pulse",    16],
            [    99,    "g_UV",    16],
            [    115,    "g_solid mixed cycle",    16],
            [    115,    "g_UV",    16],
            [    131,    "g_UV pulse",    2],
            [    133,    "g_cyan top pulse",    16],
            [    149,    "g_solid top cycle",    16],
            [    149,    "g_UV",    16],
            [    165,    "g_solid mixed double",    16],
            [    165,    "g_UV",    16],
            [    181,    "g_Strobe",    1],
            [    182,    "g_solid mixed double",    16],
            [    182,    "g_UV",    16],
            [    198,    "g_green sidechain bottom pulse",    16],
            [    214,    "g_cyan top pulse",    16],
            [    230,    "g_UV Strobe",    1],
            [    231,    "g_UV pulse",    2],
            [    233,    "g_cyan top pulse",    16]
        ],
        "bpm": 96,
        "delay_lights": 0.256,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/Cheesecake.ogg",
        "was_autogenerated": True
    }
}