effects = {
    "g_cnam_slander_said_the_sky_cut": {
        "beats": [
            [    1,    "Ghosts riser",    4],
            [    1,    "Autogen UV Strobe",    1],
            [    5,    "Autogen Strobe",    1],
            [    5,    "hooked wandering bottom",    16],
            [    21,    "Ghosts riser",    4],
            [    21,    "hooked wandering bottom",    16],
            [    37,    "UV pulse slow",    2],
            [    37,    "UV pulse",    1],
            [    39,    "Autogen bassline top",    2],
            [    39,    "rainbow good slow top",    16],
            [    55,    "Autogen bassline bottom",    2],
            [    55,    "Rainbow bad",    2],
            [    57,    "UV pulse slow",    2],
            [    57,    "hooked wandering bottom",    16],
            [    73,    "hooked wandering top",    16],
            [    73,    "Autogen bassline top",    2],
            [    89,    "Autogen Strobe",    1],
            [    89,    "hooked wandering bottom",    16],
            [    105,    "UV pulse",    1],
            [    105,    "Ghosts riser",    4],
            [    109,    "Autogen UV Strobe",    1],
            [    109,    "Autogen Strobe",    1],
            [    110,    "Autogen bassline sidechain bottom",    2],
            [    110,    "Autogen bassline bottom",    2],
            [    112,    "UV pulse slow",    2],
            [    112,    "Rainbow bad",    2],
            [    114,    "Autogen bassline bottom",    2],
            [    114,    "Ghosts riser",    4],
            [    118,    "Autogen bassline sidechain bottom",    2],
            [    118,    "hooked wandering top",    16],
            [    134,    "Autogen Strobe",    1],
            [    134,    "Rainbow bad",    2],
            [    136,    "Ghosts riser",    4],
            [    136,    "UV pulse",    1],
            [    140,    "hooked wandering bottom",    16],
            [    140,    "rainbow good slow top",    16],
            [    156,    "hooked wandering top",    16],
            [    156,    "Autogen bassline bottom",    2],
            [    172,    "Autogen Strobe",    1],
            [    172,    "Rainbow bad",    2],
            [    174,    "Rainbow bad",    2],
            [    174,    "Rainbow bad",    2],
            [    176,    "Ghosts riser",    4],
            [    176,    "Autogen bassline sidechain bottom",    2],
            [    180,    "hooked wandering bottom",    16],
            [    180,    "hooked wandering bottom",    16],
            [    196,    "hooked wandering bottom",    16],
            [    196,    "hooked wandering bottom",    16],
            [    212,    "hooked wandering top",    16],
            [    212,    "Autogen UV Strobe",    1],
            [    228,    "Autogen bassline top",    2],
            [    228,    "hooked wandering bottom",    16],
            [    244,    "UV pulse",    1],
            [    244,    "hooked wandering top",    16],
            [    260,    "Autogen bassline bottom",    2],
            [    260,    "hooked wandering bottom",    16],
            [    276,    "Autogen UV Strobe",    1],
            [    276,    "UV pulse slow",    2],
            [    278,    "hooked wandering top",    16],
            [    278,    "RBBB 1 bar",    4],
            [    294,    "Autogen Strobe",    1],
            [    294,    "UV pulse",    1],
            [    295,    "hooked wandering top",    16],
            [    295,    "UV pulse slow",    2],
            [    311,    "Autogen UV Strobe",    1],
            [    311,    "Autogen Strobe",    1],
            [    312,    "RBBB 1 bar",    4],
            [    312,    "hooked wandering bottom",    16],
            [    328,    "Autogen bassline sidechain bottom",    2],
            [    328,    "hooked wandering bottom",    16],
            [    344,    "rainbow good slow top",    16],
            [    344,    "hooked wandering bottom",    16],
            [    360,    "rainbow good slow top",    16],
            [    360,    "Ghosts riser",    4],
            [    376,    "hooked wandering top",    16],
            [    376,    "Autogen Strobe",    1],
            [    392,    "UV pulse",    1],
            [    392,    "hooked wandering bottom",    16],
            [    408,    "UV pulse",    1],
            [    408,    "UV pulse slow",    2],
            [    410,    "UV pulse slow",    2],
            [    410,    "RBBB 1 bar",    4],
            [    414,    "Autogen Strobe",    1],
            [    414,    "Autogen bassline sidechain bottom",    2],
            [    416,    "Autogen UV Strobe",    1],
            [    416,    "UV pulse",    1],
            [    417,    "Autogen bassline bottom",    2],
            [    417,    "Ghosts riser",    4],
            [    421,    "RBBB 1 bar",    4],
            [    421,    "Autogen bassline top",    2],
            [    425,    "Autogen bassline bottom",    2],
            [    425,    "Autogen bassline bottom",    2],
            [    427,    "Rainbow bad",    2],
            [    427,    "Ghosts riser",    4],
            [    431,    "Autogen bassline sidechain bottom",    2],
            [    431,    "rainbow good slow top",    16],
            [    447,    "Ghosts riser",    4],
            [    447,    "Autogen bassline sidechain bottom",    2],
            [    451,    "RBBB 1 bar",    4],
            [    451,    "rainbow good slow top",    16],
            [    467,    "hooked wandering top",    16],
            [    467,    "Autogen bassline bottom",    2],
            [    483,    "UV pulse slow",    2],
            [    483,    "RBBB 1 bar",    4],
            [    487,    "hooked wandering top",    16],
            [    487,    "hooked wandering bottom",    16],
            [    503,    "UV pulse",    1],
            [    503,    "RBBB 1 bar",    4],
            [    507,    "RBBB 1 bar",    4],
            [    507,    "Autogen Strobe",    1],
            [    511,    "Autogen bassline top",    2],
            [    511,    "UV pulse",    1],
            [    513,    "UV pulse slow",    2],
            [    513,    "Autogen Strobe",    1],
            [    515,    "Autogen bassline top",    2],
            [    515,    "UV pulse slow",    2],
            [    517,    "rainbow good slow top",    16],
            [    517,    "hooked wandering bottom",    16],
            [    533,    "Autogen bassline sidechain bottom",    2],
            [    533,    "UV pulse slow",    2],
            [    535,    "hooked wandering top",    16],
            [    535,    "Autogen bassline bottom",    2],
            [    551,    "RBBB 1 bar",    4],
            [    551,    "Autogen bassline bottom",    2],
            [    555,    "Autogen Strobe",    1],
            [    555,    "RBBB 1 bar",    4],
            [    559,    "Autogen bassline sidechain bottom",    2],
            [    559,    "Autogen bassline sidechain bottom",    2],
            [    561,    "Ghosts riser",    4],
            [    561,    "UV pulse slow",    2],
            [    565,    "Rainbow bad",    2],
            [    565,    "Rainbow bad",    2],
            [    567,    "Autogen Strobe",    1],
            [    567,    "rainbow good slow top",    16],
            [    583,    "UV pulse slow",    2],
            [    583,    "hooked wandering bottom",    16],
            [    599,    "UV pulse",    1],
            [    599,    "UV pulse slow",    2],
            [    601,    "Autogen bassline top",    2],
            [    601,    "Autogen bassline top",    2],
            [    603,    "Rainbow bad",    2],
            [    603,    "Rainbow bad",    2],
            [    605,    "Autogen bassline sidechain bottom",    2],
            [    605,    "Ghosts riser",    4],
            [    609,    "UV pulse",    1],
            [    609,    "Autogen Strobe",    1],
            [    610,    "Autogen bassline top",    2],
            [    610,    "UV pulse slow",    2],
            [    612,    "Autogen bassline top",    2],
            [    612,    "Rainbow bad",    2],
            [    614,    "Rainbow bad",    2],
            [    614,    "Rainbow bad",    2],
            [    616,    "Autogen bassline bottom",    2],
            [    616,    "Ghosts riser",    4],
            [    620,    "Ghosts riser",    4],
            [    620,    "RBBB 1 bar",    4],
            [    624,    "hooked wandering bottom",    16],
            [    624,    "rainbow good slow top",    16],
            [    640,    "Autogen Strobe",    1],
            [    640,    "Rainbow bad",    2],
            [    642,    "hooked wandering bottom",    16],
            [    642,    "Autogen UV Strobe",    1],
            [    658,    "Autogen UV Strobe",    1],
            [    658,    "Rainbow bad",    2],
            [    660,    "hooked wandering top",    16],
            [    660,    "Rainbow bad",    2]
        ],
        "bpm": 125,
        "delay_lights": 0.40615,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/cnam_slander_said_the_sky_cut.ogg"
    }
}