effects = {
    "g_cnam_slander_said_the_sky_cut": {
        "beats": [
            [    1,    "g_green sidechain bottom pulse",    16],
            [    17,    "g_solid top cycle",    16],
            [    33,    "g_solid top cycle",    16],
            [    49,    "g_solid top cycle",    16],
            [    65,    "g_solid top cycle",    16],
            [    81,    "g_solid top cycle",    16],
            [    81,    "g_UV",    16],
            [    97,    "g_rainbow good top",    16],
            [    97,    "g_solid bottom cycle",    16],
            [    113,    "g_UV pulse",    1],
            [    114,    "g_cyan top pulse",    16],
            [    114,    "g_UV",    16],
            [    130,    "g_UV pulse",    2],
            [    132,    "g_UV Strobe",    1],
            [    133,    "g_UV pulse",    2],
            [    135,    "g_solid bottom cycle",    16],
            [    135,    "g_UV",    16],
            [    151,    "g_UV pulse",    4],
            [    155,    "g_purple green bottom pulse",    16],
            [    155,    "g_UV",    16],
            [    171,    "g_cyan top pulse",    16],
            [    171,    "g_green sidechain bottom pulse",    16],
            [    171,    "g_UV",    16],
            [    187,    "g_cyan top pulse",    16],
            [    187,    "g_UV",    16],
            [    203,    "g_UV pulse",    2],
            [    205,    "g_rainbow good top",    16],
            [    205,    "g_purple green bottom pulse",    16],
            [    221,    "g_UV pulse",    1],
            [    222,    "RGB Flash",    1],
            [    223,    "g_cyan top pulse",    16],
            [    223,    "g_UV",    16],
            [    239,    "g_solid top cycle",    16],
            [    239,    "g_UV",    16],
            [    255,    "g_solid mixed double",    16],
            [    255,    "g_UV",    16],
            [    271,    "g_cyan top pulse",    16],
            [    287,    "g_cyan top pulse",    16],
            [    287,    "g_green sidechain bottom pulse",    16],
            [    287,    "g_UV",    16],
            [    303,    "g_solid bottom cycle",    16],
            [    303,    "g_UV",    16],
            [    319,    "g_solid mixed cycle",    16],
            [    319,    "g_UV",    16],
            [    335,    "g_green sidechain bottom pulse",    16],
            [    351,    "g_UV pulse",    1],
            [    352,    "g_UV pulse",    4],
            [    356,    "g_UV pulse",    4],
            [    360,    "g_UV pulse",    1],
            [    361,    "g_UV Strobe",    1],
            [    362,    "g_purple green bottom pulse",    16],
            [    362,    "g_UV",    16],
            [    378,    "g_UV pulse",    1],
            [    379,    "g_UV pulse",    2],
            [    381,    "g_cyan top pulse",    16],
            [    381,    "g_UV",    16],
            [    397,    "g_rainbow good top",    16],
            [    397,    "g_solid bottom cycle",    16],
            [    413,    "g_cyan top pulse",    16],
            [    413,    "g_green sidechain bottom pulse",    16],
            [    429,    "g_purple green bottom pulse",    16],
            [    445,    "g_UV pulse",    1],
            [    446,    "g_solid top cycle",    16],
            [    446,    "g_purple green bottom pulse",    16],
            [    446,    "g_UV",    16],
            [    462,    "g_cyan top pulse",    16],
            [    462,    "g_green sidechain bottom pulse",    16],
            [    462,    "g_UV",    16],
            [    478,    "g_solid mixed double",    16],
            [    478,    "g_UV",    16],
            [    494,    "g_UV pulse",    4],
            [    498,    "g_solid mixed double",    16],
            [    514,    "g_solid top cycle",    16],
            [    514,    "g_UV",    16],
            [    530,    "g_UV pulse",    2],
            [    532,    "g_solid top cycle",    16],
            [    532,    "g_green sidechain bottom pulse",    16],
            [    532,    "g_UV",    16],
            [    548,    "g_solid top cycle",    16],
            [    548,    "g_UV",    16],
            [    564,    "g_solid top cycle",    16],
            [    564,    "g_UV",    16],
            [    580,    "g_UV pulse",    2],
            [    582,    "g_solid mixed cycle",    16],
            [    598,    "g_solid mixed double",    16],
            [    614,    "RGB Flash",    1],
            [    615,    "g_cyan top pulse",    16],
            [    631,    "RGB Flash",    1],
            [    632,    "g_UV pulse",    2],
            [    634,    "g_green sidechain bottom pulse",    16],
            [    634,    "g_UV",    16],
            [    650,    "g_solid mixed cycle",    16],
            [    666,    "g_UV pulse",    4],
            [    670,    "g_solid mixed double",    16]
        ],
        "bpm": 125,
        "delay_lights": 0.40615,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/cnam_slander_said_the_sky_cut.ogg",
        "was_autogenerated": True
    }
}