effects = {
    "g_cnam_slander_said_the_sky_cut": {
        "beats": [
            [    1,    "Autogen UV Strobe",    1],
            [    1,    "UV pulse",    1],
            [    2,    "rainbow good slow top",    16],
            [    2,    "RBBB 1 bar",    4],
            [    18,    "hooked wandering bottom",    16],
            [    18,    "Autogen UV Strobe",    1],
            [    34,    "hooked wandering top",    16],
            [    34,    "Autogen UV Strobe",    1],
            [    50,    "Autogen bassline bottom",    2],
            [    50,    "Rainbow bad",    2],
            [    52,    "hooked wandering bottom",    16],
            [    52,    "Ghosts riser",    4],
            [    68,    "Autogen bassline bottom",    2],
            [    68,    "UV pulse",    1],
            [    70,    "Autogen bassline sidechain bottom",    2],
            [    70,    "Rainbow bad",    2],
            [    72,    "Autogen bassline top",    2],
            [    72,    "hooked wandering bottom",    16],
            [    88,    "Rainbow bad",    2],
            [    88,    "hooked wandering bottom",    16],
            [    104,    "UV pulse",    1],
            [    104,    "Rainbow bad",    2],
            [    106,    "Autogen bassline top",    2],
            [    106,    "Rainbow bad",    2],
            [    108,    "rainbow good slow top",    16],
            [    108,    "hooked wandering bottom",    16],
            [    124,    "Rainbow bad",    2],
            [    124,    "Autogen bassline bottom",    2],
            [    126,    "Autogen UV Strobe",    1],
            [    126,    "Autogen bassline sidechain bottom",    2],
            [    128,    "Ghosts riser",    4],
            [    128,    "RBBB 1 bar",    4],
            [    132,    "Autogen bassline bottom",    2],
            [    132,    "RBBB 1 bar",    4],
            [    136,    "Ghosts riser",    4],
            [    136,    "Rainbow bad",    2],
            [    140,    "UV pulse",    1],
            [    140,    "rainbow good slow top",    16],
            [    156,    "hooked wandering bottom",    16],
            [    156,    "Rainbow bad",    2],
            [    172,    "Ghosts riser",    4],
            [    172,    "Autogen bassline top",    2],
            [    176,    "Autogen bassline bottom",    2],
            [    176,    "Rainbow bad",    2],
            [    178,    "Rainbow bad",    2],
            [    178,    "Autogen bassline top",    2],
            [    180,    "Ghosts riser",    4],
            [    180,    "Autogen UV Strobe",    1],
            [    184,    "Autogen Strobe",    1],
            [    184,    "UV pulse",    1],
            [    185,    "Autogen bassline top",    2],
            [    185,    "Autogen bassline sidechain bottom",    2],
            [    187,    "rainbow good slow top",    16],
            [    187,    "Ghosts riser",    4],
            [    203,    "Autogen UV Strobe",    1],
            [    203,    "Autogen bassline top",    2],
            [    205,    "Autogen bassline top",    2],
            [    205,    "hooked wandering bottom",    16],
            [    221,    "Autogen bassline bottom",    2],
            [    221,    "hooked wandering top",    16],
            [    237,    "RBBB 1 bar",    4],
            [    237,    "Autogen UV Strobe",    1],
            [    241,    "Autogen bassline bottom",    2],
            [    241,    "hooked wandering top",    16],
            [    257,    "Autogen Strobe",    1],
            [    257,    "UV pulse",    1],
            [    258,    "Autogen bassline bottom",    2],
            [    258,    "UV pulse",    1],
            [    260,    "Autogen Strobe",    1],
            [    260,    "Autogen Strobe",    1],
            [    261,    "hooked wandering bottom",    16],
            [    261,    "Autogen bassline sidechain bottom",    2],
            [    277,    "UV pulse slow",    2],
            [    277,    "hooked wandering top",    16],
            [    293,    "Autogen bassline top",    2],
            [    293,    "Ghosts riser",    4],
            [    297,    "hooked wandering bottom",    16],
            [    297,    "Autogen bassline top",    2],
            [    313,    "hooked wandering bottom",    16],
            [    313,    "hooked wandering bottom",    16],
            [    329,    "RBBB 1 bar",    4],
            [    329,    "Autogen bassline top",    2],
            [    333,    "rainbow good slow top",    16],
            [    333,    "Ghosts riser",    4],
            [    349,    "RBBB 1 bar",    4],
            [    349,    "hooked wandering bottom",    16],
            [    365,    "RBBB 1 bar",    4],
            [    365,    "Autogen bassline bottom",    2],
            [    369,    "RBBB 1 bar",    4],
            [    369,    "RBBB 1 bar",    4],
            [    373,    "Ghosts riser",    4],
            [    373,    "UV pulse",    1],
            [    377,    "Rainbow bad",    2],
            [    377,    "Autogen bassline bottom",    2],
            [    379,    "UV pulse",    1],
            [    379,    "RBBB 1 bar",    4],
            [    383,    "UV pulse",    1],
            [    383,    "Autogen Strobe",    1],
            [    384,    "Rainbow bad",    2],
            [    384,    "rainbow good slow top",    16],
            [    400,    "rainbow good slow top",    16],
            [    400,    "Autogen bassline bottom",    2],
            [    416,    "Autogen Strobe",    1],
            [    416,    "RBBB 1 bar",    4],
            [    420,    "hooked wandering bottom",    16],
            [    420,    "RBBB 1 bar",    4],
            [    436,    "rainbow good slow top",    16],
            [    436,    "Rainbow bad",    2],
            [    452,    "hooked wandering top",    16],
            [    452,    "hooked wandering bottom",    16],
            [    468,    "Ghosts riser",    4],
            [    468,    "Autogen bassline bottom",    2],
            [    472,    "UV pulse",    1],
            [    472,    "Autogen bassline sidechain bottom",    2],
            [    474,    "Ghosts riser",    4],
            [    474,    "Autogen UV Strobe",    1],
            [    478,    "Autogen Strobe",    1],
            [    478,    "rainbow good slow top",    16],
            [    494,    "Rainbow bad",    2],
            [    494,    "Autogen bassline top",    2],
            [    496,    "UV pulse",    1],
            [    496,    "hooked wandering top",    16],
            [    512,    "Autogen Strobe",    1],
            [    512,    "hooked wandering bottom",    16],
            [    528,    "UV pulse slow",    2],
            [    528,    "UV pulse slow",    2],
            [    530,    "hooked wandering top",    16],
            [    530,    "Autogen bassline bottom",    2],
            [    546,    "Autogen bassline top",    2],
            [    546,    "RBBB 1 bar",    4],
            [    550,    "rainbow good slow top",    16],
            [    550,    "Autogen UV Strobe",    1],
            [    566,    "Rainbow bad",    2],
            [    566,    "RBBB 1 bar",    4],
            [    570,    "hooked wandering top",    16],
            [    570,    "Autogen bassline sidechain bottom",    2],
            [    586,    "Autogen Strobe",    1],
            [    586,    "UV pulse slow",    2],
            [    588,    "UV pulse slow",    2],
            [    588,    "rainbow good slow top",    16],
            [    604,    "RBBB 1 bar",    4],
            [    604,    "UV pulse",    1],
            [    608,    "Ghosts riser",    4],
            [    608,    "Autogen Strobe",    1],
            [    612,    "hooked wandering top",    16],
            [    612,    "rainbow good slow top",    16],
            [    628,    "Rainbow bad",    2],
            [    628,    "Ghosts riser",    4],
            [    632,    "Ghosts riser",    4],
            [    632,    "RBBB 1 bar",    4],
            [    636,    "hooked wandering bottom",    16],
            [    636,    "UV pulse",    1],
            [    652,    "Rainbow bad",    2],
            [    652,    "Autogen bassline bottom",    2],
            [    654,    "Autogen Strobe",    1],
            [    654,    "hooked wandering bottom",    16],
            [    670,    "Ghosts riser",    4],
            [    670,    "Autogen bassline sidechain bottom",    2]
        ],
        "bpm": 125,
        "delay_lights": 0.40615,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/cnam_slander_said_the_sky_cut.ogg"
    }
}