effects = {
    "g_deadmau5 & Kaskade - I Remember (HQ)": {
        "beats": [
            [    1,    "Autogen Strobe",    1],
            [    1,    "UV pulse",    1],
            [    2,    "rainbow good slow top",    16],
            [    2,    "Autogen Strobe",    1],
            [    18,    "RBBB 1 bar",    4],
            [    18,    "hooked wandering bottom",    16],
            [    34,    "Autogen UV Strobe",    1],
            [    34,    "UV pulse",    1],
            [    35,    "RBBB 1 bar",    4],
            [    35,    "Autogen Strobe",    1],
            [    39,    "RBBB 1 bar",    4],
            [    39,    "hooked wandering top",    16],
            [    55,    "Autogen UV Strobe",    1],
            [    55,    "rainbow good slow top",    16],
            [    71,    "Rainbow bad",    2],
            [    71,    "Autogen UV Strobe",    1],
            [    73,    "hooked wandering bottom",    16],
            [    73,    "Autogen bassline top",    2],
            [    89,    "hooked wandering top",    16],
            [    89,    "hooked wandering top",    16],
            [    105,    "Ghosts riser",    4],
            [    105,    "Autogen Strobe",    1],
            [    109,    "Autogen Strobe",    1],
            [    109,    "Autogen bassline bottom",    2],
            [    111,    "rainbow good slow top",    16],
            [    111,    "Autogen UV Strobe",    1],
            [    127,    "Autogen Strobe",    1],
            [    127,    "UV pulse",    1],
            [    128,    "Autogen bassline sidechain bottom",    2],
            [    128,    "UV pulse slow",    2],
            [    130,    "RBBB 1 bar",    4],
            [    130,    "Autogen bassline sidechain bottom",    2],
            [    134,    "rainbow good slow top",    16],
            [    134,    "Rainbow bad",    2],
            [    150,    "Autogen UV Strobe",    1],
            [    150,    "hooked wandering bottom",    16],
            [    166,    "hooked wandering top",    16],
            [    166,    "Autogen UV Strobe",    1],
            [    182,    "hooked wandering top",    16],
            [    182,    "Autogen bassline bottom",    2],
            [    198,    "Autogen bassline top",    2],
            [    198,    "rainbow good slow top",    16],
            [    214,    "Autogen bassline top",    2],
            [    214,    "Autogen bassline bottom",    2],
            [    216,    "hooked wandering top",    16],
            [    216,    "hooked wandering bottom",    16],
            [    232,    "rainbow good slow top",    16],
            [    232,    "Autogen bassline sidechain bottom",    2],
            [    248,    "Autogen bassline top",    2],
            [    248,    "hooked wandering top",    16],
            [    264,    "Ghosts riser",    4],
            [    264,    "UV pulse slow",    2],
            [    268,    "UV pulse slow",    2],
            [    268,    "hooked wandering top",    16],
            [    284,    "Ghosts riser",    4],
            [    284,    "RBBB 1 bar",    4],
            [    288,    "rainbow good slow top",    16],
            [    288,    "RBBB 1 bar",    4],
            [    304,    "Autogen bassline sidechain bottom",    2],
            [    304,    "UV pulse",    1],
            [    306,    "hooked wandering top",    16],
            [    306,    "Autogen bassline sidechain bottom",    2],
            [    322,    "rainbow good slow top",    16],
            [    322,    "UV pulse",    1],
            [    338,    "RBBB 1 bar",    4],
            [    338,    "Autogen UV Strobe",    1],
            [    342,    "UV pulse",    1],
            [    342,    "Autogen bassline sidechain bottom",    2],
            [    344,    "rainbow good slow top",    16],
            [    344,    "UV pulse",    1],
            [    360,    "rainbow good slow top",    16],
            [    360,    "Autogen bassline bottom",    2],
            [    376,    "Autogen UV Strobe",    1],
            [    376,    "UV pulse slow",    2],
            [    378,    "RBBB 1 bar",    4],
            [    378,    "hooked wandering bottom",    16],
            [    394,    "UV pulse slow",    2],
            [    394,    "Autogen UV Strobe",    1],
            [    396,    "Autogen UV Strobe",    1],
            [    396,    "Autogen bassline top",    2],
            [    398,    "Ghosts riser",    4],
            [    398,    "hooked wandering bottom",    16],
            [    414,    "Rainbow bad",    2],
            [    414,    "rainbow good slow top",    16],
            [    430,    "Autogen UV Strobe",    1],
            [    430,    "hooked wandering top",    16],
            [    446,    "Ghosts riser",    4],
            [    446,    "Autogen bassline sidechain bottom",    2],
            [    450,    "RBBB 1 bar",    4],
            [    450,    "hooked wandering top",    16],
            [    466,    "hooked wandering bottom",    16],
            [    466,    "Autogen bassline bottom",    2],
            [    482,    "Rainbow bad",    2],
            [    482,    "Autogen Strobe",    1],
            [    484,    "Autogen Strobe",    1],
            [    484,    "hooked wandering bottom",    16],
            [    500,    "Autogen UV Strobe",    1],
            [    500,    "Autogen UV Strobe",    1],
            [    501,    "rainbow good slow top",    16],
            [    501,    "hooked wandering bottom",    16],
            [    517,    "rainbow good slow top",    16],
            [    517,    "Rainbow bad",    2],
            [    533,    "UV pulse slow",    2],
            [    533,    "Autogen Strobe",    1],
            [    535,    "Autogen bassline sidechain bottom",    2],
            [    535,    "UV pulse",    1],
            [    537,    "Autogen bassline sidechain bottom",    2],
            [    537,    "UV pulse",    1],
            [    539,    "Autogen bassline sidechain bottom",    2],
            [    539,    "UV pulse",    1],
            [    541,    "hooked wandering bottom",    16],
            [    541,    "Autogen UV Strobe",    1],
            [    557,    "hooked wandering top",    16],
            [    557,    "UV pulse",    1],
            [    573,    "Autogen bassline bottom",    2],
            [    573,    "Autogen bassline bottom",    2],
            [    575,    "UV pulse",    1],
            [    575,    "hooked wandering top",    16],
            [    591,    "UV pulse",    1],
            [    591,    "Autogen Strobe",    1],
            [    592,    "Rainbow bad",    2],
            [    592,    "hooked wandering top",    16],
            [    608,    "Autogen Strobe",    1],
            [    608,    "Rainbow bad",    2],
            [    610,    "UV pulse",    1],
            [    610,    "Autogen UV Strobe",    1],
            [    611,    "Autogen UV Strobe",    1],
            [    611,    "UV pulse",    1],
            [    612,    "rainbow good slow top",    16],
            [    612,    "Autogen bassline sidechain bottom",    2],
            [    628,    "Autogen UV Strobe",    1],
            [    628,    "rainbow good slow top",    16],
            [    644,    "rainbow good slow top",    16],
            [    644,    "hooked wandering bottom",    16],
            [    660,    "Autogen bassline sidechain bottom",    2],
            [    660,    "UV pulse",    1],
            [    662,    "Autogen Strobe",    1],
            [    662,    "RBBB 1 bar",    4],
            [    666,    "UV pulse slow",    2],
            [    666,    "Autogen bassline bottom",    2],
            [    668,    "hooked wandering top",    16],
            [    668,    "rainbow good slow top",    16],
            [    684,    "hooked wandering top",    16],
            [    684,    "Autogen Strobe",    1],
            [    700,    "Ghosts riser",    4],
            [    700,    "Autogen bassline sidechain bottom",    2],
            [    704,    "hooked wandering bottom",    16],
            [    704,    "hooked wandering bottom",    16],
            [    720,    "Autogen Strobe",    1],
            [    720,    "Ghosts riser",    4],
            [    724,    "rainbow good slow top",    16],
            [    724,    "Autogen bassline bottom",    2],
            [    740,    "Autogen bassline bottom",    2],
            [    740,    "rainbow good slow top",    16],
            [    756,    "UV pulse",    1],
            [    756,    "rainbow good slow top",    16],
            [    772,    "rainbow good slow top",    16],
            [    772,    "Ghosts riser",    4],
            [    788,    "RBBB 1 bar",    4],
            [    788,    "Autogen bassline top",    2],
            [    792,    "Rainbow bad",    2],
            [    792,    "rainbow good slow top",    16],
            [    808,    "rainbow good slow top",    16],
            [    808,    "UV pulse slow",    2],
            [    824,    "Ghosts riser",    4],
            [    824,    "RBBB 1 bar",    4],
            [    828,    "Rainbow bad",    2],
            [    828,    "UV pulse slow",    2],
            [    830,    "Autogen Strobe",    1],
            [    830,    "UV pulse",    1],
            [    831,    "Autogen bassline bottom",    2],
            [    831,    "Autogen Strobe",    1],
            [    833,    "Autogen bassline bottom",    2],
            [    833,    "Autogen bassline sidechain bottom",    2],
            [    835,    "RBBB 1 bar",    4],
            [    835,    "rainbow good slow top",    16],
            [    851,    "Ghosts riser",    4],
            [    851,    "rainbow good slow top",    16],
            [    867,    "RBBB 1 bar",    4],
            [    867,    "hooked wandering top",    16],
            [    883,    "Autogen UV Strobe",    1],
            [    883,    "rainbow good slow top",    16],
            [    899,    "UV pulse slow",    2],
            [    899,    "RBBB 1 bar",    4],
            [    903,    "UV pulse slow",    2],
            [    903,    "Autogen Strobe",    1],
            [    905,    "RBBB 1 bar",    4],
            [    905,    "hooked wandering bottom",    16],
            [    921,    "RBBB 1 bar",    4],
            [    921,    "Autogen bassline sidechain bottom",    2],
            [    925,    "Autogen Strobe",    1],
            [    925,    "Autogen Strobe",    1],
            [    926,    "RBBB 1 bar",    4],
            [    926,    "Autogen Strobe",    1],
            [    930,    "Ghosts riser",    4],
            [    930,    "Autogen bassline top",    2],
            [    934,    "hooked wandering bottom",    16],
            [    934,    "Autogen bassline bottom",    2],
            [    950,    "Rainbow bad",    2],
            [    950,    "Ghosts riser",    4],
            [    954,    "hooked wandering top",    16],
            [    954,    "Autogen Strobe",    1],
            [    970,    "rainbow good slow top",    16],
            [    970,    "hooked wandering top",    16],
            [    986,    "Ghosts riser",    4],
            [    986,    "Autogen bassline sidechain bottom",    2],
            [    990,    "hooked wandering top",    16],
            [    990,    "Autogen Strobe",    1],
            [    1006,    "hooked wandering top",    16],
            [    1006,    "UV pulse slow",    2],
            [    1022,    "hooked wandering top",    16],
            [    1022,    "rainbow good slow top",    16],
            [    1038,    "hooked wandering bottom",    16],
            [    1038,    "Autogen bassline bottom",    2],
            [    1054,    "hooked wandering bottom",    16],
            [    1054,    "RBBB 1 bar",    4],
            [    1070,    "Autogen bassline sidechain bottom",    2],
            [    1070,    "rainbow good slow top",    16],
            [    1086,    "UV pulse",    1],
            [    1086,    "UV pulse",    1],
            [    1087,    "Rainbow bad",    2],
            [    1087,    "Autogen bassline sidechain bottom",    2],
            [    1089,    "rainbow good slow top",    16],
            [    1089,    "hooked wandering bottom",    16],
            [    1105,    "UV pulse slow",    2],
            [    1105,    "Autogen bassline sidechain bottom",    2],
            [    1107,    "Autogen UV Strobe",    1],
            [    1107,    "Autogen bassline sidechain bottom",    2],
            [    1109,    "hooked wandering bottom",    16],
            [    1109,    "RBBB 1 bar",    4],
            [    1125,    "rainbow good slow top",    16],
            [    1125,    "RBBB 1 bar",    4],
            [    1141,    "rainbow good slow top",    16],
            [    1141,    "UV pulse",    1],
            [    1157,    "rainbow good slow top",    16],
            [    1157,    "rainbow good slow top",    16],
            [    1173,    "Autogen bassline bottom",    2],
            [    1173,    "Autogen UV Strobe",    1],
            [    1175,    "Autogen bassline top",    2],
            [    1175,    "Ghosts riser",    4],
            [    1179,    "UV pulse slow",    2],
            [    1179,    "Rainbow bad",    2],
            [    1181,    "rainbow good slow top",    16],
            [    1181,    "Rainbow bad",    2],
            [    1197,    "Rainbow bad",    2],
            [    1197,    "hooked wandering top",    16],
            [    1213,    "UV pulse slow",    2],
            [    1213,    "Autogen bassline sidechain bottom",    2],
            [    1215,    "RBBB 1 bar",    4],
            [    1215,    "Autogen UV Strobe",    1],
            [    1219,    "rainbow good slow top",    16],
            [    1219,    "hooked wandering top",    16],
            [    1235,    "hooked wandering bottom",    16],
            [    1235,    "RBBB 1 bar",    4],
            [    1251,    "Autogen bassline sidechain bottom",    2],
            [    1251,    "Autogen bassline bottom",    2],
            [    1253,    "Autogen bassline sidechain bottom",    2],
            [    1253,    "Autogen bassline top",    2],
            [    1255,    "rainbow good slow top",    16],
            [    1255,    "RBBB 1 bar",    4]
        ],
        "bpm": 128,
        "delay_lights": 0.12,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/deadmau5 & Kaskade - I Remember (HQ).ogg"
    }
}