effects = {
    "g_deadmau5 & Kaskade - I Remember (HQ)": {
        "beats": [
            [    1,    "g_solid mixed double",    16],
            [    1,    "g_UV",    16],
            [    17,    "g_green sidechain bottom pulse",    16],
            [    17,    "g_UV",    16],
            [    33,    "g_cyan top pulse",    16],
            [    33,    "g_purple green bottom pulse",    16],
            [    49,    "g_cyan top pulse",    16],
            [    65,    "RGB Flash",    1],
            [    66,    "g_solid top cycle",    16],
            [    66,    "g_purple green bottom pulse",    16],
            [    82,    "g_Strobe",    1],
            [    83,    "g_UV pulse",    1],
            [    84,    "g_UV pulse",    2],
            [    86,    "g_green sidechain bottom pulse",    16],
            [    102,    "g_UV pulse",    4],
            [    106,    "RGB Flash",    1],
            [    107,    "g_solid bottom cycle",    16],
            [    107,    "g_UV",    16],
            [    123,    "g_Strobe",    1],
            [    124,    "g_solid top cycle",    16],
            [    124,    "g_green sidechain bottom pulse",    16],
            [    140,    "g_solid top cycle",    16],
            [    140,    "g_UV",    16],
            [    156,    "g_solid mixed double",    16],
            [    172,    "g_cyan top pulse",    16],
            [    172,    "g_solid bottom cycle",    16],
            [    188,    "g_solid top cycle",    16],
            [    188,    "g_green sidechain bottom pulse",    16],
            [    188,    "g_UV",    16],
            [    204,    "g_solid top cycle",    16],
            [    204,    "g_green sidechain bottom pulse",    16],
            [    204,    "g_UV",    16],
            [    220,    "g_cyan top pulse",    16],
            [    220,    "g_solid bottom cycle",    16],
            [    236,    "g_solid mixed double",    16],
            [    252,    "g_Strobe",    1],
            [    253,    "g_solid bottom cycle",    16],
            [    253,    "g_UV",    16],
            [    269,    "g_solid top cycle",    16],
            [    285,    "g_solid mixed double",    16],
            [    285,    "g_UV",    16],
            [    301,    "g_solid mixed double",    16],
            [    317,    "g_cyan top pulse",    16],
            [    333,    "g_solid top cycle",    16],
            [    333,    "g_purple green bottom pulse",    16],
            [    333,    "g_UV",    16],
            [    349,    "g_green sidechain bottom pulse",    16],
            [    365,    "RGB Flash",    1],
            [    366,    "g_cyan top pulse",    16],
            [    382,    "g_UV Strobe",    1],
            [    383,    "g_cyan top pulse",    16],
            [    399,    "g_solid top cycle",    16],
            [    399,    "g_solid bottom cycle",    16],
            [    415,    "g_UV Strobe",    1],
            [    416,    "g_solid top cycle",    16],
            [    416,    "g_purple green bottom pulse",    16],
            [    432,    "g_solid bottom cycle",    16],
            [    448,    "RGB Flash",    1],
            [    449,    "g_solid mixed cycle",    16],
            [    449,    "g_UV",    16],
            [    465,    "g_solid top cycle",    16],
            [    465,    "g_purple green bottom pulse",    16],
            [    465,    "g_UV",    16],
            [    481,    "g_solid mixed cycle",    16],
            [    497,    "g_solid bottom cycle",    16],
            [    513,    "g_solid mixed double",    16],
            [    513,    "g_UV",    16],
            [    529,    "g_cyan top pulse",    16],
            [    529,    "g_purple green bottom pulse",    16],
            [    529,    "g_UV",    16],
            [    545,    "g_solid bottom cycle",    16],
            [    545,    "g_UV",    16],
            [    561,    "g_UV pulse",    2],
            [    563,    "g_UV pulse",    4],
            [    567,    "g_purple green bottom pulse",    16],
            [    583,    "g_UV pulse",    4],
            [    587,    "g_solid mixed double",    16],
            [    587,    "g_UV",    16],
            [    603,    "g_cyan top pulse",    16],
            [    619,    "g_Strobe",    1],
            [    620,    "g_rainbow good top",    16],
            [    620,    "g_solid bottom cycle",    16],
            [    636,    "g_UV pulse",    4],
            [    640,    "g_solid mixed cycle",    16],
            [    656,    "g_cyan top pulse",    16],
            [    672,    "g_UV pulse",    2],
            [    674,    "g_solid mixed cycle",    16],
            [    674,    "g_UV",    16],
            [    690,    "g_solid top cycle",    16],
            [    690,    "g_solid bottom cycle",    16],
            [    706,    "g_UV pulse",    4],
            [    710,    "g_cyan top pulse",    16],
            [    710,    "g_UV",    16],
            [    726,    "g_solid top cycle",    16],
            [    726,    "g_purple green bottom pulse",    16],
            [    742,    "g_solid mixed cycle",    16],
            [    758,    "g_purple green bottom pulse",    16],
            [    758,    "g_UV",    16],
            [    774,    "g_green sidechain bottom pulse",    16],
            [    774,    "g_UV",    16],
            [    790,    "g_UV pulse",    4],
            [    794,    "g_Strobe",    1],
            [    795,    "g_solid top cycle",    16],
            [    811,    "g_solid mixed double",    16],
            [    811,    "g_UV",    16],
            [    827,    "g_UV pulse",    4],
            [    831,    "g_UV pulse",    2],
            [    833,    "g_rainbow good top",    16],
            [    833,    "g_purple green bottom pulse",    16],
            [    849,    "g_solid top cycle",    16],
            [    865,    "g_cyan top pulse",    16],
            [    865,    "g_purple green bottom pulse",    16],
            [    865,    "g_UV",    16],
            [    881,    "g_rainbow good slow top",    16],
            [    881,    "g_purple green bottom pulse",    16],
            [    897,    "g_solid top cycle",    16],
            [    897,    "g_purple green bottom pulse",    16],
            [    913,    "RGB Flash",    1],
            [    914,    "g_cyan top pulse",    16],
            [    930,    "RGB Flash",    1],
            [    931,    "g_rainbow good slow top",    16],
            [    931,    "g_purple green bottom pulse",    16],
            [    947,    "g_UV Strobe",    1],
            [    948,    "g_UV pulse",    1],
            [    949,    "g_UV pulse",    4],
            [    953,    "g_UV pulse",    1],
            [    954,    "g_purple green bottom pulse",    16],
            [    954,    "g_UV",    16],
            [    970,    "g_UV pulse",    2],
            [    972,    "g_purple green bottom pulse",    16],
            [    988,    "g_UV Strobe",    1],
            [    989,    "g_solid mixed double",    16],
            [    989,    "g_UV",    16],
            [    1005,    "g_solid top cycle",    16],
            [    1021,    "g_UV pulse",    2],
            [    1023,    "g_solid top cycle",    16],
            [    1023,    "g_green sidechain bottom pulse",    16],
            [    1023,    "g_UV",    16],
            [    1039,    "g_solid top cycle",    16],
            [    1055,    "g_UV pulse",    2],
            [    1057,    "g_rainbow good top",    16],
            [    1057,    "g_purple green bottom pulse",    16],
            [    1073,    "g_Strobe",    1],
            [    1074,    "RGB Flash",    1],
            [    1075,    "g_cyan top pulse",    16],
            [    1091,    "g_rainbow good slow top",    16],
            [    1091,    "g_green sidechain bottom pulse",    16],
            [    1107,    "g_solid top cycle",    16],
            [    1107,    "g_purple green bottom pulse",    16],
            [    1107,    "g_UV",    16],
            [    1123,    "g_UV pulse",    2],
            [    1125,    "g_UV pulse",    1],
            [    1126,    "g_green sidechain bottom pulse",    16],
            [    1126,    "g_UV",    16],
            [    1142,    "g_UV pulse",    4],
            [    1146,    "RGB Flash",    1],
            [    1147,    "g_solid top cycle",    16],
            [    1147,    "g_UV",    16],
            [    1163,    "g_UV pulse",    1],
            [    1164,    "g_UV pulse",    1],
            [    1165,    "g_rainbow good top",    16],
            [    1165,    "g_solid bottom cycle",    16],
            [    1181,    "g_solid mixed double",    16],
            [    1197,    "g_UV pulse",    4],
            [    1201,    "g_rainbow good slow top",    16],
            [    1201,    "g_green sidechain bottom pulse",    16],
            [    1217,    "g_solid top cycle",    16],
            [    1217,    "g_purple green bottom pulse",    16],
            [    1217,    "g_UV",    16],
            [    1233,    "g_solid mixed cycle",    16],
            [    1233,    "g_UV",    16],
            [    1249,    "RGB Flash",    1],
            [    1250,    "g_UV pulse",    1],
            [    1251,    "g_UV pulse",    4],
            [    1255,    "g_solid top cycle",    16],
            [    1255,    "g_UV",    16]
        ],
        "bpm": 128,
        "delay_lights": 0.12,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/deadmau5 & Kaskade - I Remember (HQ).ogg"
    }
}