effects = {
    "g_deadmau5 feat Rob Swire - Ghosts N Stuff": {
        "beats": [
            [    1,    "UV pulse",    1],
            [    1,    "hooked wandering bottom",    16],
            [    17,    "Autogen bassline top",    2],
            [    17,    "Autogen Strobe",    1],
            [    19,    "rainbow good slow top",    16],
            [    19,    "Autogen bassline top",    2],
            [    35,    "UV pulse slow",    2],
            [    35,    "hooked wandering bottom",    16],
            [    51,    "RBBB 1 bar",    4],
            [    51,    "RBBB 1 bar",    4],
            [    55,    "RBBB 1 bar",    4],
            [    55,    "Autogen bassline top",    2],
            [    59,    "rainbow good slow top",    16],
            [    59,    "Autogen bassline sidechain bottom",    2],
            [    75,    "Autogen Strobe",    1],
            [    75,    "Rainbow bad",    2],
            [    77,    "UV pulse slow",    2],
            [    77,    "RBBB 1 bar",    4],
            [    81,    "Autogen Strobe",    1],
            [    81,    "Autogen bassline top",    2],
            [    83,    "Autogen UV Strobe",    1],
            [    83,    "Autogen bassline bottom",    2],
            [    85,    "hooked wandering bottom",    16],
            [    85,    "Autogen bassline bottom",    2],
            [    101,    "Autogen UV Strobe",    1],
            [    101,    "Autogen bassline top",    2],
            [    103,    "hooked wandering top",    16],
            [    103,    "Autogen Strobe",    1],
            [    119,    "Autogen Strobe",    1],
            [    119,    "Rainbow bad",    2],
            [    121,    "rainbow good slow top",    16],
            [    121,    "rainbow good slow top",    16],
            [    137,    "Autogen bassline top",    2],
            [    137,    "Autogen UV Strobe",    1],
            [    139,    "hooked wandering bottom",    16],
            [    139,    "Autogen bassline sidechain bottom",    2],
            [    155,    "Autogen bassline sidechain bottom",    2],
            [    155,    "Ghosts riser",    4],
            [    159,    "Autogen Strobe",    1],
            [    159,    "Autogen UV Strobe",    1],
            [    160,    "hooked wandering top",    16],
            [    160,    "UV pulse",    1],
            [    176,    "Autogen bassline sidechain bottom",    2],
            [    176,    "Rainbow bad",    2],
            [    178,    "UV pulse slow",    2],
            [    178,    "Autogen bassline top",    2],
            [    180,    "Rainbow bad",    2],
            [    180,    "Ghosts riser",    4],
            [    184,    "hooked wandering bottom",    16],
            [    184,    "RBBB 1 bar",    4],
            [    200,    "Autogen bassline top",    2],
            [    200,    "RBBB 1 bar",    4],
            [    204,    "Autogen UV Strobe",    1],
            [    204,    "Autogen bassline sidechain bottom",    2],
            [    206,    "rainbow good slow top",    16],
            [    206,    "RBBB 1 bar",    4],
            [    222,    "hooked wandering bottom",    16],
            [    222,    "Ghosts riser",    4],
            [    238,    "hooked wandering top",    16],
            [    238,    "RBBB 1 bar",    4],
            [    254,    "rainbow good slow top",    16],
            [    254,    "RBBB 1 bar",    4],
            [    270,    "Autogen UV Strobe",    1],
            [    270,    "Autogen bassline sidechain bottom",    2],
            [    272,    "Rainbow bad",    2],
            [    272,    "Autogen bassline bottom",    2],
            [    274,    "Rainbow bad",    2],
            [    274,    "UV pulse",    1],
            [    276,    "Rainbow bad",    2],
            [    276,    "UV pulse slow",    2],
            [    278,    "Autogen Strobe",    1],
            [    278,    "Autogen bassline bottom",    2],
            [    280,    "UV pulse",    1],
            [    280,    "RBBB 1 bar",    4],
            [    284,    "UV pulse",    1],
            [    284,    "rainbow good slow top",    16],
            [    300,    "Rainbow bad",    2],
            [    300,    "Autogen bassline bottom",    2],
            [    302,    "hooked wandering top",    16],
            [    302,    "hooked wandering bottom",    16],
            [    318,    "Autogen bassline bottom",    2],
            [    318,    "hooked wandering bottom",    16],
            [    334,    "RBBB 1 bar",    4],
            [    334,    "hooked wandering top",    16],
            [    350,    "Autogen bassline bottom",    2],
            [    350,    "UV pulse slow",    2],
            [    352,    "Autogen bassline bottom",    2],
            [    352,    "Autogen bassline top",    2],
            [    354,    "rainbow good slow top",    16],
            [    354,    "rainbow good slow top",    16],
            [    370,    "Ghosts riser",    4],
            [    370,    "RBBB 1 bar",    4],
            [    374,    "UV pulse",    1],
            [    374,    "Ghosts riser",    4],
            [    378,    "UV pulse",    1],
            [    378,    "UV pulse",    1],
            [    379,    "Autogen UV Strobe",    1],
            [    379,    "rainbow good slow top",    16],
            [    395,    "hooked wandering bottom",    16],
            [    395,    "Autogen UV Strobe",    1],
            [    411,    "rainbow good slow top",    16],
            [    411,    "Autogen bassline top",    2]
        ],
        "bpm": 128,
        "delay_lights": 0.024050000000000002,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/deadmau5 feat Rob Swire - Ghosts N Stuff.ogg"
    }
}