effects = {
    "g_deadmau5 & Kaskade - I Remember (HQ)": {
        "beats": [
            [    1,    "Autogen Strobe",    1],
            [    1,    "Autogen UV Strobe",    1],
            [    2,    "hooked wandering bottom",    16],
            [    2,    "Autogen bassline bottom",    2],
            [    18,    "rainbow good slow top",    16],
            [    18,    "RBBB 1 bar",    4],
            [    34,    "Autogen UV Strobe",    1],
            [    34,    "Autogen Strobe",    1],
            [    35,    "Autogen bassline top",    2],
            [    35,    "RBBB 1 bar",    4],
            [    39,    "Autogen Strobe",    1],
            [    39,    "Autogen Strobe",    1],
            [    40,    "hooked wandering top",    16],
            [    40,    "Autogen bassline sidechain bottom",    2],
            [    56,    "Autogen bassline sidechain bottom",    2],
            [    56,    "rainbow good slow top",    16],
            [    72,    "rainbow good slow top",    16],
            [    72,    "Autogen bassline top",    2],
            [    88,    "Ghosts riser",    4],
            [    88,    "Autogen bassline top",    2],
            [    92,    "hooked wandering bottom",    16],
            [    92,    "Ghosts riser",    4],
            [    108,    "Autogen bassline bottom",    2],
            [    108,    "Ghosts riser",    4],
            [    112,    "UV pulse",    1],
            [    112,    "hooked wandering bottom",    16],
            [    128,    "Rainbow bad",    2],
            [    128,    "Autogen bassline top",    2],
            [    130,    "hooked wandering top",    16],
            [    130,    "Autogen bassline top",    2],
            [    146,    "Autogen Strobe",    1],
            [    146,    "UV pulse",    1],
            [    147,    "Autogen Strobe",    1],
            [    147,    "UV pulse slow",    2],
            [    149,    "Autogen UV Strobe",    1],
            [    149,    "hooked wandering top",    16],
            [    165,    "Ghosts riser",    4],
            [    165,    "Autogen bassline top",    2],
            [    169,    "Autogen bassline top",    2],
            [    169,    "Rainbow bad",    2],
            [    171,    "UV pulse",    1],
            [    171,    "UV pulse slow",    2],
            [    173,    "RBBB 1 bar",    4],
            [    173,    "RBBB 1 bar",    4],
            [    177,    "Ghosts riser",    4],
            [    177,    "Ghosts riser",    4],
            [    181,    "Autogen bassline bottom",    2],
            [    181,    "hooked wandering top",    16],
            [    197,    "hooked wandering top",    16],
            [    197,    "Ghosts riser",    4],
            [    213,    "rainbow good slow top",    16],
            [    213,    "hooked wandering top",    16],
            [    229,    "rainbow good slow top",    16],
            [    229,    "Autogen Strobe",    1],
            [    245,    "UV pulse",    1],
            [    245,    "hooked wandering top",    16],
            [    261,    "Autogen UV Strobe",    1],
            [    261,    "Autogen bassline bottom",    2],
            [    263,    "UV pulse slow",    2],
            [    263,    "UV pulse",    1],
            [    265,    "rainbow good slow top",    16],
            [    265,    "UV pulse",    1],
            [    281,    "rainbow good slow top",    16],
            [    281,    "Autogen bassline sidechain bottom",    2],
            [    297,    "Autogen bassline bottom",    2],
            [    297,    "hooked wandering top",    16],
            [    313,    "RBBB 1 bar",    4],
            [    313,    "Autogen Strobe",    1],
            [    317,    "Autogen UV Strobe",    1],
            [    317,    "UV pulse",    1],
            [    318,    "RBBB 1 bar",    4],
            [    318,    "RBBB 1 bar",    4],
            [    322,    "UV pulse slow",    2],
            [    322,    "Rainbow bad",    2],
            [    324,    "Autogen bassline bottom",    2],
            [    324,    "RBBB 1 bar",    4],
            [    328,    "Autogen bassline sidechain bottom",    2],
            [    328,    "Autogen bassline sidechain bottom",    2],
            [    330,    "Rainbow bad",    2],
            [    330,    "rainbow good slow top",    16],
            [    346,    "Autogen bassline sidechain bottom",    2],
            [    346,    "Autogen bassline bottom",    2],
            [    348,    "Autogen Strobe",    1],
            [    348,    "Autogen bassline bottom",    2],
            [    350,    "UV pulse slow",    2],
            [    350,    "Rainbow bad",    2],
            [    352,    "rainbow good slow top",    16],
            [    352,    "UV pulse",    1],
            [    368,    "UV pulse slow",    2],
            [    368,    "UV pulse",    1],
            [    370,    "Ghosts riser",    4],
            [    370,    "UV pulse slow",    2],
            [    374,    "hooked wandering bottom",    16],
            [    374,    "hooked wandering top",    16],
            [    390,    "hooked wandering bottom",    16],
            [    390,    "Rainbow bad",    2],
            [    406,    "hooked wandering bottom",    16],
            [    406,    "Autogen Strobe",    1],
            [    422,    "Ghosts riser",    4],
            [    422,    "Ghosts riser",    4],
            [    426,    "UV pulse slow",    2],
            [    426,    "hooked wandering bottom",    16],
            [    442,    "Autogen bassline bottom",    2],
            [    442,    "RBBB 1 bar",    4],
            [    446,    "UV pulse slow",    2],
            [    446,    "UV pulse",    1],
            [    448,    "Autogen bassline bottom",    2],
            [    448,    "Autogen bassline sidechain bottom",    2],
            [    450,    "Ghosts riser",    4],
            [    450,    "UV pulse",    1],
            [    454,    "Rainbow bad",    2],
            [    454,    "Autogen bassline top",    2],
            [    456,    "Autogen Strobe",    1],
            [    456,    "Rainbow bad",    2],
            [    458,    "Autogen UV Strobe",    1],
            [    458,    "rainbow good slow top",    16],
            [    474,    "hooked wandering top",    16],
            [    474,    "Autogen bassline sidechain bottom",    2],
            [    490,    "Autogen bassline top",    2],
            [    490,    "Autogen UV Strobe",    1],
            [    492,    "Autogen Strobe",    1],
            [    492,    "Autogen bassline top",    2],
            [    494,    "UV pulse",    1],
            [    494,    "RBBB 1 bar",    4],
            [    498,    "Autogen bassline sidechain bottom",    2],
            [    498,    "Autogen UV Strobe",    1],
            [    500,    "Autogen bassline sidechain bottom",    2],
            [    500,    "Autogen bassline top",    2],
            [    502,    "UV pulse",    1],
            [    502,    "Rainbow bad",    2],
            [    504,    "Autogen Strobe",    1],
            [    504,    "hooked wandering bottom",    16],
            [    520,    "UV pulse slow",    2],
            [    520,    "Autogen bassline top",    2],
            [    522,    "Autogen bassline sidechain bottom",    2],
            [    522,    "Autogen Strobe",    1],
            [    524,    "rainbow good slow top",    16],
            [    524,    "rainbow good slow top",    16],
            [    540,    "UV pulse",    1],
            [    540,    "Autogen bassline bottom",    2],
            [    542,    "hooked wandering bottom",    16],
            [    542,    "Rainbow bad",    2],
            [    558,    "UV pulse slow",    2],
            [    558,    "Ghosts riser",    4],
            [    562,    "Ghosts riser",    4],
            [    562,    "Autogen bassline bottom",    2],
            [    566,    "Autogen bassline top",    2],
            [    566,    "Autogen bassline top",    2],
            [    568,    "Autogen bassline top",    2],
            [    568,    "UV pulse",    1],
            [    570,    "RBBB 1 bar",    4],
            [    570,    "Ghosts riser",    4],
            [    574,    "Rainbow bad",    2],
            [    574,    "Autogen bassline bottom",    2],
            [    576,    "RBBB 1 bar",    4],
            [    576,    "Ghosts riser",    4],
            [    580,    "hooked wandering bottom",    16],
            [    580,    "Autogen bassline bottom",    2],
            [    596,    "Rainbow bad",    2],
            [    596,    "hooked wandering top",    16],
            [    612,    "hooked wandering bottom",    16],
            [    612,    "hooked wandering top",    16],
            [    628,    "Autogen bassline top",    2],
            [    628,    "UV pulse",    1],
            [    630,    "Autogen UV Strobe",    1],
            [    630,    "hooked wandering top",    16],
            [    646,    "Autogen bassline top",    2],
            [    646,    "Autogen bassline sidechain bottom",    2],
            [    648,    "UV pulse slow",    2],
            [    648,    "hooked wandering bottom",    16],
            [    664,    "Ghosts riser",    4],
            [    664,    "RBBB 1 bar",    4],
            [    668,    "Ghosts riser",    4],
            [    668,    "hooked wandering bottom",    16],
            [    684,    "Ghosts riser",    4],
            [    684,    "Autogen bassline bottom",    2],
            [    688,    "Ghosts riser",    4],
            [    688,    "rainbow good slow top",    16],
            [    704,    "RBBB 1 bar",    4],
            [    704,    "Autogen bassline top",    2],
            [    708,    "Autogen Strobe",    1],
            [    708,    "Autogen bassline top",    2],
            [    710,    "Autogen UV Strobe",    1],
            [    710,    "Ghosts riser",    4],
            [    714,    "Ghosts riser",    4],
            [    714,    "rainbow good slow top",    16],
            [    730,    "hooked wandering bottom",    16],
            [    730,    "Autogen bassline top",    2],
            [    746,    "UV pulse",    1],
            [    746,    "Ghosts riser",    4],
            [    750,    "Autogen Strobe",    1],
            [    750,    "RBBB 1 bar",    4],
            [    754,    "Autogen bassline sidechain bottom",    2],
            [    754,    "rainbow good slow top",    16],
            [    770,    "Autogen Strobe",    1],
            [    770,    "UV pulse slow",    2],
            [    772,    "rainbow good slow top",    16],
            [    772,    "Ghosts riser",    4],
            [    788,    "hooked wandering bottom",    16],
            [    788,    "Autogen bassline bottom",    2],
            [    804,    "hooked wandering top",    16],
            [    804,    "Autogen Strobe",    1],
            [    820,    "Autogen UV Strobe",    1],
            [    820,    "Autogen UV Strobe",    1],
            [    821,    "Autogen Strobe",    1],
            [    821,    "hooked wandering top",    16],
            [    837,    "Autogen UV Strobe",    1],
            [    837,    "Ghosts riser",    4],
            [    841,    "Autogen bassline bottom",    2],
            [    841,    "UV pulse slow",    2],
            [    843,    "Autogen UV Strobe",    1],
            [    843,    "Autogen UV Strobe",    1],
            [    844,    "UV pulse",    1],
            [    844,    "Autogen UV Strobe",    1],
            [    845,    "Autogen bassline top",    2],
            [    845,    "Autogen bassline top",    2],
            [    847,    "rainbow good slow top",    16],
            [    847,    "Autogen bassline sidechain bottom",    2],
            [    863,    "UV pulse slow",    2],
            [    863,    "RBBB 1 bar",    4],
            [    867,    "Autogen bassline bottom",    2],
            [    867,    "hooked wandering bottom",    16],
            [    883,    "Autogen bassline bottom",    2],
            [    883,    "Autogen UV Strobe",    1],
            [    885,    "Autogen bassline top",    2],
            [    885,    "rainbow good slow top",    16],
            [    901,    "RBBB 1 bar",    4],
            [    901,    "Autogen UV Strobe",    1],
            [    905,    "UV pulse",    1],
            [    905,    "rainbow good slow top",    16],
            [    921,    "UV pulse slow",    2],
            [    921,    "hooked wandering top",    16],
            [    937,    "Autogen UV Strobe",    1],
            [    937,    "Autogen bassline top",    2],
            [    939,    "Rainbow bad",    2],
            [    939,    "Autogen Strobe",    1],
            [    941,    "Autogen UV Strobe",    1],
            [    941,    "Autogen bassline sidechain bottom",    2],
            [    943,    "hooked wandering top",    16],
            [    943,    "Rainbow bad",    2],
            [    959,    "Autogen bassline bottom",    2],
            [    959,    "Ghosts riser",    4],
            [    963,    "UV pulse",    1],
            [    963,    "hooked wandering bottom",    16],
            [    979,    "UV pulse",    1],
            [    979,    "rainbow good slow top",    16],
            [    995,    "Autogen bassline top",    2],
            [    995,    "UV pulse",    1],
            [    997,    "Autogen bassline top",    2],
            [    997,    "RBBB 1 bar",    4],
            [    1001,    "RBBB 1 bar",    4],
            [    1001,    "Autogen bassline top",    2],
            [    1005,    "UV pulse",    1],
            [    1005,    "Autogen UV Strobe",    1],
            [    1006,    "Autogen bassline top",    2],
            [    1006,    "hooked wandering top",    16],
            [    1022,    "Autogen bassline top",    2],
            [    1022,    "rainbow good slow top",    16],
            [    1038,    "UV pulse slow",    2],
            [    1038,    "Ghosts riser",    4],
            [    1042,    "hooked wandering bottom",    16],
            [    1042,    "RBBB 1 bar",    4],
            [    1058,    "hooked wandering bottom",    16],
            [    1058,    "rainbow good slow top",    16],
            [    1074,    "UV pulse slow",    2],
            [    1074,    "Ghosts riser",    4],
            [    1078,    "rainbow good slow top",    16],
            [    1078,    "hooked wandering top",    16],
            [    1094,    "Autogen UV Strobe",    1],
            [    1094,    "hooked wandering top",    16],
            [    1110,    "Autogen Strobe",    1],
            [    1110,    "hooked wandering bottom",    16],
            [    1126,    "Autogen bassline top",    2],
            [    1126,    "Autogen bassline sidechain bottom",    2],
            [    1128,    "UV pulse slow",    2],
            [    1128,    "hooked wandering bottom",    16],
            [    1144,    "UV pulse slow",    2],
            [    1144,    "RBBB 1 bar",    4],
            [    1148,    "hooked wandering bottom",    16],
            [    1148,    "UV pulse",    1],
            [    1164,    "Autogen UV Strobe",    1],
            [    1164,    "RBBB 1 bar",    4],
            [    1168,    "RBBB 1 bar",    4],
            [    1168,    "RBBB 1 bar",    4],
            [    1172,    "Autogen Strobe",    1],
            [    1172,    "rainbow good slow top",    16],
            [    1188,    "Ghosts riser",    4],
            [    1188,    "Autogen UV Strobe",    1],
            [    1192,    "UV pulse slow",    2],
            [    1192,    "Autogen bassline bottom",    2],
            [    1194,    "hooked wandering bottom",    16],
            [    1194,    "hooked wandering top",    16],
            [    1210,    "Autogen bassline top",    2],
            [    1210,    "Rainbow bad",    2],
            [    1212,    "Autogen Strobe",    1],
            [    1212,    "hooked wandering bottom",    16],
            [    1228,    "Ghosts riser",    4],
            [    1228,    "Rainbow bad",    2],
            [    1232,    "hooked wandering bottom",    16],
            [    1232,    "UV pulse slow",    2],
            [    1248,    "hooked wandering top",    16],
            [    1248,    "UV pulse slow",    2],
            [    1264,    "hooked wandering top",    16],
            [    1264,    "hooked wandering top",    16]
        ],
        "bpm": 128,
        "delay_lights": 0.12,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/deadmau5 & Kaskade - I Remember (HQ).ogg"
    }
}