effects = {
    "g_deadmau5 feat Rob Swire - Ghosts N Stuff": {
        "beats": [
            [    1,    "Autogen Strobe",    1],
            [    1,    "Autogen UV Strobe",    1],
            [    2,    "hooked wandering bottom",    16],
            [    2,    "Autogen bassline sidechain bottom",    2],
            [    18,    "RBBB 1 bar",    4],
            [    18,    "UV pulse",    1],
            [    22,    "UV pulse slow",    2],
            [    22,    "Autogen Strobe",    1],
            [    24,    "rainbow good slow top",    16],
            [    24,    "Autogen Strobe",    1],
            [    40,    "RBBB 1 bar",    4],
            [    40,    "Autogen bassline bottom",    2],
            [    44,    "Ghosts riser",    4],
            [    44,    "Autogen UV Strobe",    1],
            [    48,    "Autogen Strobe",    1],
            [    48,    "RBBB 1 bar",    4],
            [    52,    "Autogen UV Strobe",    1],
            [    52,    "Autogen UV Strobe",    1],
            [    53,    "Autogen bassline bottom",    2],
            [    53,    "UV pulse slow",    2],
            [    55,    "rainbow good slow top",    16],
            [    55,    "UV pulse slow",    2],
            [    71,    "Autogen Strobe",    1],
            [    71,    "Autogen bassline bottom",    2],
            [    73,    "RBBB 1 bar",    4],
            [    73,    "hooked wandering bottom",    16],
            [    89,    "hooked wandering bottom",    16],
            [    89,    "hooked wandering top",    16],
            [    105,    "Ghosts riser",    4],
            [    105,    "rainbow good slow top",    16],
            [    121,    "rainbow good slow top",    16],
            [    121,    "Autogen Strobe",    1],
            [    137,    "Autogen bassline sidechain bottom",    2],
            [    137,    "Autogen Strobe",    1],
            [    139,    "Ghosts riser",    4],
            [    139,    "Autogen bassline bottom",    2],
            [    143,    "Autogen bassline top",    2],
            [    143,    "Rainbow bad",    2],
            [    145,    "UV pulse slow",    2],
            [    145,    "Ghosts riser",    4],
            [    149,    "Autogen bassline bottom",    2],
            [    149,    "Autogen bassline bottom",    2],
            [    151,    "Ghosts riser",    4],
            [    151,    "rainbow good slow top",    16],
            [    167,    "Ghosts riser",    4],
            [    167,    "hooked wandering bottom",    16],
            [    183,    "Rainbow bad",    2],
            [    183,    "Autogen bassline bottom",    2],
            [    185,    "hooked wandering top",    16],
            [    185,    "Autogen UV Strobe",    1],
            [    201,    "UV pulse slow",    2],
            [    201,    "Autogen bassline bottom",    2],
            [    203,    "hooked wandering top",    16],
            [    203,    "hooked wandering top",    16],
            [    219,    "rainbow good slow top",    16],
            [    219,    "hooked wandering bottom",    16],
            [    235,    "hooked wandering top",    16],
            [    235,    "Autogen bassline sidechain bottom",    2],
            [    251,    "UV pulse slow",    2],
            [    251,    "rainbow good slow top",    16],
            [    267,    "Ghosts riser",    4],
            [    267,    "UV pulse",    1],
            [    271,    "Rainbow bad",    2],
            [    271,    "Autogen bassline top",    2],
            [    273,    "UV pulse slow",    2],
            [    273,    "Autogen bassline top",    2],
            [    275,    "Rainbow bad",    2],
            [    275,    "Rainbow bad",    2],
            [    277,    "hooked wandering top",    16],
            [    277,    "UV pulse",    1],
            [    293,    "UV pulse",    1],
            [    293,    "Rainbow bad",    2],
            [    295,    "Autogen UV Strobe",    1],
            [    295,    "Autogen bassline sidechain bottom",    2],
            [    297,    "Ghosts riser",    4],
            [    297,    "Autogen Strobe",    1],
            [    301,    "UV pulse",    1],
            [    301,    "UV pulse slow",    2],
            [    303,    "Autogen Strobe",    1],
            [    303,    "rainbow good slow top",    16],
            [    319,    "Autogen bassline top",    2],
            [    319,    "hooked wandering bottom",    16],
            [    335,    "Autogen Strobe",    1],
            [    335,    "Ghosts riser",    4],
            [    339,    "Autogen Strobe",    1],
            [    339,    "Autogen Strobe",    1],
            [    340,    "Autogen bassline bottom",    2],
            [    340,    "rainbow good slow top",    16],
            [    356,    "Ghosts riser",    4],
            [    356,    "Autogen bassline bottom",    2],
            [    360,    "RBBB 1 bar",    4],
            [    360,    "rainbow good slow top",    16],
            [    376,    "UV pulse",    1],
            [    376,    "Autogen Strobe",    1],
            [    377,    "Autogen Strobe",    1],
            [    377,    "UV pulse slow",    2],
            [    379,    "UV pulse",    1],
            [    379,    "Autogen Strobe",    1],
            [    380,    "Ghosts riser",    4],
            [    380,    "UV pulse",    1],
            [    384,    "Autogen UV Strobe",    1],
            [    384,    "hooked wandering bottom",    16],
            [    400,    "Ghosts riser",    4],
            [    400,    "UV pulse slow",    2],
            [    404,    "Ghosts riser",    4],
            [    404,    "hooked wandering top",    16]
        ],
        "bpm": 128,
        "delay_lights": 0.024050000000000002,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/deadmau5 feat Rob Swire - Ghosts N Stuff.ogg"
    }
}