effects = {
    "g_Everything Goes On": {
        "beats": [
            [    1,    "hooked wandering top",    16],
            [    1,    "UV pulse slow",    2],
            [    17,    "rainbow good slow top",    16],
            [    17,    "RBBB 1 bar",    4],
            [    33,    "hooked wandering bottom",    16],
            [    33,    "UV pulse",    1],
            [    49,    "RBBB 1 bar",    4],
            [    49,    "Autogen bassline top",    2],
            [    53,    "rainbow good slow top",    16],
            [    53,    "UV pulse slow",    2],
            [    69,    "Autogen Strobe",    1],
            [    69,    "hooked wandering top",    16],
            [    85,    "UV pulse",    1],
            [    85,    "Autogen bassline sidechain bottom",    2],
            [    87,    "Autogen bassline sidechain bottom",    2],
            [    87,    "hooked wandering bottom",    16],
            [    103,    "Autogen Strobe",    1],
            [    103,    "UV pulse slow",    2],
            [    105,    "Rainbow bad",    2],
            [    105,    "rainbow good slow top",    16],
            [    121,    "Autogen bassline top",    2],
            [    121,    "RBBB 1 bar",    4],
            [    125,    "hooked wandering top",    16],
            [    125,    "UV pulse",    1],
            [    141,    "rainbow good slow top",    16],
            [    141,    "Autogen bassline bottom",    2],
            [    157,    "Autogen bassline top",    2],
            [    157,    "Autogen bassline top",    2],
            [    159,    "Rainbow bad",    2],
            [    159,    "Rainbow bad",    2],
            [    161,    "Rainbow bad",    2],
            [    161,    "Autogen bassline top",    2],
            [    163,    "Ghosts riser",    4],
            [    163,    "rainbow good slow top",    16],
            [    179,    "Ghosts riser",    4],
            [    179,    "UV pulse",    1],
            [    183,    "Autogen UV Strobe",    1],
            [    183,    "Autogen Strobe",    1],
            [    184,    "Autogen Strobe",    1],
            [    184,    "RBBB 1 bar",    4],
            [    188,    "rainbow good slow top",    16],
            [    188,    "UV pulse",    1],
            [    204,    "Autogen bassline bottom",    2],
            [    204,    "rainbow good slow top",    16],
            [    220,    "hooked wandering bottom",    16],
            [    220,    "Autogen bassline bottom",    2],
            [    236,    "RBBB 1 bar",    4],
            [    236,    "Autogen bassline top",    2],
            [    240,    "Autogen bassline bottom",    2],
            [    240,    "rainbow good slow top",    16],
            [    256,    "Autogen bassline bottom",    2],
            [    256,    "UV pulse slow",    2],
            [    258,    "Rainbow bad",    2],
            [    258,    "Autogen bassline bottom",    2],
            [    260,    "Autogen UV Strobe",    1],
            [    260,    "Autogen bassline top",    2],
            [    262,    "hooked wandering bottom",    16],
            [    262,    "rainbow good slow top",    16],
            [    278,    "Autogen UV Strobe",    1],
            [    278,    "hooked wandering top",    16],
            [    294,    "Autogen UV Strobe",    1],
            [    294,    "Autogen bassline top",    2],
            [    296,    "hooked wandering bottom",    16],
            [    296,    "Autogen Strobe",    1],
            [    312,    "UV pulse slow",    2],
            [    312,    "UV pulse slow",    2],
            [    314,    "RBBB 1 bar",    4],
            [    314,    "Autogen bassline sidechain bottom",    2],
            [    318,    "UV pulse",    1],
            [    318,    "Autogen bassline sidechain bottom",    2],
            [    320,    "Autogen UV Strobe",    1],
            [    320,    "Autogen bassline top",    2],
            [    322,    "Autogen bassline top",    2],
            [    322,    "Autogen bassline bottom",    2],
            [    324,    "RBBB 1 bar",    4],
            [    324,    "Autogen UV Strobe",    1],
            [    328,    "Autogen bassline sidechain bottom",    2],
            [    328,    "rainbow good slow top",    16],
            [    344,    "Autogen UV Strobe",    1],
            [    344,    "RBBB 1 bar",    4],
            [    348,    "Rainbow bad",    2],
            [    348,    "Autogen bassline sidechain bottom",    2],
            [    350,    "Ghosts riser",    4],
            [    350,    "hooked wandering bottom",    16],
            [    366,    "UV pulse slow",    2],
            [    366,    "Autogen UV Strobe",    1],
            [    368,    "hooked wandering top",    16],
            [    368,    "UV pulse",    1],
            [    384,    "hooked wandering top",    16],
            [    384,    "hooked wandering bottom",    16],
            [    400,    "Autogen UV Strobe",    1],
            [    400,    "RBBB 1 bar",    4],
            [    404,    "Autogen bassline sidechain bottom",    2],
            [    404,    "UV pulse",    1],
            [    406,    "UV pulse",    1],
            [    406,    "Autogen bassline bottom",    2],
            [    408,    "Rainbow bad",    2],
            [    408,    "Autogen UV Strobe",    1],
            [    410,    "Autogen Strobe",    1],
            [    410,    "Autogen UV Strobe",    1],
            [    411,    "Autogen bassline sidechain bottom",    2],
            [    411,    "Ghosts riser",    4],
            [    415,    "rainbow good slow top",    16],
            [    415,    "hooked wandering bottom",    16],
            [    431,    "Autogen Strobe",    1],
            [    431,    "hooked wandering bottom",    16],
            [    447,    "Autogen bassline top",    2],
            [    447,    "UV pulse",    1],
            [    449,    "hooked wandering top",    16],
            [    449,    "rainbow good slow top",    16],
            [    465,    "Ghosts riser",    4],
            [    465,    "hooked wandering top",    16],
            [    481,    "UV pulse slow",    2],
            [    481,    "Rainbow bad",    2],
            [    483,    "rainbow good slow top",    16],
            [    483,    "Autogen bassline sidechain bottom",    2],
            [    499,    "Autogen bassline sidechain bottom",    2],
            [    499,    "hooked wandering bottom",    16],
            [    515,    "rainbow good slow top",    16],
            [    515,    "Autogen Strobe",    1]
        ],
        "bpm": 157,
        "delay_lights": 0.20566560509554144,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/Everything Goes On.ogg"
    }
}