effects = {
    "g_Everything Goes On": {
        "beats": [
            [    1,    "RBBB 1 bar",    4],
            [    1,    "UV pulse",    1],
            [    5,    "Rainbow bad",    2],
            [    5,    "hooked wandering bottom",    16],
            [    21,    "Autogen bassline top",    2],
            [    21,    "Rainbow bad",    2],
            [    23,    "hooked wandering top",    16],
            [    23,    "hooked wandering bottom",    16],
            [    39,    "Autogen bassline sidechain bottom",    2],
            [    39,    "Autogen bassline top",    2],
            [    41,    "Autogen bassline sidechain bottom",    2],
            [    41,    "Autogen bassline top",    2],
            [    43,    "Ghosts riser",    4],
            [    43,    "UV pulse slow",    2],
            [    47,    "Autogen bassline sidechain bottom",    2],
            [    47,    "Autogen bassline sidechain bottom",    2],
            [    49,    "Autogen bassline bottom",    2],
            [    49,    "UV pulse",    1],
            [    51,    "Autogen Strobe",    1],
            [    51,    "Ghosts riser",    4],
            [    55,    "RBBB 1 bar",    4],
            [    55,    "hooked wandering bottom",    16],
            [    71,    "UV pulse slow",    2],
            [    71,    "Autogen Strobe",    1],
            [    73,    "hooked wandering top",    16],
            [    73,    "Autogen Strobe",    1],
            [    89,    "Autogen UV Strobe",    1],
            [    89,    "rainbow good slow top",    16],
            [    105,    "Autogen bassline top",    2],
            [    105,    "UV pulse slow",    2],
            [    107,    "UV pulse slow",    2],
            [    107,    "UV pulse",    1],
            [    109,    "Autogen bassline bottom",    2],
            [    109,    "UV pulse slow",    2],
            [    111,    "hooked wandering top",    16],
            [    111,    "Autogen bassline sidechain bottom",    2],
            [    127,    "UV pulse slow",    2],
            [    127,    "hooked wandering top",    16],
            [    143,    "hooked wandering bottom",    16],
            [    143,    "Ghosts riser",    4],
            [    159,    "UV pulse slow",    2],
            [    159,    "rainbow good slow top",    16],
            [    175,    "Autogen UV Strobe",    1],
            [    175,    "UV pulse slow",    2],
            [    177,    "hooked wandering bottom",    16],
            [    177,    "hooked wandering bottom",    16],
            [    193,    "Autogen bassline bottom",    2],
            [    193,    "Autogen bassline bottom",    2],
            [    195,    "Autogen UV Strobe",    1],
            [    195,    "RBBB 1 bar",    4],
            [    199,    "Autogen bassline top",    2],
            [    199,    "Autogen UV Strobe",    1],
            [    201,    "Ghosts riser",    4],
            [    201,    "UV pulse",    1],
            [    205,    "rainbow good slow top",    16],
            [    205,    "UV pulse",    1],
            [    221,    "Ghosts riser",    4],
            [    221,    "Autogen bassline sidechain bottom",    2],
            [    225,    "RBBB 1 bar",    4],
            [    225,    "hooked wandering bottom",    16],
            [    241,    "Autogen bassline sidechain bottom",    2],
            [    241,    "rainbow good slow top",    16],
            [    257,    "rainbow good slow top",    16],
            [    257,    "Ghosts riser",    4],
            [    273,    "Autogen UV Strobe",    1],
            [    273,    "Ghosts riser",    4],
            [    277,    "UV pulse slow",    2],
            [    277,    "Autogen bassline top",    2],
            [    279,    "UV pulse",    1],
            [    279,    "Ghosts riser",    4],
            [    283,    "Ghosts riser",    4],
            [    283,    "Autogen bassline top",    2],
            [    287,    "Autogen bassline top",    2],
            [    287,    "Rainbow bad",    2],
            [    289,    "Autogen Strobe",    1],
            [    289,    "hooked wandering top",    16],
            [    305,    "Autogen bassline bottom",    2],
            [    305,    "Rainbow bad",    2],
            [    307,    "Autogen bassline top",    2],
            [    307,    "Autogen UV Strobe",    1],
            [    309,    "Rainbow bad",    2],
            [    309,    "UV pulse slow",    2],
            [    311,    "Autogen bassline bottom",    2],
            [    311,    "UV pulse",    1],
            [    313,    "Ghosts riser",    4],
            [    313,    "Autogen bassline sidechain bottom",    2],
            [    317,    "UV pulse",    1],
            [    317,    "Autogen bassline sidechain bottom",    2],
            [    319,    "Rainbow bad",    2],
            [    319,    "Autogen UV Strobe",    1],
            [    321,    "Rainbow bad",    2],
            [    321,    "Autogen bassline sidechain bottom",    2],
            [    323,    "rainbow good slow top",    16],
            [    323,    "Rainbow bad",    2],
            [    339,    "RBBB 1 bar",    4],
            [    339,    "Autogen bassline sidechain bottom",    2],
            [    343,    "Autogen UV Strobe",    1],
            [    343,    "UV pulse",    1],
            [    344,    "Ghosts riser",    4],
            [    344,    "Autogen bassline top",    2],
            [    348,    "Rainbow bad",    2],
            [    348,    "Autogen Strobe",    1],
            [    350,    "Autogen bassline top",    2],
            [    350,    "Ghosts riser",    4],
            [    354,    "Autogen bassline top",    2],
            [    354,    "Rainbow bad",    2],
            [    356,    "Ghosts riser",    4],
            [    356,    "UV pulse slow",    2],
            [    360,    "Autogen UV Strobe",    1],
            [    360,    "hooked wandering bottom",    16],
            [    376,    "UV pulse slow",    2],
            [    376,    "Ghosts riser",    4],
            [    380,    "Rainbow bad",    2],
            [    380,    "Autogen bassline sidechain bottom",    2],
            [    382,    "Autogen UV Strobe",    1],
            [    382,    "Rainbow bad",    2],
            [    384,    "Autogen Strobe",    1],
            [    384,    "rainbow good slow top",    16],
            [    400,    "Autogen bassline top",    2],
            [    400,    "Autogen bassline top",    2],
            [    402,    "Autogen UV Strobe",    1],
            [    402,    "Autogen bassline top",    2],
            [    404,    "UV pulse slow",    2],
            [    404,    "Autogen bassline sidechain bottom",    2],
            [    406,    "Autogen bassline bottom",    2],
            [    406,    "Autogen UV Strobe",    1],
            [    408,    "rainbow good slow top",    16],
            [    408,    "Autogen UV Strobe",    1],
            [    424,    "Ghosts riser",    4],
            [    424,    "rainbow good slow top",    16],
            [    440,    "rainbow good slow top",    16],
            [    440,    "rainbow good slow top",    16],
            [    456,    "UV pulse slow",    2],
            [    456,    "hooked wandering bottom",    16],
            [    472,    "Ghosts riser",    4],
            [    472,    "RBBB 1 bar",    4],
            [    476,    "Rainbow bad",    2],
            [    476,    "UV pulse",    1],
            [    478,    "Autogen bassline top",    2],
            [    478,    "hooked wandering top",    16],
            [    494,    "hooked wandering top",    16],
            [    494,    "Ghosts riser",    4],
            [    510,    "hooked wandering bottom",    16],
            [    510,    "Autogen UV Strobe",    1],
            [    526,    "hooked wandering top",    16],
            [    526,    "hooked wandering bottom",    16]
        ],
        "bpm": 157,
        "delay_lights": 0.20566560509554144,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/Everything Goes On.ogg"
    }
}