effects = {
    "g_KSLV - Pimp Slap": {
        "beats": [
            [    1,    "Rainbow bad",    2],
            [    1,    "UV pulse slow",    2],
            [    3,    "Autogen UV Strobe",    1],
            [    3,    "Autogen bassline sidechain bottom",    2],
            [    5,    "hooked wandering bottom",    16],
            [    5,    "rainbow good slow top",    16],
            [    21,    "RBBB 1 bar",    4],
            [    21,    "Autogen bassline top",    2],
            [    25,    "Autogen bassline bottom",    2],
            [    25,    "Autogen UV Strobe",    1],
            [    27,    "Autogen bassline sidechain bottom",    2],
            [    27,    "Autogen Strobe",    1],
            [    29,    "Rainbow bad",    2],
            [    29,    "hooked wandering bottom",    16],
            [    45,    "UV pulse slow",    2],
            [    45,    "rainbow good slow top",    16],
            [    61,    "Autogen bassline top",    2],
            [    61,    "Ghosts riser",    4],
            [    65,    "Autogen bassline bottom",    2],
            [    65,    "Autogen UV Strobe",    1],
            [    67,    "hooked wandering bottom",    16],
            [    67,    "rainbow good slow top",    16],
            [    83,    "Rainbow bad",    2],
            [    83,    "Rainbow bad",    2],
            [    85,    "hooked wandering top",    16],
            [    85,    "Autogen Strobe",    1],
            [    101,    "rainbow good slow top",    16],
            [    101,    "Rainbow bad",    2],
            [    117,    "hooked wandering bottom",    16],
            [    117,    "UV pulse",    1],
            [    133,    "Autogen Strobe",    1],
            [    133,    "hooked wandering bottom",    16],
            [    149,    "hooked wandering bottom",    16],
            [    149,    "Rainbow bad",    2],
            [    165,    "Autogen bassline top",    2],
            [    165,    "RBBB 1 bar",    4],
            [    169,    "UV pulse",    1],
            [    169,    "Rainbow bad",    2],
            [    171,    "Autogen Strobe",    1],
            [    171,    "Autogen bassline bottom",    2],
            [    173,    "Autogen bassline bottom",    2],
            [    173,    "hooked wandering top",    16],
            [    189,    "Ghosts riser",    4],
            [    189,    "Autogen Strobe",    1],
            [    193,    "UV pulse slow",    2],
            [    193,    "UV pulse slow",    2],
            [    195,    "hooked wandering top",    16],
            [    195,    "Autogen bassline sidechain bottom",    2],
            [    211,    "RBBB 1 bar",    4],
            [    211,    "Autogen UV Strobe",    1],
            [    215,    "UV pulse",    1],
            [    215,    "rainbow good slow top",    16],
            [    231,    "RBBB 1 bar",    4],
            [    231,    "UV pulse",    1],
            [    235,    "Rainbow bad",    2],
            [    235,    "hooked wandering top",    16],
            [    251,    "hooked wandering bottom",    16],
            [    251,    "RBBB 1 bar",    4]
        ],
        "bpm": 110,
        "delay_lights": 0.32145454545454544,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/KSLV - Pimp Slap.ogg"
    }
}