effects = {
    "g_KSLV - Pimp Slap": {
        "beats": [
            [    1,    "hooked wandering bottom",    16],
            [    1,    "Rainbow bad",    2],
            [    17,    "Ghosts riser",    4],
            [    17,    "rainbow good slow top",    16],
            [    33,    "hooked wandering bottom",    16],
            [    33,    "Rainbow bad",    2],
            [    49,    "Autogen bassline top",    2],
            [    49,    "rainbow good slow top",    16],
            [    65,    "Autogen bassline top",    2],
            [    65,    "hooked wandering bottom",    16],
            [    81,    "Autogen bassline bottom",    2],
            [    81,    "hooked wandering top",    16],
            [    97,    "Autogen UV Strobe",    1],
            [    97,    "UV pulse",    1],
            [    98,    "RBBB 1 bar",    4],
            [    98,    "Autogen bassline sidechain bottom",    2],
            [    102,    "hooked wandering top",    16],
            [    102,    "Autogen UV Strobe",    1],
            [    118,    "Autogen bassline bottom",    2],
            [    118,    "Autogen Strobe",    1],
            [    120,    "UV pulse",    1],
            [    120,    "Rainbow bad",    2],
            [    122,    "RBBB 1 bar",    4],
            [    122,    "Autogen Strobe",    1],
            [    126,    "rainbow good slow top",    16],
            [    126,    "Autogen Strobe",    1],
            [    142,    "Autogen bassline sidechain bottom",    2],
            [    142,    "Autogen bassline top",    2],
            [    144,    "Ghosts riser",    4],
            [    144,    "UV pulse",    1],
            [    148,    "hooked wandering bottom",    16],
            [    148,    "Autogen bassline bottom",    2],
            [    164,    "RBBB 1 bar",    4],
            [    164,    "UV pulse",    1],
            [    168,    "UV pulse slow",    2],
            [    168,    "Autogen bassline bottom",    2],
            [    170,    "Autogen bassline top",    2],
            [    170,    "hooked wandering top",    16],
            [    186,    "rainbow good slow top",    16],
            [    186,    "RBBB 1 bar",    4],
            [    202,    "rainbow good slow top",    16],
            [    202,    "UV pulse",    1],
            [    218,    "Autogen Strobe",    1],
            [    218,    "Autogen bassline top",    2],
            [    220,    "Autogen Strobe",    1],
            [    220,    "Rainbow bad",    2],
            [    222,    "hooked wandering top",    16],
            [    222,    "Ghosts riser",    4],
            [    238,    "Autogen Strobe",    1],
            [    238,    "hooked wandering bottom",    16],
            [    254,    "Ghosts riser",    4],
            [    254,    "Autogen UV Strobe",    1]
        ],
        "bpm": 110,
        "delay_lights": 0.32145454545454544,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/KSLV - Pimp Slap.ogg"
    }
}