effects = {
    "g_luigi": {
        "beats": [
            [    1,    "g_solid bottom cycle",    16],
            [    17,    "g_UV pulse",    2],
            [    19,    "g_UV pulse",    1],
            [    20,    "g_UV pulse",    2],
            [    22,    "g_cyan top pulse",    16],
            [    22,    "g_UV",    16],
            [    38,    "g_UV pulse",    1],
            [    39,    "g_purple green bottom pulse",    16],
            [    55,    "g_solid top cycle",    16],
            [    55,    "g_purple green bottom pulse",    16],
            [    55,    "g_UV",    16],
            [    71,    "RGB Flash",    1],
            [    72,    "g_solid top cycle",    16],
            [    72,    "g_green sidechain bottom pulse",    16],
            [    72,    "g_UV",    16],
            [    88,    "g_solid mixed cycle",    16],
            [    88,    "g_UV",    16],
            [    104,    "g_cyan top pulse",    16],
            [    104,    "g_solid bottom cycle",    16],
            [    104,    "g_UV",    16],
            [    120,    "g_cyan top pulse",    16]
        ],
        "bpm": 90,
        "delay_lights": 0.42766666666666664,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/luigi.ogg",
        "was_autogenerated": True
    }
}