effects = {
    "g_Mad Zach - The Visitor": {
        "beats": [
            [    1,    "hooked wandering top",    16],
            [    1,    "rainbow good slow top",    16],
            [    17,    "hooked wandering top",    16],
            [    17,    "hooked wandering top",    16],
            [    33,    "hooked wandering bottom",    16],
            [    33,    "Ghosts riser",    4],
            [    49,    "hooked wandering bottom",    16],
            [    49,    "Autogen bassline sidechain bottom",    2],
            [    65,    "Rainbow bad",    2],
            [    65,    "Autogen UV Strobe",    1],
            [    67,    "Autogen bassline top",    2],
            [    67,    "RBBB 1 bar",    4],
            [    71,    "hooked wandering bottom",    16],
            [    71,    "UV pulse",    1],
            [    87,    "hooked wandering top",    16],
            [    87,    "RBBB 1 bar",    4],
            [    103,    "Autogen bassline top",    2],
            [    103,    "Autogen bassline top",    2],
            [    105,    "Autogen bassline sidechain bottom",    2],
            [    105,    "Autogen bassline bottom",    2],
            [    107,    "UV pulse",    1],
            [    107,    "hooked wandering top",    16],
            [    123,    "Autogen Strobe",    1],
            [    123,    "rainbow good slow top",    16],
            [    139,    "hooked wandering top",    16],
            [    139,    "Autogen Strobe",    1],
            [    155,    "hooked wandering top",    16],
            [    155,    "hooked wandering bottom",    16],
            [    171,    "UV pulse",    1],
            [    171,    "Autogen bassline sidechain bottom",    2],
            [    173,    "Autogen UV Strobe",    1],
            [    173,    "UV pulse",    1],
            [    174,    "UV pulse slow",    2],
            [    174,    "UV pulse",    1],
            [    176,    "UV pulse",    1],
            [    176,    "Autogen bassline bottom",    2],
            [    178,    "Ghosts riser",    4],
            [    178,    "rainbow good slow top",    16],
            [    194,    "UV pulse slow",    2],
            [    194,    "Autogen Strobe",    1],
            [    196,    "Autogen Strobe",    1],
            [    196,    "Autogen bassline top",    2],
            [    198,    "Autogen bassline sidechain bottom",    2],
            [    198,    "hooked wandering top",    16],
            [    214,    "Autogen UV Strobe",    1],
            [    214,    "RBBB 1 bar",    4],
            [    218,    "Autogen UV Strobe",    1],
            [    218,    "UV pulse slow",    2],
            [    220,    "Rainbow bad",    2],
            [    220,    "Autogen bassline top",    2],
            [    222,    "UV pulse slow",    2],
            [    222,    "Ghosts riser",    4],
            [    226,    "Autogen UV Strobe",    1],
            [    226,    "Autogen UV Strobe",    1],
            [    227,    "Ghosts riser",    4],
            [    227,    "UV pulse slow",    2],
            [    231,    "UV pulse",    1],
            [    231,    "Autogen UV Strobe",    1],
            [    232,    "Autogen bassline sidechain bottom",    2],
            [    232,    "RBBB 1 bar",    4],
            [    236,    "Rainbow bad",    2],
            [    236,    "UV pulse slow",    2],
            [    238,    "UV pulse slow",    2],
            [    238,    "Rainbow bad",    2],
            [    240,    "hooked wandering top",    16],
            [    240,    "Autogen bassline sidechain bottom",    2],
            [    256,    "Rainbow bad",    2],
            [    256,    "hooked wandering bottom",    16],
            [    272,    "UV pulse",    1],
            [    272,    "rainbow good slow top",    16],
            [    288,    "Autogen Strobe",    1],
            [    288,    "Autogen Strobe",    1],
            [    289,    "hooked wandering bottom",    16],
            [    289,    "hooked wandering bottom",    16],
            [    305,    "rainbow good slow top",    16],
            [    305,    "Ghosts riser",    4],
            [    321,    "hooked wandering top",    16],
            [    321,    "UV pulse",    1],
            [    337,    "UV pulse",    1],
            [    337,    "Rainbow bad",    2],
            [    339,    "Autogen bassline sidechain bottom",    2],
            [    339,    "Autogen Strobe",    1],
            [    341,    "hooked wandering top",    16],
            [    341,    "Autogen Strobe",    1],
            [    357,    "UV pulse slow",    2],
            [    357,    "Autogen bassline top",    2],
            [    359,    "hooked wandering top",    16],
            [    359,    "hooked wandering top",    16],
            [    375,    "Autogen bassline bottom",    2],
            [    375,    "hooked wandering bottom",    16],
            [    391,    "hooked wandering top",    16],
            [    391,    "hooked wandering top",    16],
            [    407,    "UV pulse slow",    2],
            [    407,    "UV pulse slow",    2],
            [    409,    "RBBB 1 bar",    4],
            [    409,    "Autogen bassline bottom",    2],
            [    413,    "Autogen UV Strobe",    1],
            [    413,    "hooked wandering bottom",    16],
            [    429,    "Rainbow bad",    2],
            [    429,    "Ghosts riser",    4],
            [    433,    "hooked wandering bottom",    16],
            [    433,    "Autogen Strobe",    1],
            [    449,    "Autogen Strobe",    1],
            [    449,    "Autogen Strobe",    1],
            [    450,    "Ghosts riser",    4],
            [    450,    "Autogen bassline top",    2],
            [    454,    "Autogen UV Strobe",    1],
            [    454,    "hooked wandering top",    16],
            [    470,    "Autogen bassline top",    2],
            [    470,    "Ghosts riser",    4],
            [    474,    "Autogen Strobe",    1],
            [    474,    "Ghosts riser",    4],
            [    478,    "rainbow good slow top",    16],
            [    478,    "hooked wandering bottom",    16],
            [    494,    "Autogen Strobe",    1],
            [    494,    "rainbow good slow top",    16],
            [    510,    "RBBB 1 bar",    4],
            [    510,    "rainbow good slow top",    16],
            [    526,    "Autogen bassline bottom",    2],
            [    526,    "Autogen bassline sidechain bottom",    2],
            [    528,    "Autogen bassline bottom",    2],
            [    528,    "RBBB 1 bar",    4],
            [    532,    "Ghosts riser",    4],
            [    532,    "UV pulse",    1],
            [    536,    "RBBB 1 bar",    4],
            [    536,    "Autogen bassline bottom",    2],
            [    540,    "UV pulse",    1],
            [    540,    "RBBB 1 bar",    4],
            [    544,    "Autogen UV Strobe",    1],
            [    544,    "RBBB 1 bar",    4],
            [    548,    "RBBB 1 bar",    4],
            [    548,    "Autogen UV Strobe",    1],
            [    552,    "Autogen bassline bottom",    2],
            [    552,    "Autogen Strobe",    1],
            [    554,    "RBBB 1 bar",    4],
            [    554,    "Autogen bassline sidechain bottom",    2],
            [    558,    "Autogen bassline top",    2],
            [    558,    "UV pulse slow",    2],
            [    560,    "Autogen bassline bottom",    2],
            [    560,    "hooked wandering bottom",    16],
            [    576,    "Autogen bassline bottom",    2],
            [    576,    "hooked wandering bottom",    16],
            [    592,    "rainbow good slow top",    16],
            [    592,    "Autogen bassline bottom",    2],
            [    608,    "hooked wandering bottom",    16],
            [    608,    "Autogen bassline bottom",    2],
            [    624,    "Autogen bassline top",    2],
            [    624,    "hooked wandering top",    16],
            [    640,    "Autogen bassline top",    2],
            [    640,    "UV pulse",    1],
            [    642,    "rainbow good slow top",    16],
            [    642,    "UV pulse slow",    2],
            [    658,    "Autogen UV Strobe",    1],
            [    658,    "RBBB 1 bar",    4],
            [    662,    "UV pulse",    1],
            [    662,    "rainbow good slow top",    16],
            [    678,    "UV pulse",    1],
            [    678,    "Autogen UV Strobe",    1],
            [    679,    "rainbow good slow top",    16],
            [    679,    "hooked wandering top",    16],
            [    695,    "UV pulse",    1],
            [    695,    "UV pulse slow",    2],
            [    697,    "Autogen UV Strobe",    1],
            [    697,    "Autogen bassline bottom",    2],
            [    699,    "Autogen bassline bottom",    2],
            [    699,    "UV pulse",    1],
            [    701,    "Autogen Strobe",    1],
            [    701,    "Autogen Strobe",    1],
            [    702,    "UV pulse slow",    2],
            [    702,    "Rainbow bad",    2],
            [    704,    "RBBB 1 bar",    4],
            [    704,    "Rainbow bad",    2],
            [    708,    "Autogen bassline sidechain bottom",    2],
            [    708,    "Ghosts riser",    4],
            [    712,    "Autogen bassline sidechain bottom",    2],
            [    712,    "Autogen bassline top",    2],
            [    714,    "UV pulse",    1],
            [    714,    "Rainbow bad",    2],
            [    716,    "UV pulse",    1],
            [    716,    "Autogen bassline top",    2],
            [    718,    "UV pulse slow",    2],
            [    718,    "Autogen Strobe",    1],
            [    720,    "Autogen UV Strobe",    1],
            [    720,    "Autogen UV Strobe",    1],
            [    721,    "hooked wandering top",    16],
            [    721,    "Autogen bassline bottom",    2]
        ],
        "bpm": 136,
        "delay_lights": 0.11299999999999999,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/Mad Zach - The Visitor.ogg"
    }
}