effects = {
    "g_Madeon - Be Fine (Official Audio)": {
        "beats": [
            [    1,    "rainbow good slow top",    16],
            [    1,    "Autogen bassline sidechain bottom",    2],
            [    17,    "Autogen UV Strobe",    1],
            [    17,    "rainbow good slow top",    16],
            [    33,    "Ghosts riser",    4],
            [    33,    "Rainbow bad",    2],
            [    37,    "hooked wandering bottom",    16],
            [    37,    "UV pulse",    1],
            [    53,    "Autogen Strobe",    1],
            [    53,    "UV pulse slow",    2],
            [    55,    "hooked wandering bottom",    16],
            [    55,    "Autogen bassline sidechain bottom",    2],
            [    71,    "UV pulse slow",    2],
            [    71,    "RBBB 1 bar",    4],
            [    75,    "UV pulse",    1],
            [    75,    "Autogen bassline bottom",    2],
            [    77,    "Autogen bassline bottom",    2],
            [    77,    "Rainbow bad",    2],
            [    79,    "Autogen Strobe",    1],
            [    79,    "Autogen bassline sidechain bottom",    2],
            [    81,    "rainbow good slow top",    16],
            [    81,    "hooked wandering top",    16],
            [    97,    "rainbow good slow top",    16],
            [    97,    "Ghosts riser",    4],
            [    113,    "Autogen bassline sidechain bottom",    2],
            [    113,    "RBBB 1 bar",    4],
            [    117,    "Autogen UV Strobe",    1],
            [    117,    "UV pulse slow",    2],
            [    119,    "Autogen Strobe",    1],
            [    119,    "hooked wandering top",    16],
            [    135,    "RBBB 1 bar",    4],
            [    135,    "Ghosts riser",    4],
            [    139,    "RBBB 1 bar",    4],
            [    139,    "Autogen Strobe",    1],
            [    143,    "RBBB 1 bar",    4],
            [    143,    "Rainbow bad",    2],
            [    147,    "Ghosts riser",    4],
            [    147,    "Rainbow bad",    2],
            [    151,    "RBBB 1 bar",    4],
            [    151,    "Autogen bassline bottom",    2],
            [    155,    "Rainbow bad",    2],
            [    155,    "Autogen bassline bottom",    2],
            [    157,    "Rainbow bad",    2],
            [    157,    "RBBB 1 bar",    4],
            [    161,    "hooked wandering bottom",    16],
            [    161,    "UV pulse slow",    2],
            [    177,    "hooked wandering bottom",    16],
            [    177,    "RBBB 1 bar",    4],
            [    193,    "Autogen bassline top",    2],
            [    193,    "hooked wandering bottom",    16],
            [    209,    "Autogen bassline top",    2],
            [    209,    "rainbow good slow top",    16],
            [    225,    "Ghosts riser",    4],
            [    225,    "hooked wandering top",    16],
            [    241,    "Autogen UV Strobe",    1],
            [    241,    "Autogen bassline bottom",    2],
            [    243,    "RBBB 1 bar",    4],
            [    243,    "RBBB 1 bar",    4],
            [    247,    "RBBB 1 bar",    4],
            [    247,    "Autogen bassline top",    2],
            [    251,    "Autogen bassline bottom",    2],
            [    251,    "Ghosts riser",    4],
            [    255,    "Autogen bassline top",    2],
            [    255,    "RBBB 1 bar",    4],
            [    259,    "Autogen bassline bottom",    2],
            [    259,    "Autogen Strobe",    1],
            [    261,    "hooked wandering bottom",    16],
            [    261,    "Autogen bassline sidechain bottom",    2],
            [    277,    "hooked wandering bottom",    16],
            [    277,    "Autogen bassline sidechain bottom",    2],
            [    293,    "Rainbow bad",    2],
            [    293,    "hooked wandering top",    16],
            [    309,    "Autogen bassline sidechain bottom",    2],
            [    309,    "Autogen UV Strobe",    1],
            [    311,    "rainbow good slow top",    16],
            [    311,    "hooked wandering top",    16],
            [    327,    "UV pulse slow",    2],
            [    327,    "Autogen bassline bottom",    2],
            [    329,    "UV pulse slow",    2],
            [    329,    "hooked wandering bottom",    16]
        ],
        "bpm": 94,
        "delay_lights": 0.2615,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/Madeon - Be Fine (Official Audio).ogg"
    }
}