effects = {
    "g_Madeon - Be Fine (Official Audio)": {
        "beats": [
            [    1,    "Autogen bassline sidechain bottom",    2],
            [    1,    "Ghosts riser",    4],
            [    5,    "hooked wandering bottom",    16],
            [    5,    "UV pulse",    1],
            [    21,    "Autogen UV Strobe",    1],
            [    21,    "hooked wandering top",    16],
            [    37,    "Ghosts riser",    4],
            [    37,    "rainbow good slow top",    16],
            [    53,    "Rainbow bad",    2],
            [    53,    "UV pulse slow",    2],
            [    55,    "RBBB 1 bar",    4],
            [    55,    "hooked wandering top",    16],
            [    71,    "Rainbow bad",    2],
            [    71,    "RBBB 1 bar",    4],
            [    75,    "RBBB 1 bar",    4],
            [    75,    "Autogen bassline bottom",    2],
            [    79,    "hooked wandering top",    16],
            [    79,    "hooked wandering bottom",    16],
            [    95,    "Autogen bassline top",    2],
            [    95,    "RBBB 1 bar",    4],
            [    99,    "Ghosts riser",    4],
            [    99,    "hooked wandering bottom",    16],
            [    115,    "UV pulse",    1],
            [    115,    "Rainbow bad",    2],
            [    117,    "Autogen bassline bottom",    2],
            [    117,    "Autogen UV Strobe",    1],
            [    119,    "rainbow good slow top",    16],
            [    119,    "hooked wandering bottom",    16],
            [    135,    "hooked wandering bottom",    16],
            [    135,    "Autogen bassline sidechain bottom",    2],
            [    151,    "Autogen bassline top",    2],
            [    151,    "UV pulse",    1],
            [    153,    "UV pulse slow",    2],
            [    153,    "Autogen Strobe",    1],
            [    155,    "Ghosts riser",    4],
            [    155,    "Rainbow bad",    2],
            [    159,    "Autogen UV Strobe",    1],
            [    159,    "Ghosts riser",    4],
            [    163,    "Ghosts riser",    4],
            [    163,    "Autogen bassline top",    2],
            [    167,    "hooked wandering bottom",    16],
            [    167,    "Autogen bassline sidechain bottom",    2],
            [    183,    "Rainbow bad",    2],
            [    183,    "Ghosts riser",    4],
            [    187,    "Autogen bassline sidechain bottom",    2],
            [    187,    "Autogen bassline bottom",    2],
            [    189,    "Autogen bassline bottom",    2],
            [    189,    "rainbow good slow top",    16],
            [    205,    "Autogen bassline sidechain bottom",    2],
            [    205,    "Ghosts riser",    4],
            [    209,    "Ghosts riser",    4],
            [    209,    "RBBB 1 bar",    4],
            [    213,    "UV pulse",    1],
            [    213,    "Rainbow bad",    2],
            [    215,    "Rainbow bad",    2],
            [    215,    "Autogen Strobe",    1],
            [    217,    "Ghosts riser",    4],
            [    217,    "hooked wandering bottom",    16],
            [    233,    "hooked wandering bottom",    16],
            [    233,    "Autogen bassline sidechain bottom",    2],
            [    249,    "UV pulse",    1],
            [    249,    "RBBB 1 bar",    4],
            [    253,    "Autogen UV Strobe",    1],
            [    253,    "Autogen bassline top",    2],
            [    255,    "Autogen bassline sidechain bottom",    2],
            [    255,    "Autogen bassline top",    2],
            [    257,    "hooked wandering bottom",    16],
            [    257,    "Ghosts riser",    4],
            [    273,    "Autogen bassline bottom",    2],
            [    273,    "Autogen bassline top",    2],
            [    275,    "Autogen bassline top",    2],
            [    275,    "rainbow good slow top",    16],
            [    291,    "UV pulse",    1],
            [    291,    "Ghosts riser",    4],
            [    295,    "UV pulse",    1],
            [    295,    "UV pulse slow",    2],
            [    297,    "Rainbow bad",    2],
            [    297,    "Autogen bassline bottom",    2],
            [    299,    "Ghosts riser",    4],
            [    299,    "Autogen bassline bottom",    2],
            [    303,    "RBBB 1 bar",    4],
            [    303,    "Autogen bassline bottom",    2],
            [    307,    "Autogen UV Strobe",    1],
            [    307,    "RBBB 1 bar",    4],
            [    311,    "UV pulse",    1],
            [    311,    "Rainbow bad",    2],
            [    313,    "hooked wandering top",    16],
            [    313,    "Autogen Strobe",    1],
            [    329,    "Autogen bassline top",    2],
            [    329,    "RBBB 1 bar",    4],
            [    333,    "hooked wandering top",    16],
            [    333,    "Autogen bassline top",    2]
        ],
        "bpm": 94,
        "delay_lights": 0.2615,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/Madeon - Be Fine (Official Audio).ogg"
    }
}