effects = {
    "g_Mad Zach - The Visitor": {
        "beats": [
            [    1,    "g_rainbow good top",    16],
            [    1,    "g_solid bottom cycle",    16],
            [    17,    "g_solid bottom cycle",    16],
            [    33,    "g_solid bottom cycle",    16],
            [    49,    "g_rainbow good slow top",    16],
            [    49,    "g_solid bottom cycle",    16],
            [    65,    "g_solid top cycle",    16],
            [    81,    "g_UV pulse",    2],
            [    83,    "RGB Flash",    1],
            [    84,    "g_solid mixed double",    16],
            [    84,    "g_UV",    16],
            [    100,    "g_solid bottom cycle",    16],
            [    100,    "g_UV",    16],
            [    116,    "g_green sidechain bottom pulse",    16],
            [    132,    "g_solid top cycle",    16],
            [    132,    "g_green sidechain bottom pulse",    16],
            [    132,    "g_UV",    16],
            [    148,    "g_solid bottom cycle",    16],
            [    164,    "g_rainbow good top",    16],
            [    164,    "g_solid bottom cycle",    16],
            [    180,    "g_UV pulse",    1],
            [    181,    "RGB Flash",    1],
            [    182,    "g_rainbow good top",    16],
            [    182,    "g_solid bottom cycle",    16],
            [    198,    "g_solid top cycle",    16],
            [    198,    "g_UV",    16],
            [    214,    "g_UV Strobe",    1],
            [    215,    "g_solid mixed double",    16],
            [    231,    "RGB Flash",    1],
            [    232,    "g_solid mixed double",    16],
            [    232,    "g_UV",    16],
            [    248,    "RGB Flash",    1],
            [    249,    "g_solid mixed double",    16],
            [    265,    "g_purple green bottom pulse",    16],
            [    281,    "g_UV pulse",    4],
            [    285,    "g_UV pulse",    4],
            [    289,    "g_solid mixed double",    16],
            [    305,    "g_solid mixed double",    16],
            [    305,    "g_UV",    16],
            [    321,    "g_purple green bottom pulse",    16],
            [    321,    "g_UV",    16],
            [    337,    "g_UV pulse",    2],
            [    339,    "g_cyan top pulse",    16],
            [    355,    "g_UV pulse",    1],
            [    356,    "g_solid mixed double",    16],
            [    356,    "g_UV",    16],
            [    372,    "g_solid mixed double",    16],
            [    372,    "g_UV",    16],
            [    388,    "g_solid mixed cycle",    16],
            [    404,    "g_cyan top pulse",    16],
            [    404,    "g_purple green bottom pulse",    16],
            [    420,    "g_solid top cycle",    16],
            [    420,    "g_green sidechain bottom pulse",    16],
            [    420,    "g_UV",    16],
            [    436,    "g_solid bottom cycle",    16],
            [    452,    "g_solid top cycle",    16],
            [    452,    "g_UV",    16],
            [    468,    "g_rainbow good top",    16],
            [    468,    "g_solid bottom cycle",    16],
            [    484,    "g_solid mixed double",    16],
            [    500,    "g_purple green bottom pulse",    16],
            [    500,    "g_UV",    16],
            [    516,    "g_UV pulse",    4],
            [    520,    "g_rainbow good slow top",    16],
            [    520,    "g_purple green bottom pulse",    16],
            [    536,    "RGB Flash",    1],
            [    537,    "g_cyan top pulse",    16],
            [    537,    "g_UV",    16],
            [    553,    "g_UV pulse",    4],
            [    557,    "g_solid top cycle",    16],
            [    557,    "g_green sidechain bottom pulse",    16],
            [    573,    "g_UV pulse",    2],
            [    575,    "g_cyan top pulse",    16],
            [    575,    "g_purple green bottom pulse",    16],
            [    591,    "g_cyan top pulse",    16],
            [    607,    "g_solid mixed double",    16],
            [    623,    "g_cyan top pulse",    16],
            [    623,    "g_solid bottom cycle",    16],
            [    623,    "g_UV",    16],
            [    639,    "g_rainbow good top",    16],
            [    639,    "g_green sidechain bottom pulse",    16],
            [    655,    "g_solid top cycle",    16],
            [    655,    "g_solid bottom cycle",    16],
            [    655,    "g_UV",    16],
            [    671,    "g_solid mixed cycle",    16],
            [    687,    "g_UV pulse",    1],
            [    688,    "g_purple green bottom pulse",    16],
            [    704,    "g_UV pulse",    4],
            [    708,    "g_UV pulse",    2],
            [    710,    "g_UV pulse",    2],
            [    712,    "g_solid top cycle",    16],
            [    728,    "g_cyan top pulse",    16],
            [    728,    "g_purple green bottom pulse",    16],
            [    728,    "g_UV",    16]
        ],
        "bpm": 136,
        "delay_lights": 0.11299999999999999,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/Mad Zach - The Visitor.ogg",
        "was_autogenerated": True
    }
}