effects = {
    "g_Mad Zach - The Visitor": {
        "beats": [
            [    1,    "Autogen UV Strobe",    1],
            [    1,    "UV pulse slow",    2],
            [    3,    "RBBB 1 bar",    4],
            [    3,    "Autogen UV Strobe",    1],
            [    7,    "Autogen bassline top",    2],
            [    7,    "UV pulse slow",    2],
            [    9,    "Autogen bassline top",    2],
            [    9,    "RBBB 1 bar",    4],
            [    13,    "UV pulse slow",    2],
            [    13,    "Autogen bassline top",    2],
            [    15,    "Autogen Strobe",    1],
            [    15,    "UV pulse",    1],
            [    16,    "Autogen bassline bottom",    2],
            [    16,    "UV pulse slow",    2],
            [    18,    "RBBB 1 bar",    4],
            [    18,    "Autogen bassline bottom",    2],
            [    22,    "hooked wandering top",    16],
            [    22,    "Autogen UV Strobe",    1],
            [    38,    "hooked wandering top",    16],
            [    38,    "hooked wandering top",    16],
            [    54,    "Ghosts riser",    4],
            [    54,    "hooked wandering bottom",    16],
            [    70,    "Autogen UV Strobe",    1],
            [    70,    "RBBB 1 bar",    4],
            [    74,    "Autogen Strobe",    1],
            [    74,    "UV pulse",    1],
            [    75,    "Autogen bassline bottom",    2],
            [    75,    "rainbow good slow top",    16],
            [    91,    "Rainbow bad",    2],
            [    91,    "UV pulse slow",    2],
            [    93,    "Autogen bassline sidechain bottom",    2],
            [    93,    "Autogen Strobe",    1],
            [    95,    "Autogen bassline top",    2],
            [    95,    "Rainbow bad",    2],
            [    97,    "Ghosts riser",    4],
            [    97,    "rainbow good slow top",    16],
            [    113,    "UV pulse",    1],
            [    113,    "UV pulse slow",    2],
            [    115,    "Autogen bassline top",    2],
            [    115,    "Autogen bassline sidechain bottom",    2],
            [    117,    "rainbow good slow top",    16],
            [    117,    "hooked wandering top",    16],
            [    133,    "rainbow good slow top",    16],
            [    133,    "rainbow good slow top",    16],
            [    149,    "Autogen UV Strobe",    1],
            [    149,    "UV pulse",    1],
            [    150,    "Autogen bassline sidechain bottom",    2],
            [    150,    "Autogen bassline sidechain bottom",    2],
            [    152,    "Autogen UV Strobe",    1],
            [    152,    "hooked wandering bottom",    16],
            [    168,    "Autogen Strobe",    1],
            [    168,    "UV pulse slow",    2],
            [    170,    "Rainbow bad",    2],
            [    170,    "Autogen bassline sidechain bottom",    2],
            [    172,    "Autogen Strobe",    1],
            [    172,    "Autogen UV Strobe",    1],
            [    173,    "RBBB 1 bar",    4],
            [    173,    "Rainbow bad",    2],
            [    177,    "rainbow good slow top",    16],
            [    177,    "Ghosts riser",    4],
            [    193,    "Autogen Strobe",    1],
            [    193,    "UV pulse",    1],
            [    194,    "hooked wandering bottom",    16],
            [    194,    "hooked wandering top",    16],
            [    210,    "hooked wandering bottom",    16],
            [    210,    "Autogen UV Strobe",    1],
            [    226,    "UV pulse",    1],
            [    226,    "Ghosts riser",    4],
            [    230,    "Autogen bassline sidechain bottom",    2],
            [    230,    "Autogen bassline top",    2],
            [    232,    "UV pulse slow",    2],
            [    232,    "Autogen bassline sidechain bottom",    2],
            [    234,    "Rainbow bad",    2],
            [    234,    "Autogen Strobe",    1],
            [    236,    "rainbow good slow top",    16],
            [    236,    "UV pulse",    1],
            [    252,    "rainbow good slow top",    16],
            [    252,    "UV pulse",    1],
            [    268,    "UV pulse",    1],
            [    268,    "Ghosts riser",    4],
            [    272,    "UV pulse",    1],
            [    272,    "Autogen bassline top",    2],
            [    274,    "UV pulse slow",    2],
            [    274,    "hooked wandering bottom",    16],
            [    290,    "Rainbow bad",    2],
            [    290,    "Autogen UV Strobe",    1],
            [    292,    "Autogen bassline top",    2],
            [    292,    "Autogen Strobe",    1],
            [    294,    "Autogen bassline bottom",    2],
            [    294,    "Autogen Strobe",    1],
            [    296,    "UV pulse slow",    2],
            [    296,    "Ghosts riser",    4],
            [    300,    "Ghosts riser",    4],
            [    300,    "Autogen UV Strobe",    1],
            [    304,    "Autogen UV Strobe",    1],
            [    304,    "Ghosts riser",    4],
            [    308,    "UV pulse",    1],
            [    308,    "UV pulse",    1],
            [    309,    "hooked wandering bottom",    16],
            [    309,    "Rainbow bad",    2],
            [    325,    "Autogen bassline bottom",    2],
            [    325,    "hooked wandering bottom",    16],
            [    341,    "hooked wandering top",    16],
            [    341,    "RBBB 1 bar",    4],
            [    357,    "hooked wandering top",    16],
            [    357,    "Rainbow bad",    2],
            [    373,    "Autogen bassline sidechain bottom",    2],
            [    373,    "UV pulse",    1],
            [    375,    "Autogen bassline top",    2],
            [    375,    "rainbow good slow top",    16],
            [    391,    "Autogen bassline top",    2],
            [    391,    "hooked wandering top",    16],
            [    407,    "hooked wandering bottom",    16],
            [    407,    "UV pulse",    1],
            [    423,    "Ghosts riser",    4],
            [    423,    "UV pulse",    1],
            [    427,    "UV pulse slow",    2],
            [    427,    "Autogen bassline sidechain bottom",    2],
            [    429,    "UV pulse slow",    2],
            [    429,    "UV pulse",    1],
            [    431,    "hooked wandering bottom",    16],
            [    431,    "Rainbow bad",    2],
            [    447,    "RBBB 1 bar",    4],
            [    447,    "Autogen UV Strobe",    1],
            [    451,    "Autogen bassline top",    2],
            [    451,    "RBBB 1 bar",    4],
            [    455,    "Autogen UV Strobe",    1],
            [    455,    "rainbow good slow top",    16],
            [    471,    "Autogen Strobe",    1],
            [    471,    "hooked wandering top",    16],
            [    487,    "hooked wandering bottom",    16],
            [    487,    "Autogen Strobe",    1],
            [    503,    "hooked wandering top",    16],
            [    503,    "RBBB 1 bar",    4],
            [    519,    "Autogen UV Strobe",    1],
            [    519,    "UV pulse",    1],
            [    520,    "Rainbow bad",    2],
            [    520,    "Ghosts riser",    4],
            [    524,    "hooked wandering bottom",    16],
            [    524,    "UV pulse slow",    2],
            [    540,    "rainbow good slow top",    16],
            [    540,    "hooked wandering bottom",    16],
            [    556,    "UV pulse slow",    2],
            [    556,    "Autogen Strobe",    1],
            [    558,    "Autogen UV Strobe",    1],
            [    558,    "Autogen Strobe",    1],
            [    559,    "RBBB 1 bar",    4],
            [    559,    "UV pulse",    1],
            [    563,    "hooked wandering bottom",    16],
            [    563,    "Autogen bassline sidechain bottom",    2],
            [    579,    "hooked wandering top",    16],
            [    579,    "Rainbow bad",    2],
            [    595,    "UV pulse",    1],
            [    595,    "Autogen bassline bottom",    2],
            [    597,    "Ghosts riser",    4],
            [    597,    "Rainbow bad",    2],
            [    601,    "hooked wandering bottom",    16],
            [    601,    "Ghosts riser",    4],
            [    617,    "Rainbow bad",    2],
            [    617,    "hooked wandering top",    16],
            [    633,    "rainbow good slow top",    16],
            [    633,    "hooked wandering bottom",    16],
            [    649,    "Autogen bassline bottom",    2],
            [    649,    "RBBB 1 bar",    4],
            [    653,    "Autogen bassline top",    2],
            [    653,    "Autogen Strobe",    1],
            [    655,    "Autogen bassline top",    2],
            [    655,    "Rainbow bad",    2],
            [    657,    "Autogen Strobe",    1],
            [    657,    "Autogen bassline bottom",    2],
            [    659,    "hooked wandering top",    16],
            [    659,    "Rainbow bad",    2],
            [    675,    "Autogen Strobe",    1],
            [    675,    "rainbow good slow top",    16],
            [    691,    "hooked wandering top",    16],
            [    691,    "UV pulse",    1],
            [    707,    "Autogen bassline bottom",    2],
            [    707,    "RBBB 1 bar",    4],
            [    711,    "Autogen bassline top",    2],
            [    711,    "Autogen bassline sidechain bottom",    2],
            [    713,    "Rainbow bad",    2],
            [    713,    "Ghosts riser",    4],
            [    717,    "Autogen bassline sidechain bottom",    2],
            [    717,    "Autogen bassline top",    2],
            [    719,    "RBBB 1 bar",    4],
            [    719,    "rainbow good slow top",    16]
        ],
        "bpm": 136,
        "delay_lights": 0.11299999999999999,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/Mad Zach - The Visitor.ogg"
    }
}