effects = {
    "g_mo_bamba": {
        "beats": [
            [    1,    "UV pulse slow",    2],
            [    1,    "Autogen Strobe",    1],
            [    3,    "Ghosts riser",    4],
            [    3,    "UV pulse",    1],
            [    7,    "Autogen bassline top",    2],
            [    7,    "UV pulse",    1],
            [    9,    "Rainbow bad",    2],
            [    9,    "UV pulse",    1],
            [    11,    "Autogen bassline sidechain bottom",    2],
            [    11,    "Rainbow bad",    2],
            [    13,    "UV pulse slow",    2],
            [    13,    "Autogen bassline top",    2],
            [    15,    "RBBB 1 bar",    4],
            [    15,    "hooked wandering top",    16],
            [    31,    "Autogen bassline bottom",    2],
            [    31,    "Ghosts riser",    4],
            [    35,    "Autogen UV Strobe",    1],
            [    35,    "RBBB 1 bar",    4],
            [    39,    "Rainbow bad",    2],
            [    39,    "hooked wandering top",    16],
            [    55,    "UV pulse",    1],
            [    55,    "Autogen bassline bottom",    2],
            [    57,    "Rainbow bad",    2],
            [    57,    "hooked wandering bottom",    16],
            [    73,    "rainbow good slow top",    16],
            [    73,    "hooked wandering bottom",    16],
            [    89,    "hooked wandering top",    16],
            [    89,    "UV pulse slow",    2],
            [    105,    "UV pulse slow",    2],
            [    105,    "Autogen UV Strobe",    1],
            [    107,    "Autogen Strobe",    1],
            [    107,    "Autogen bassline sidechain bottom",    2],
            [    109,    "hooked wandering top",    16],
            [    109,    "Rainbow bad",    2],
            [    125,    "hooked wandering top",    16],
            [    125,    "Autogen UV Strobe",    1],
            [    141,    "UV pulse slow",    2],
            [    141,    "Autogen UV Strobe",    1],
            [    143,    "UV pulse slow",    2],
            [    143,    "rainbow good slow top",    16],
            [    159,    "hooked wandering top",    16],
            [    159,    "Ghosts riser",    4],
            [    175,    "Autogen bassline bottom",    2],
            [    175,    "UV pulse slow",    2],
            [    177,    "UV pulse",    1],
            [    177,    "Autogen UV Strobe",    1],
            [    178,    "Autogen bassline bottom",    2],
            [    178,    "Autogen bassline sidechain bottom",    2],
            [    180,    "rainbow good slow top",    16],
            [    180,    "UV pulse slow",    2],
            [    196,    "Autogen Strobe",    1],
            [    196,    "Autogen Strobe",    1],
            [    197,    "Autogen bassline sidechain bottom",    2],
            [    197,    "hooked wandering top",    16],
            [    213,    "RBBB 1 bar",    4],
            [    213,    "Autogen bassline sidechain bottom",    2],
            [    217,    "RBBB 1 bar",    4],
            [    217,    "hooked wandering top",    16],
            [    233,    "UV pulse",    1],
            [    233,    "rainbow good slow top",    16],
            [    249,    "RBBB 1 bar",    4],
            [    249,    "RBBB 1 bar",    4],
            [    253,    "Autogen bassline top",    2],
            [    253,    "hooked wandering top",    16],
            [    269,    "Autogen bassline bottom",    2],
            [    269,    "Autogen Strobe",    1],
            [    271,    "UV pulse slow",    2],
            [    271,    "UV pulse",    1],
            [    273,    "hooked wandering top",    16],
            [    273,    "Autogen bassline sidechain bottom",    2],
            [    289,    "Autogen Strobe",    1],
            [    289,    "hooked wandering top",    16],
            [    305,    "Autogen bassline top",    2],
            [    305,    "Autogen bassline bottom",    2],
            [    307,    "hooked wandering top",    16],
            [    307,    "UV pulse",    1],
            [    323,    "Rainbow bad",    2],
            [    323,    "hooked wandering bottom",    16],
            [    339,    "UV pulse slow",    2],
            [    339,    "RBBB 1 bar",    4],
            [    343,    "Autogen UV Strobe",    1],
            [    343,    "Ghosts riser",    4],
            [    347,    "UV pulse slow",    2],
            [    347,    "Autogen bassline bottom",    2],
            [    349,    "hooked wandering bottom",    16],
            [    349,    "UV pulse slow",    2],
            [    365,    "hooked wandering bottom",    16],
            [    365,    "hooked wandering bottom",    16],
            [    381,    "hooked wandering bottom",    16],
            [    381,    "rainbow good slow top",    16],
            [    397,    "Ghosts riser",    4],
            [    397,    "Rainbow bad",    2],
            [    401,    "UV pulse slow",    2],
            [    401,    "Rainbow bad",    2],
            [    403,    "Autogen bassline top",    2],
            [    403,    "RBBB 1 bar",    4],
            [    407,    "Autogen bassline top",    2],
            [    407,    "RBBB 1 bar",    4],
            [    411,    "RBBB 1 bar",    4],
            [    411,    "Autogen Strobe",    1],
            [    415,    "Autogen bassline bottom",    2],
            [    415,    "UV pulse",    1],
            [    417,    "UV pulse slow",    2],
            [    417,    "hooked wandering bottom",    16],
            [    433,    "Autogen UV Strobe",    1],
            [    433,    "Ghosts riser",    4],
            [    437,    "Ghosts riser",    4],
            [    437,    "hooked wandering top",    16]
        ],
        "bpm": 146,
        "delay_lights": 0.0843,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/mo_bamba.ogg"
    }
}