effects = {
    "g_mo_bamba": {
        "beats": [
            [    1,    "Rainbow bad",    2],
            [    1,    "hooked wandering bottom",    16],
            [    17,    "Autogen UV Strobe",    1],
            [    17,    "Autogen bassline bottom",    2],
            [    19,    "Autogen bassline sidechain bottom",    2],
            [    19,    "Rainbow bad",    2],
            [    21,    "RBBB 1 bar",    4],
            [    21,    "UV pulse",    1],
            [    25,    "RBBB 1 bar",    4],
            [    25,    "Autogen bassline top",    2],
            [    29,    "Autogen UV Strobe",    1],
            [    29,    "hooked wandering top",    16],
            [    45,    "Autogen bassline sidechain bottom",    2],
            [    45,    "hooked wandering bottom",    16],
            [    61,    "rainbow good slow top",    16],
            [    61,    "RBBB 1 bar",    4],
            [    77,    "UV pulse slow",    2],
            [    77,    "Autogen bassline bottom",    2],
            [    79,    "Autogen bassline top",    2],
            [    79,    "Autogen Strobe",    1],
            [    81,    "rainbow good slow top",    16],
            [    81,    "Ghosts riser",    4],
            [    97,    "UV pulse slow",    2],
            [    97,    "hooked wandering top",    16],
            [    113,    "Rainbow bad",    2],
            [    113,    "UV pulse",    1],
            [    115,    "Autogen bassline top",    2],
            [    115,    "Ghosts riser",    4],
            [    119,    "Autogen UV Strobe",    1],
            [    119,    "Autogen Strobe",    1],
            [    120,    "Ghosts riser",    4],
            [    120,    "UV pulse slow",    2],
            [    124,    "hooked wandering bottom",    16],
            [    124,    "Rainbow bad",    2],
            [    140,    "RBBB 1 bar",    4],
            [    140,    "Autogen bassline top",    2],
            [    144,    "Ghosts riser",    4],
            [    144,    "hooked wandering bottom",    16],
            [    160,    "RBBB 1 bar",    4],
            [    160,    "Autogen bassline sidechain bottom",    2],
            [    164,    "RBBB 1 bar",    4],
            [    164,    "Autogen UV Strobe",    1],
            [    168,    "Rainbow bad",    2],
            [    168,    "RBBB 1 bar",    4],
            [    172,    "Rainbow bad",    2],
            [    172,    "rainbow good slow top",    16],
            [    188,    "Rainbow bad",    2],
            [    188,    "Ghosts riser",    4],
            [    192,    "Autogen bassline bottom",    2],
            [    192,    "hooked wandering top",    16],
            [    208,    "Autogen bassline bottom",    2],
            [    208,    "Autogen bassline bottom",    2],
            [    210,    "Ghosts riser",    4],
            [    210,    "Autogen bassline top",    2],
            [    214,    "Autogen UV Strobe",    1],
            [    214,    "Autogen bassline top",    2],
            [    216,    "Rainbow bad",    2],
            [    216,    "Autogen bassline sidechain bottom",    2],
            [    218,    "hooked wandering bottom",    16],
            [    218,    "Autogen bassline top",    2],
            [    234,    "Autogen bassline sidechain bottom",    2],
            [    234,    "Autogen UV Strobe",    1],
            [    236,    "hooked wandering top",    16],
            [    236,    "RBBB 1 bar",    4],
            [    252,    "Rainbow bad",    2],
            [    252,    "Rainbow bad",    2],
            [    254,    "Autogen Strobe",    1],
            [    254,    "Autogen Strobe",    1],
            [    255,    "RBBB 1 bar",    4],
            [    255,    "UV pulse slow",    2],
            [    259,    "UV pulse",    1],
            [    259,    "rainbow good slow top",    16],
            [    275,    "UV pulse",    1],
            [    275,    "Autogen bassline sidechain bottom",    2],
            [    277,    "Autogen bassline sidechain bottom",    2],
            [    277,    "UV pulse slow",    2],
            [    279,    "UV pulse slow",    2],
            [    279,    "Autogen UV Strobe",    1],
            [    281,    "Autogen bassline sidechain bottom",    2],
            [    281,    "hooked wandering top",    16],
            [    297,    "rainbow good slow top",    16],
            [    297,    "RBBB 1 bar",    4],
            [    313,    "rainbow good slow top",    16],
            [    313,    "UV pulse slow",    2],
            [    329,    "Autogen bassline sidechain bottom",    2],
            [    329,    "hooked wandering bottom",    16],
            [    345,    "Autogen bassline sidechain bottom",    2],
            [    345,    "Ghosts riser",    4],
            [    349,    "hooked wandering bottom",    16],
            [    349,    "Ghosts riser",    4],
            [    365,    "Autogen Strobe",    1],
            [    365,    "Autogen bassline sidechain bottom",    2],
            [    367,    "Autogen bassline bottom",    2],
            [    367,    "Autogen Strobe",    1],
            [    369,    "UV pulse slow",    2],
            [    369,    "hooked wandering bottom",    16],
            [    385,    "Autogen bassline bottom",    2],
            [    385,    "UV pulse",    1],
            [    387,    "UV pulse",    1],
            [    387,    "Autogen bassline bottom",    2],
            [    389,    "Autogen bassline top",    2],
            [    389,    "Autogen Strobe",    1],
            [    391,    "Autogen bassline sidechain bottom",    2],
            [    391,    "UV pulse slow",    2],
            [    393,    "rainbow good slow top",    16],
            [    393,    "Autogen bassline bottom",    2],
            [    409,    "Rainbow bad",    2],
            [    409,    "UV pulse",    1],
            [    411,    "RBBB 1 bar",    4],
            [    411,    "Autogen bassline top",    2],
            [    415,    "RBBB 1 bar",    4],
            [    415,    "rainbow good slow top",    16],
            [    431,    "rainbow good slow top",    16],
            [    431,    "UV pulse",    1],
            [    447,    "Autogen bassline bottom",    2],
            [    447,    "rainbow good slow top",    16]
        ],
        "bpm": 146,
        "delay_lights": 0.0843,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/mo_bamba.ogg"
    }
}