effects = {
    "g_Neon Pattern Drum": {
        "beats": [
            [    1,    "g_UV Strobe",    1],
            [    2,    "g_solid top cycle",    16],
            [    2,    "g_UV",    16],
            [    18,    "RGB Flash",    1],
            [    19,    "g_UV pulse",    1],
            [    20,    "g_solid mixed double",    16],
            [    36,    "g_UV pulse",    2],
            [    38,    "g_solid mixed double",    16],
            [    38,    "g_UV",    16],
            [    54,    "g_solid top cycle",    16],
            [    70,    "g_UV pulse",    4],
            [    74,    "g_solid top cycle",    16],
            [    74,    "g_green sidechain bottom pulse",    16],
            [    74,    "g_UV",    16],
            [    90,    "g_UV pulse",    2],
            [    92,    "g_cyan top pulse",    16],
            [    92,    "g_UV",    16],
            [    108,    "g_purple green bottom pulse",    16],
            [    124,    "g_purple green bottom pulse",    16],
            [    124,    "g_UV",    16],
            [    140,    "g_purple green bottom pulse",    16],
            [    156,    "g_UV pulse",    1],
            [    157,    "g_rainbow good slow top",    16],
            [    157,    "g_solid bottom cycle",    16],
            [    173,    "g_UV pulse",    4],
            [    177,    "g_UV pulse",    1],
            [    178,    "g_purple green bottom pulse",    16],
            [    194,    "g_solid mixed cycle",    16],
            [    210,    "g_UV pulse",    2],
            [    212,    "g_rainbow good slow top",    16],
            [    212,    "g_purple green bottom pulse",    16],
            [    228,    "g_solid mixed double",    16],
            [    228,    "g_UV",    16],
            [    244,    "g_solid top cycle",    16],
            [    244,    "g_green sidechain bottom pulse",    16],
            [    244,    "g_UV",    16],
            [    260,    "g_solid mixed double",    16],
            [    260,    "g_UV",    16],
            [    276,    "g_solid top cycle",    16],
            [    292,    "g_cyan top pulse",    16],
            [    292,    "g_green sidechain bottom pulse",    16],
            [    308,    "g_solid mixed double",    16],
            [    308,    "g_UV",    16],
            [    324,    "g_solid top cycle",    16],
            [    324,    "g_solid bottom cycle",    16],
            [    340,    "g_solid top cycle",    16],
            [    356,    "RGB Flash",    1],
            [    357,    "g_solid mixed cycle",    16],
            [    357,    "g_UV",    16],
            [    373,    "g_solid mixed double",    16],
            [    389,    "RGB Flash",    1],
            [    390,    "g_rainbow good top",    16],
            [    390,    "g_purple green bottom pulse",    16],
            [    406,    "g_rainbow good top",    16],
            [    406,    "g_green sidechain bottom pulse",    16],
            [    422,    "g_green sidechain bottom pulse",    16],
            [    438,    "g_UV pulse",    1],
            [    439,    "g_purple green bottom pulse",    16],
            [    439,    "g_UV",    16],
            [    455,    "g_solid bottom cycle",    16],
            [    455,    "g_UV",    16],
            [    471,    "g_solid bottom cycle",    16],
            [    471,    "g_UV",    16],
            [    487,    "g_cyan top pulse",    16],
            [    503,    "RGB Flash",    1],
            [    504,    "g_solid bottom cycle",    16],
            [    504,    "g_UV",    16],
            [    520,    "RGB Flash",    1],
            [    521,    "g_solid top cycle",    16],
            [    537,    "g_Strobe",    1],
            [    538,    "g_solid bottom cycle",    16],
            [    538,    "g_UV",    16],
            [    554,    "g_UV Strobe",    1],
            [    555,    "g_solid top cycle",    16],
            [    555,    "g_solid bottom cycle",    16],
            [    555,    "g_UV",    16],
            [    571,    "g_solid mixed double",    16],
            [    587,    "g_solid top cycle",    16],
            [    587,    "g_green sidechain bottom pulse",    16],
            [    603,    "g_rainbow good top",    16],
            [    603,    "g_green sidechain bottom pulse",    16],
            [    619,    "g_UV pulse",    4],
            [    623,    "g_UV pulse",    4],
            [    627,    "g_green sidechain bottom pulse",    16],
            [    627,    "g_UV",    16],
            [    643,    "g_solid top cycle",    16],
            [    643,    "g_UV",    16],
            [    659,    "g_Strobe",    1],
            [    660,    "g_cyan top pulse",    16],
            [    660,    "g_purple green bottom pulse",    16],
            [    660,    "g_UV",    16],
            [    676,    "g_UV pulse",    2],
            [    678,    "g_UV pulse",    2],
            [    680,    "g_solid mixed cycle",    16],
            [    696,    "RGB Flash",    1],
            [    697,    "g_green sidechain bottom pulse",    16],
            [    713,    "g_UV pulse",    2],
            [    715,    "g_rainbow good slow top",    16],
            [    715,    "g_solid bottom cycle",    16],
            [    731,    "g_cyan top pulse",    16],
            [    731,    "g_UV",    16],
            [    747,    "g_purple green bottom pulse",    16],
            [    747,    "g_UV",    16],
            [    763,    "g_UV pulse",    4]
        ],
        "bpm": 125,
        "delay_lights": 0.0246,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/Neon Pattern Drum.ogg",
        "was_autogenerated": True
    }
}