effects = {
    "g_Neon Pattern Drum": {
        "beats": [
            [    1,    "rainbow good slow top",    16],
            [    1,    "UV pulse slow",    2],
            [    17,    "Autogen bassline sidechain bottom",    2],
            [    17,    "Rainbow bad",    2],
            [    19,    "UV pulse",    1],
            [    19,    "Autogen bassline bottom",    2],
            [    21,    "RBBB 1 bar",    4],
            [    21,    "Ghosts riser",    4],
            [    25,    "Autogen Strobe",    1],
            [    25,    "hooked wandering bottom",    16],
            [    41,    "Autogen Strobe",    1],
            [    41,    "hooked wandering bottom",    16],
            [    57,    "RBBB 1 bar",    4],
            [    57,    "Autogen UV Strobe",    1],
            [    61,    "RBBB 1 bar",    4],
            [    61,    "Autogen Strobe",    1],
            [    65,    "Ghosts riser",    4],
            [    65,    "hooked wandering top",    16],
            [    81,    "hooked wandering top",    16],
            [    81,    "rainbow good slow top",    16],
            [    97,    "rainbow good slow top",    16],
            [    97,    "hooked wandering top",    16],
            [    113,    "Autogen Strobe",    1],
            [    113,    "Autogen bassline top",    2],
            [    115,    "hooked wandering top",    16],
            [    115,    "RBBB 1 bar",    4],
            [    131,    "Autogen bassline sidechain bottom",    2],
            [    131,    "Autogen UV Strobe",    1],
            [    133,    "Autogen bassline top",    2],
            [    133,    "Autogen bassline bottom",    2],
            [    135,    "Ghosts riser",    4],
            [    135,    "Autogen Strobe",    1],
            [    139,    "UV pulse slow",    2],
            [    139,    "Rainbow bad",    2],
            [    141,    "Autogen Strobe",    1],
            [    141,    "UV pulse slow",    2],
            [    143,    "hooked wandering top",    16],
            [    143,    "Ghosts riser",    4],
            [    159,    "rainbow good slow top",    16],
            [    159,    "hooked wandering top",    16],
            [    175,    "UV pulse",    1],
            [    175,    "Ghosts riser",    4],
            [    179,    "Autogen bassline top",    2],
            [    179,    "Autogen bassline sidechain bottom",    2],
            [    181,    "Rainbow bad",    2],
            [    181,    "Autogen bassline sidechain bottom",    2],
            [    183,    "Autogen bassline sidechain bottom",    2],
            [    183,    "Rainbow bad",    2],
            [    185,    "Rainbow bad",    2],
            [    185,    "Autogen UV Strobe",    1],
            [    187,    "UV pulse slow",    2],
            [    187,    "Ghosts riser",    4],
            [    191,    "Ghosts riser",    4],
            [    191,    "Autogen bassline bottom",    2],
            [    195,    "rainbow good slow top",    16],
            [    195,    "Autogen bassline bottom",    2],
            [    211,    "Rainbow bad",    2],
            [    211,    "Autogen bassline top",    2],
            [    213,    "hooked wandering bottom",    16],
            [    213,    "hooked wandering bottom",    16],
            [    229,    "Ghosts riser",    4],
            [    229,    "Autogen bassline top",    2],
            [    233,    "Autogen bassline bottom",    2],
            [    233,    "Autogen bassline top",    2],
            [    235,    "hooked wandering top",    16],
            [    235,    "rainbow good slow top",    16],
            [    251,    "Rainbow bad",    2],
            [    251,    "Rainbow bad",    2],
            [    253,    "RBBB 1 bar",    4],
            [    253,    "hooked wandering bottom",    16],
            [    269,    "Rainbow bad",    2],
            [    269,    "UV pulse",    1],
            [    271,    "Autogen bassline bottom",    2],
            [    271,    "Autogen bassline sidechain bottom",    2],
            [    273,    "Autogen Strobe",    1],
            [    273,    "Autogen bassline bottom",    2],
            [    275,    "Autogen bassline bottom",    2],
            [    275,    "hooked wandering top",    16],
            [    291,    "rainbow good slow top",    16],
            [    291,    "RBBB 1 bar",    4],
            [    307,    "Rainbow bad",    2],
            [    307,    "hooked wandering top",    16],
            [    323,    "Ghosts riser",    4],
            [    323,    "Rainbow bad",    2],
            [    327,    "Autogen bassline bottom",    2],
            [    327,    "Autogen bassline sidechain bottom",    2],
            [    329,    "hooked wandering top",    16],
            [    329,    "UV pulse",    1],
            [    345,    "Autogen bassline bottom",    2],
            [    345,    "hooked wandering top",    16],
            [    361,    "Autogen bassline sidechain bottom",    2],
            [    361,    "Autogen bassline bottom",    2],
            [    363,    "Autogen UV Strobe",    1],
            [    363,    "Autogen bassline sidechain bottom",    2],
            [    365,    "hooked wandering bottom",    16],
            [    365,    "hooked wandering bottom",    16],
            [    381,    "hooked wandering top",    16],
            [    381,    "UV pulse slow",    2],
            [    397,    "Rainbow bad",    2],
            [    397,    "Rainbow bad",    2],
            [    399,    "hooked wandering top",    16],
            [    399,    "Autogen bassline bottom",    2],
            [    415,    "Autogen Strobe",    1],
            [    415,    "Ghosts riser",    4],
            [    419,    "rainbow good slow top",    16],
            [    419,    "Autogen bassline top",    2],
            [    435,    "Autogen UV Strobe",    1],
            [    435,    "hooked wandering bottom",    16],
            [    451,    "rainbow good slow top",    16],
            [    451,    "Rainbow bad",    2],
            [    467,    "hooked wandering top",    16],
            [    467,    "Rainbow bad",    2],
            [    483,    "hooked wandering top",    16],
            [    483,    "Rainbow bad",    2],
            [    499,    "hooked wandering top",    16],
            [    499,    "rainbow good slow top",    16],
            [    515,    "hooked wandering top",    16],
            [    515,    "rainbow good slow top",    16],
            [    531,    "rainbow good slow top",    16],
            [    531,    "UV pulse",    1],
            [    547,    "Autogen bassline bottom",    2],
            [    547,    "hooked wandering top",    16],
            [    563,    "Autogen bassline sidechain bottom",    2],
            [    563,    "rainbow good slow top",    16],
            [    579,    "RBBB 1 bar",    4],
            [    579,    "rainbow good slow top",    16],
            [    595,    "Ghosts riser",    4],
            [    595,    "UV pulse",    1],
            [    599,    "RBBB 1 bar",    4],
            [    599,    "hooked wandering top",    16],
            [    615,    "Autogen bassline sidechain bottom",    2],
            [    615,    "rainbow good slow top",    16],
            [    631,    "Rainbow bad",    2],
            [    631,    "RBBB 1 bar",    4],
            [    635,    "Autogen bassline top",    2],
            [    635,    "UV pulse slow",    2],
            [    637,    "Autogen bassline bottom",    2],
            [    637,    "UV pulse",    1],
            [    639,    "Ghosts riser",    4],
            [    639,    "rainbow good slow top",    16],
            [    655,    "Ghosts riser",    4],
            [    655,    "Autogen bassline bottom",    2],
            [    659,    "hooked wandering top",    16],
            [    659,    "Rainbow bad",    2],
            [    675,    "Autogen UV Strobe",    1],
            [    675,    "Rainbow bad",    2],
            [    677,    "RBBB 1 bar",    4],
            [    677,    "RBBB 1 bar",    4],
            [    681,    "Autogen bassline top",    2],
            [    681,    "UV pulse slow",    2],
            [    683,    "Autogen bassline top",    2],
            [    683,    "Autogen Strobe",    1],
            [    685,    "Rainbow bad",    2],
            [    685,    "Ghosts riser",    4],
            [    689,    "Autogen bassline bottom",    2],
            [    689,    "RBBB 1 bar",    4],
            [    693,    "Autogen UV Strobe",    1],
            [    693,    "Autogen Strobe",    1],
            [    694,    "Rainbow bad",    2],
            [    694,    "UV pulse slow",    2],
            [    696,    "Autogen bassline top",    2],
            [    696,    "rainbow good slow top",    16],
            [    712,    "Autogen bassline sidechain bottom",    2],
            [    712,    "UV pulse",    1],
            [    714,    "UV pulse",    1],
            [    714,    "rainbow good slow top",    16],
            [    730,    "hooked wandering top",    16],
            [    730,    "Autogen bassline bottom",    2],
            [    746,    "Autogen Strobe",    1],
            [    746,    "Autogen bassline bottom",    2],
            [    748,    "UV pulse slow",    2],
            [    748,    "Rainbow bad",    2],
            [    750,    "Autogen bassline sidechain bottom",    2],
            [    750,    "Autogen UV Strobe",    1],
            [    752,    "Rainbow bad",    2],
            [    752,    "hooked wandering top",    16]
        ],
        "bpm": 125,
        "delay_lights": 0.0246,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/Neon Pattern Drum.ogg"
    }
}