effects = {
    "g_Neon Pattern Drum": {
        "beats": [
            [    1,    "UV pulse",    1],
            [    1,    "hooked wandering top",    16],
            [    17,    "Autogen bassline bottom",    2],
            [    17,    "Autogen UV Strobe",    1],
            [    19,    "Rainbow bad",    2],
            [    19,    "Rainbow bad",    2],
            [    21,    "Rainbow bad",    2],
            [    21,    "hooked wandering top",    16],
            [    37,    "hooked wandering top",    16],
            [    37,    "UV pulse",    1],
            [    53,    "rainbow good slow top",    16],
            [    53,    "Autogen bassline top",    2],
            [    69,    "Ghosts riser",    4],
            [    69,    "rainbow good slow top",    16],
            [    85,    "Autogen Strobe",    1],
            [    85,    "rainbow good slow top",    16],
            [    101,    "rainbow good slow top",    16],
            [    101,    "Autogen bassline sidechain bottom",    2],
            [    117,    "Autogen UV Strobe",    1],
            [    117,    "RBBB 1 bar",    4],
            [    121,    "Rainbow bad",    2],
            [    121,    "UV pulse",    1],
            [    123,    "Autogen bassline bottom",    2],
            [    123,    "hooked wandering top",    16],
            [    139,    "UV pulse slow",    2],
            [    139,    "Autogen bassline bottom",    2],
            [    141,    "Autogen UV Strobe",    1],
            [    141,    "Autogen bassline top",    2],
            [    143,    "Rainbow bad",    2],
            [    143,    "Autogen Strobe",    1],
            [    145,    "hooked wandering bottom",    16],
            [    145,    "hooked wandering bottom",    16],
            [    161,    "Autogen UV Strobe",    1],
            [    161,    "hooked wandering top",    16],
            [    177,    "Autogen bassline top",    2],
            [    177,    "Rainbow bad",    2],
            [    179,    "Autogen bassline top",    2],
            [    179,    "RBBB 1 bar",    4],
            [    183,    "Autogen Strobe",    1],
            [    183,    "hooked wandering bottom",    16],
            [    199,    "hooked wandering top",    16],
            [    199,    "hooked wandering top",    16],
            [    215,    "Ghosts riser",    4],
            [    215,    "RBBB 1 bar",    4],
            [    219,    "Autogen Strobe",    1],
            [    219,    "UV pulse",    1],
            [    220,    "Ghosts riser",    4],
            [    220,    "RBBB 1 bar",    4],
            [    224,    "hooked wandering top",    16],
            [    224,    "Autogen UV Strobe",    1],
            [    240,    "hooked wandering bottom",    16],
            [    240,    "Autogen UV Strobe",    1],
            [    256,    "Autogen bassline bottom",    2],
            [    256,    "RBBB 1 bar",    4],
            [    260,    "Autogen Strobe",    1],
            [    260,    "UV pulse",    1],
            [    261,    "hooked wandering bottom",    16],
            [    261,    "RBBB 1 bar",    4],
            [    277,    "UV pulse",    1],
            [    277,    "Autogen bassline top",    2],
            [    279,    "Autogen bassline top",    2],
            [    279,    "Rainbow bad",    2],
            [    281,    "UV pulse",    1],
            [    281,    "rainbow good slow top",    16],
            [    297,    "Autogen Strobe",    1],
            [    297,    "Autogen bassline bottom",    2],
            [    299,    "rainbow good slow top",    16],
            [    299,    "Autogen UV Strobe",    1],
            [    315,    "UV pulse slow",    2],
            [    315,    "Autogen bassline sidechain bottom",    2],
            [    317,    "Autogen Strobe",    1],
            [    317,    "Ghosts riser",    4],
            [    321,    "RBBB 1 bar",    4],
            [    321,    "Ghosts riser",    4],
            [    325,    "hooked wandering bottom",    16],
            [    325,    "hooked wandering top",    16],
            [    341,    "Autogen bassline top",    2],
            [    341,    "UV pulse slow",    2],
            [    343,    "Autogen bassline top",    2],
            [    343,    "Ghosts riser",    4],
            [    347,    "Ghosts riser",    4],
            [    347,    "hooked wandering bottom",    16],
            [    363,    "Autogen bassline sidechain bottom",    2],
            [    363,    "Autogen UV Strobe",    1],
            [    365,    "Rainbow bad",    2],
            [    365,    "Autogen bassline top",    2],
            [    367,    "Autogen bassline sidechain bottom",    2],
            [    367,    "rainbow good slow top",    16],
            [    383,    "Autogen bassline top",    2],
            [    383,    "hooked wandering top",    16],
            [    399,    "Rainbow bad",    2],
            [    399,    "Ghosts riser",    4],
            [    403,    "UV pulse slow",    2],
            [    403,    "Autogen Strobe",    1],
            [    405,    "Autogen Strobe",    1],
            [    405,    "Autogen bassline sidechain bottom",    2],
            [    407,    "Autogen bassline bottom",    2],
            [    407,    "Autogen UV Strobe",    1],
            [    409,    "hooked wandering top",    16],
            [    409,    "RBBB 1 bar",    4],
            [    425,    "rainbow good slow top",    16],
            [    425,    "hooked wandering bottom",    16],
            [    441,    "Rainbow bad",    2],
            [    441,    "UV pulse slow",    2],
            [    443,    "hooked wandering top",    16],
            [    443,    "Autogen bassline top",    2],
            [    459,    "hooked wandering bottom",    16],
            [    459,    "rainbow good slow top",    16],
            [    475,    "RBBB 1 bar",    4],
            [    475,    "Autogen bassline bottom",    2],
            [    479,    "Autogen UV Strobe",    1],
            [    479,    "hooked wandering top",    16],
            [    495,    "Autogen bassline sidechain bottom",    2],
            [    495,    "rainbow good slow top",    16],
            [    511,    "RBBB 1 bar",    4],
            [    511,    "Ghosts riser",    4],
            [    515,    "RBBB 1 bar",    4],
            [    515,    "Autogen bassline sidechain bottom",    2],
            [    519,    "rainbow good slow top",    16],
            [    519,    "Autogen bassline sidechain bottom",    2],
            [    535,    "Ghosts riser",    4],
            [    535,    "Autogen bassline sidechain bottom",    2],
            [    539,    "Autogen bassline top",    2],
            [    539,    "Autogen UV Strobe",    1],
            [    541,    "Autogen UV Strobe",    1],
            [    541,    "Rainbow bad",    2],
            [    543,    "Autogen bassline top",    2],
            [    543,    "RBBB 1 bar",    4],
            [    547,    "UV pulse slow",    2],
            [    547,    "Autogen Strobe",    1],
            [    549,    "UV pulse slow",    2],
            [    549,    "Ghosts riser",    4],
            [    553,    "RBBB 1 bar",    4],
            [    553,    "Ghosts riser",    4],
            [    557,    "rainbow good slow top",    16],
            [    557,    "Autogen bassline bottom",    2],
            [    573,    "Autogen bassline sidechain bottom",    2],
            [    573,    "Autogen Strobe",    1],
            [    575,    "Autogen bassline bottom",    2],
            [    575,    "Autogen bassline sidechain bottom",    2],
            [    577,    "Rainbow bad",    2],
            [    577,    "UV pulse slow",    2],
            [    579,    "Autogen bassline top",    2],
            [    579,    "Autogen UV Strobe",    1],
            [    581,    "hooked wandering bottom",    16],
            [    581,    "hooked wandering top",    16],
            [    597,    "Autogen UV Strobe",    1],
            [    597,    "Autogen UV Strobe",    1],
            [    598,    "Autogen bassline bottom",    2],
            [    598,    "RBBB 1 bar",    4],
            [    602,    "Autogen bassline top",    2],
            [    602,    "Autogen Strobe",    1],
            [    604,    "RBBB 1 bar",    4],
            [    604,    "UV pulse",    1],
            [    608,    "UV pulse slow",    2],
            [    608,    "Autogen UV Strobe",    1],
            [    610,    "Autogen bassline top",    2],
            [    610,    "Autogen bassline bottom",    2],
            [    612,    "Autogen bassline bottom",    2],
            [    612,    "Rainbow bad",    2],
            [    614,    "Autogen bassline bottom",    2],
            [    614,    "hooked wandering bottom",    16],
            [    630,    "Ghosts riser",    4],
            [    630,    "rainbow good slow top",    16],
            [    646,    "UV pulse slow",    2],
            [    646,    "Autogen bassline bottom",    2],
            [    648,    "Rainbow bad",    2],
            [    648,    "Ghosts riser",    4],
            [    652,    "Autogen bassline sidechain bottom",    2],
            [    652,    "Autogen UV Strobe",    1],
            [    654,    "UV pulse",    1],
            [    654,    "hooked wandering top",    16],
            [    670,    "Autogen bassline top",    2],
            [    670,    "UV pulse",    1],
            [    672,    "Autogen bassline top",    2],
            [    672,    "Ghosts riser",    4],
            [    676,    "rainbow good slow top",    16],
            [    676,    "UV pulse slow",    2],
            [    692,    "Autogen bassline top",    2],
            [    692,    "rainbow good slow top",    16],
            [    708,    "rainbow good slow top",    16],
            [    708,    "rainbow good slow top",    16],
            [    724,    "UV pulse slow",    2],
            [    724,    "Autogen bassline top",    2],
            [    726,    "Ghosts riser",    4],
            [    726,    "Autogen bassline top",    2],
            [    730,    "hooked wandering top",    16],
            [    730,    "Autogen bassline sidechain bottom",    2],
            [    746,    "Ghosts riser",    4],
            [    746,    "hooked wandering top",    16],
            [    762,    "Autogen Strobe",    1],
            [    762,    "Autogen Strobe",    1],
            [    763,    "hooked wandering bottom",    16],
            [    763,    "hooked wandering bottom",    16]
        ],
        "bpm": 125,
        "delay_lights": 0.0246,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/Neon Pattern Drum.ogg"
    }
}