effects = {
    "g_Notion - Hooked": {
        "beats": [
            [    1,    "g_UV pulse",    4],
            [    5,    "g_UV pulse",    2],
            [    7,    "g_UV pulse",    1],
            [    8,    "g_pulse top brown",    16],
            [    8,    "g_UV",    16],
            [    24,    "g_cyan top pulse",    16],
            [    24,    "g_UV",    16],
            [    40,    "g_UV pulse",    4],
            [    44,    "g_UV pulse",    4],
            [    48,    "g_UV pulse",    4],
            [    52,    "g_UV pulse",    1],
            [    53,    "g_pulse top brown",    16],
            [    53,    "g_UV",    16],
            [    69,    "g_pulse top brown",    16],
            [    69,    "g_UV",    16],
            [    85,    "g_solid top cycle",    16],
            [    85,    "g_UV",    16],
            [    101,    "g_solid top cycle",    16],
            [    101,    "g_UV",    16],
            [    117,    "g_pulse top brown",    16],
            [    117,    "g_UV",    16],
            [    133,    "g_solid top cycle",    16],
            [    133,    "g_UV",    16],
            [    149,    "g_UV pulse",    2],
            [    151,    "g_UV pulse",    4],
            [    155,    "g_UV pulse",    4],
            [    159,    "g_UV pulse",    4],
            [    163,    "g_UV pulse",    4],
            [    167,    "g_UV pulse",    4],
            [    171,    "g_UV pulse",    4],
            [    175,    "g_UV pulse",    4],
            [    179,    "g_UV pulse",    4],
            [    183,    "g_UV pulse",    4],
            [    187,    "g_UV pulse",    4],
            [    191,    "g_UV pulse",    4],
            [    195,    "g_UV pulse",    4],
            [    199,    "g_UV pulse",    4],
            [    203,    "g_UV pulse",    4],
            [    207,    "g_UV pulse",    4],
            [    211,    "g_UV pulse",    4],
            [    215,    "g_UV pulse",    4],
            [    219,    "g_UV pulse",    4],
            [    223,    "g_UV pulse",    4],
            [    227,    "g_UV pulse",    4],
            [    231,    "g_UV pulse",    4],
            [    235,    "g_UV pulse",    4],
            [    239,    "g_UV pulse",    4],
            [    243,    "g_UV pulse",    4],
            [    247,    "g_UV pulse",    4],
            [    251,    "g_UV pulse",    4],
            [    255,    "g_UV pulse",    4],
            [    259,    "g_UV pulse",    4],
            [    263,    "g_UV pulse",    4],
            [    267,    "g_UV pulse",    4],
            [    271,    "g_UV pulse",    4],
            [    275,    "g_UV pulse",    4],
            [    279,    "g_UV pulse",    4],
            [    283,    "g_UV pulse",    2],
            [    285,    "g_UV pulse",    1],
            [    286,    "g_cyan top pulse",    16],
            [    286,    "g_pulse bottom brown",    16],
            [    302,    "g_pulse top brown",    16],
            [    302,    "g_green sidechain bottom pulse",    16],
            [    318,    "g_solid top cycle",    16],
            [    318,    "g_purple green bottom pulse",    16],
            [    334,    "g_cyan top pulse",    16],
            [    334,    "g_pulse bottom brown",    16],
            [    350,    "g_solid top cycle",    16],
            [    350,    "g_pulse bottom brown",    16],
            [    366,    "g_cyan top pulse",    16],
            [    366,    "g_purple green bottom pulse",    16],
            [    382,    "g_pulse top brown",    16],
            [    382,    "g_pulse bottom brown",    16],
            [    398,    "g_solid top cycle",    16],
            [    398,    "g_pulse bottom brown",    16],
            [    414,    "g_solid top cycle",    16],
            [    414,    "g_purple green bottom pulse",    16],
            [    430,    "g_pulse top brown",    16],
            [    430,    "g_green sidechain bottom pulse",    16],
            [    446,    "g_cyan top pulse",    16],
            [    446,    "g_purple green bottom pulse",    16],
            [    462,    "g_solid top cycle",    16],
            [    462,    "g_purple green bottom pulse",    16],
            [    478,    "g_pulse top brown",    16],
            [    478,    "g_pulse bottom brown",    16],
            [    494,    "g_solid top cycle",    16],
            [    494,    "g_pulse bottom brown",    16],
            [    510,    "g_UV pulse",    4],
            [    514,    "g_UV pulse",    4],
            [    518,    "g_cyan top pulse",    16],
            [    518,    "g_purple green bottom pulse",    16],
            [    534,    "g_pulse top brown",    16],
            [    534,    "g_green sidechain bottom pulse",    16],
            [    550,    "g_cyan top pulse",    16],
            [    550,    "g_pulse bottom brown",    16],
            [    566,    "g_solid top cycle",    16],
            [    566,    "g_pulse bottom brown",    16],
            [    582,    "g_solid top cycle",    16],
            [    582,    "g_solid bottom cycle",    16],
            [    598,    "g_solid top cycle",    16],
            [    598,    "g_solid bottom cycle",    16],
            [    614,    "g_solid top cycle",    16],
            [    614,    "g_pulse bottom brown",    16],
            [    630,    "g_pulse top brown",    16],
            [    630,    "g_purple green bottom pulse",    16],
            [    646,    "g_solid top cycle",    16],
            [    646,    "g_solid bottom cycle",    16],
            [    662,    "g_cyan top pulse",    16],
            [    662,    "g_solid bottom cycle",    16],
            [    678,    "g_solid top cycle",    16],
            [    678,    "g_green sidechain bottom pulse",    16],
            [    694,    "g_solid top cycle",    16],
            [    694,    "g_purple green bottom pulse",    16],
            [    710,    "g_cyan top pulse",    16],
            [    710,    "g_solid bottom cycle",    16],
            [    726,    "g_solid top cycle",    16],
            [    726,    "g_green sidechain bottom pulse",    16],
            [    742,    "g_pulse top brown",    16],
            [    742,    "g_pulse bottom brown",    16],
            [    758,    "g_UV pulse",    4],
            [    762,    "g_UV pulse",    4],
            [    766,    "g_UV pulse",    4],
            [    770,    "RGB Flash",    1],
            [    771,    "g_pulse top brown",    16],
            [    787,    "g_pulse top brown",    16],
            [    803,    "g_cyan top pulse",    16],
            [    819,    "g_solid top cycle",    16],
            [    835,    "g_solid top cycle",    16],
            [    851,    "g_cyan top pulse",    16],
            [    867,    "g_pulse top brown",    16],
            [    883,    "g_cyan top pulse",    16],
            [    899,    "g_cyan top pulse",    16],
            [    915,    "g_pulse top brown",    16],
            [    931,    "g_solid top cycle",    16],
            [    947,    "g_solid top cycle",    16],
            [    963,    "g_cyan top pulse",    16],
            [    979,    "g_cyan top pulse",    16],
            [    995,    "g_cyan top pulse",    16],
            [    1011,    "g_cyan top pulse",    16],
            [    1027,    "g_solid top cycle",    16],
            [    1043,    "g_solid top cycle",    16],
            [    1059,    "g_UV pulse",    1],
            [    1060,    "g_pulse bottom brown",    16],
            [    1076,    "g_green sidechain bottom pulse",    16],
            [    1092,    "g_green sidechain bottom pulse",    16],
            [    1108,    "g_green sidechain bottom pulse",    16],
            [    1124,    "g_pulse bottom brown",    16],
            [    1140,    "g_solid bottom cycle",    16],
            [    1156,    "g_purple green bottom pulse",    16],
            [    1172,    "g_pulse bottom brown",    16],
            [    1188,    "g_pulse bottom brown",    16],
            [    1204,    "g_pulse bottom brown",    16],
            [    1220,    "g_pulse bottom brown",    16],
            [    1236,    "g_purple green bottom pulse",    16],
            [    1252,    "g_solid bottom cycle",    16],
            [    1268,    "g_purple green bottom pulse",    16],
            [    1284,    "g_purple green bottom pulse",    16],
            [    1300,    "g_pulse bottom brown",    16],
            [    1316,    "g_green sidechain bottom pulse",    16],
            [    1332,    "g_purple green bottom pulse",    16],
            [    1348,    "g_solid bottom cycle",    16],
            [    1364,    "g_solid bottom cycle",    16],
            [    1380,    "g_UV pulse",    4],
            [    1384,    "g_UV pulse",    4],
            [    1388,    "g_UV pulse",    4],
            [    1392,    "g_UV pulse",    4],
            [    1396,    "g_UV pulse",    4],
            [    1400,    "g_UV pulse",    4],
            [    1404,    "g_UV pulse",    4],
            [    1408,    "g_UV pulse",    4],
            [    1412,    "g_UV pulse",    4],
            [    1416,    "g_UV pulse",    4],
            [    1420,    "g_UV pulse",    4],
            [    1424,    "g_UV pulse",    4],
            [    1428,    "g_UV pulse",    4],
            [    1432,    "g_UV pulse",    4],
            [    1436,    "g_UV pulse",    4],
            [    1440,    "g_UV pulse",    4],
            [    1444,    "g_UV pulse",    4],
            [    1448,    "g_UV pulse",    4],
            [    1452,    "g_UV pulse",    4],
            [    1456,    "g_UV pulse",    4],
            [    1460,    "g_UV pulse",    4],
            [    1464,    "g_UV pulse",    4],
            [    1468,    "g_UV pulse",    4],
            [    1472,    "g_UV pulse",    4],
            [    1476,    "g_UV pulse",    4],
            [    1480,    "g_UV pulse",    4],
            [    1484,    "g_UV pulse",    4],
            [    1488,    "g_UV pulse",    4],
            [    1492,    "g_UV pulse",    4],
            [    1496,    "g_UV pulse",    4],
            [    1500,    "g_UV pulse",    4],
            [    1504,    "g_UV pulse",    4],
            [    1508,    "g_UV pulse",    4],
            [    1512,    "g_UV pulse",    4],
            [    1516,    "g_UV pulse",    4],
            [    1520,    "g_UV pulse",    4],
            [    1524,    "g_UV pulse",    4],
            [    1528,    "g_UV pulse",    4],
            [    1532,    "g_UV pulse",    4],
            [    1536,    "g_UV pulse",    4],
            [    1540,    "g_UV pulse",    4],
            [    1544,    "g_UV pulse",    4],
            [    1548,    "g_UV pulse",    4],
            [    1552,    "g_UV pulse",    4],
            [    1556,    "g_UV pulse",    4],
            [    1560,    "g_UV pulse",    4],
            [    1564,    "g_UV pulse",    4],
            [    1568,    "g_UV pulse",    4],
            [    1572,    "g_UV pulse",    4],
            [    1576,    "g_UV pulse",    4],
            [    1580,    "g_UV pulse",    4],
            [    1584,    "g_UV pulse",    4],
            [    1588,    "g_UV pulse",    4],
            [    1592,    "g_UV pulse",    4],
            [    1596,    "g_UV pulse",    4],
            [    1600,    "g_UV pulse",    4],
            [    1604,    "g_UV pulse",    4],
            [    1608,    "g_UV pulse",    4],
            [    1612,    "g_UV pulse",    4],
            [    1616,    "g_UV pulse",    4],
            [    1620,    "g_UV pulse",    4],
            [    1624,    "g_UV pulse",    4],
            [    1628,    "g_UV pulse",    4],
            [    1632,    "g_UV pulse",    4],
            [    1636,    "g_UV pulse",    4],
            [    1640,    "g_UV pulse",    4],
            [    1644,    "g_UV pulse",    4],
            [    1648,    "g_UV pulse",    4],
            [    1652,    "g_UV pulse",    4],
            [    1656,    "g_UV pulse",    4],
            [    1660,    "g_UV pulse",    4],
            [    1664,    "g_UV pulse",    4],
            [    1668,    "g_UV pulse",    4],
            [    1672,    "g_UV pulse",    4],
            [    1676,    "g_UV pulse",    4],
            [    1680,    "g_UV pulse",    4],
            [    1684,    "g_UV pulse",    4],
            [    1688,    "g_UV pulse",    4],
            [    1692,    "g_UV pulse",    4],
            [    1696,    "g_UV pulse",    4],
            [    1700,    "g_UV pulse",    4],
            [    1704,    "g_UV pulse",    4],
            [    1708,    "g_UV pulse",    4],
            [    1712,    "g_UV pulse",    4],
            [    1716,    "g_UV pulse",    4],
            [    1720,    "g_UV pulse",    4],
            [    1724,    "g_UV pulse",    4],
            [    1728,    "g_UV pulse",    4],
            [    1732,    "g_UV pulse",    4],
            [    1736,    "g_UV pulse",    4],
            [    1740,    "g_UV pulse",    4],
            [    1744,    "g_UV pulse",    4],
            [    1748,    "g_UV pulse",    4],
            [    1752,    "g_UV pulse",    4],
            [    1756,    "g_UV pulse",    4],
            [    1760,    "g_UV pulse",    4],
            [    1764,    "g_UV pulse",    4],
            [    1768,    "g_UV pulse",    4],
            [    1772,    "g_UV pulse",    4],
            [    1776,    "g_UV pulse",    4],
            [    1780,    "g_UV pulse",    4],
            [    1784,    "g_UV pulse",    4],
            [    1788,    "g_UV pulse",    4],
            [    1792,    "g_UV pulse",    4],
            [    1796,    "g_UV pulse",    4],
            [    1800,    "g_UV pulse",    4],
            [    1804,    "g_UV pulse",    4],
            [    1808,    "g_UV pulse",    4],
            [    1812,    "g_UV pulse",    4],
            [    1816,    "g_UV pulse",    4],
            [    1820,    "g_UV pulse",    4],
            [    1824,    "g_UV pulse",    4],
            [    1828,    "g_pulse top brown",    16],
            [    1828,    "g_UV",    16],
            [    1844,    "g_cyan top pulse",    16],
            [    1844,    "g_UV",    16],
            [    1860,    "g_pulse top brown",    16],
            [    1860,    "g_UV",    16],
            [    1876,    "g_solid top cycle",    16],
            [    1876,    "g_UV",    16],
            [    1892,    "g_pulse top brown",    16],
            [    1892,    "g_UV",    16],
            [    1908,    "g_solid top cycle",    16],
            [    1908,    "g_UV",    16],
            [    1924,    "g_pulse top brown",    16],
            [    1924,    "g_UV",    16],
            [    1940,    "g_cyan top pulse",    16],
            [    1940,    "g_UV",    16],
            [    1956,    "g_cyan top pulse",    16],
            [    1956,    "g_UV",    16],
            [    1972,    "g_cyan top pulse",    16],
            [    1972,    "g_UV",    16],
            [    1988,    "g_pulse top brown",    16],
            [    1988,    "g_UV",    16],
            [    2004,    "g_pulse top brown",    16],
            [    2004,    "g_UV",    16],
            [    2020,    "g_cyan top pulse",    16],
            [    2020,    "g_UV",    16],
            [    2036,    "g_cyan top pulse",    16],
            [    2036,    "g_UV",    16],
            [    2052,    "g_cyan top pulse",    16],
            [    2052,    "g_UV",    16],
            [    2068,    "g_solid top cycle",    16],
            [    2068,    "g_UV",    16],
            [    2084,    "g_pulse top brown",    16],
            [    2084,    "g_UV",    16],
            [    2100,    "g_pulse top brown",    16],
            [    2100,    "g_UV",    16],
            [    2116,    "g_pulse top brown",    16],
            [    2116,    "g_UV",    16],
            [    2132,    "g_solid top cycle",    16],
            [    2132,    "g_UV",    16],
            [    2148,    "g_pulse top brown",    16],
            [    2148,    "g_UV",    16],
            [    2164,    "g_solid top cycle",    16],
            [    2164,    "g_UV",    16],
            [    2180,    "g_pulse top brown",    16],
            [    2180,    "g_UV",    16],
            [    2196,    "g_pulse top brown",    16],
            [    2196,    "g_UV",    16],
            [    2212,    "g_pulse top brown",    16],
            [    2212,    "g_UV",    16],
            [    2228,    "g_pulse top brown",    16],
            [    2228,    "g_UV",    16],
            [    2244,    "g_solid top cycle",    16],
            [    2244,    "g_UV",    16],
            [    2260,    "g_UV pulse",    4],
            [    2264,    "g_UV pulse",    4]
        ],
        "bpm": 128,
        "delay_lights": 0.024050000000000002,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/Notion - Hooked.ogg",
        "was_autogenerated": True
    }
}