effects = {
    "g_Not Butter": {
        "beats": [
            [    1,    "hooked wandering bottom",    16],
            [    1,    "Autogen UV Strobe",    1],
            [    17,    "Autogen bassline top",    2],
            [    17,    "Autogen UV Strobe",    1],
            [    19,    "Rainbow bad",    2],
            [    19,    "Autogen bassline top",    2],
            [    21,    "UV pulse",    1],
            [    21,    "hooked wandering bottom",    16],
            [    37,    "Autogen bassline sidechain bottom",    2],
            [    37,    "Autogen UV Strobe",    1],
            [    39,    "Autogen UV Strobe",    1],
            [    39,    "Rainbow bad",    2],
            [    41,    "Autogen bassline top",    2],
            [    41,    "Autogen bassline sidechain bottom",    2],
            [    43,    "rainbow good slow top",    16],
            [    43,    "Autogen bassline sidechain bottom",    2],
            [    59,    "Autogen bassline sidechain bottom",    2],
            [    59,    "Autogen UV Strobe",    1],
            [    61,    "rainbow good slow top",    16],
            [    61,    "Autogen bassline bottom",    2],
            [    77,    "Autogen bassline bottom",    2],
            [    77,    "hooked wandering top",    16],
            [    93,    "Autogen bassline bottom",    2],
            [    93,    "Ghosts riser",    4],
            [    97,    "UV pulse slow",    2],
            [    97,    "RBBB 1 bar",    4],
            [    101,    "Autogen bassline top",    2],
            [    101,    "Autogen Strobe",    1],
            [    103,    "RBBB 1 bar",    4],
            [    103,    "rainbow good slow top",    16],
            [    119,    "Ghosts riser",    4],
            [    119,    "Autogen bassline bottom",    2],
            [    123,    "hooked wandering top",    16],
            [    123,    "Autogen bassline top",    2],
            [    139,    "Ghosts riser",    4],
            [    139,    "rainbow good slow top",    16],
            [    155,    "Ghosts riser",    4],
            [    155,    "Autogen Strobe",    1],
            [    159,    "Rainbow bad",    2],
            [    159,    "rainbow good slow top",    16],
            [    175,    "Ghosts riser",    4],
            [    175,    "hooked wandering top",    16],
            [    191,    "Autogen bassline sidechain bottom",    2],
            [    191,    "hooked wandering bottom",    16],
            [    207,    "Autogen bassline bottom",    2],
            [    207,    "hooked wandering bottom",    16],
            [    223,    "UV pulse",    1],
            [    223,    "Autogen Strobe",    1],
            [    224,    "Rainbow bad",    2],
            [    224,    "rainbow good slow top",    16],
            [    240,    "Autogen Strobe",    1],
            [    240,    "RBBB 1 bar",    4],
            [    244,    "Ghosts riser",    4],
            [    244,    "RBBB 1 bar",    4],
            [    248,    "Autogen bassline sidechain bottom",    2],
            [    248,    "hooked wandering bottom",    16],
            [    264,    "hooked wandering top",    16],
            [    264,    "Autogen bassline sidechain bottom",    2],
            [    280,    "Autogen bassline top",    2],
            [    280,    "Autogen bassline top",    2],
            [    282,    "UV pulse slow",    2],
            [    282,    "Autogen bassline bottom",    2],
            [    284,    "rainbow good slow top",    16],
            [    284,    "Rainbow bad",    2],
            [    300,    "Autogen Strobe",    1],
            [    300,    "rainbow good slow top",    16],
            [    316,    "Autogen bassline sidechain bottom",    2],
            [    316,    "RBBB 1 bar",    4],
            [    320,    "Autogen UV Strobe",    1],
            [    320,    "rainbow good slow top",    16],
            [    336,    "rainbow good slow top",    16],
            [    336,    "UV pulse",    1],
            [    352,    "Autogen bassline top",    2],
            [    352,    "Rainbow bad",    2],
            [    354,    "Autogen bassline top",    2],
            [    354,    "Autogen bassline sidechain bottom",    2],
            [    356,    "Autogen bassline top",    2],
            [    356,    "rainbow good slow top",    16],
            [    372,    "Rainbow bad",    2],
            [    372,    "Rainbow bad",    2],
            [    374,    "RBBB 1 bar",    4],
            [    374,    "Autogen bassline top",    2],
            [    378,    "Rainbow bad",    2],
            [    378,    "hooked wandering top",    16],
            [    394,    "Ghosts riser",    4],
            [    394,    "hooked wandering top",    16],
            [    410,    "Rainbow bad",    2],
            [    410,    "hooked wandering top",    16],
            [    426,    "UV pulse slow",    2],
            [    426,    "RBBB 1 bar",    4],
            [    430,    "RBBB 1 bar",    4],
            [    430,    "Autogen bassline top",    2],
            [    434,    "Autogen bassline sidechain bottom",    2],
            [    434,    "RBBB 1 bar",    4],
            [    438,    "hooked wandering bottom",    16],
            [    438,    "Autogen bassline top",    2]
        ],
        "bpm": 112,
        "delay_lights": 0.1375,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/Not Butter.ogg"
    }
}