effects = {
    "g_Notion - Hooked": {
        "beats": [
            [    1,    "hooked wandering bottom",    16],
            [    1,    "rainbow good slow top",    16],
            [    17,    "Rainbow bad",    2],
            [    17,    "Rainbow bad",    2],
            [    19,    "hooked wandering top",    16],
            [    19,    "Autogen bassline bottom",    2],
            [    35,    "hooked wandering bottom",    16],
            [    35,    "RBBB 1 bar",    4],
            [    51,    "Rainbow bad",    2],
            [    51,    "Autogen Strobe",    1],
            [    53,    "hooked wandering bottom",    16],
            [    53,    "Autogen bassline top",    2],
            [    69,    "Ghosts riser",    4],
            [    69,    "rainbow good slow top",    16],
            [    85,    "Autogen bassline top",    2],
            [    85,    "rainbow good slow top",    16],
            [    101,    "Autogen UV Strobe",    1],
            [    101,    "rainbow good slow top",    16],
            [    117,    "Rainbow bad",    2],
            [    117,    "UV pulse",    1],
            [    119,    "Autogen bassline top",    2],
            [    119,    "UV pulse",    1],
            [    121,    "Autogen UV Strobe",    1],
            [    121,    "UV pulse slow",    2],
            [    123,    "RBBB 1 bar",    4],
            [    123,    "Autogen UV Strobe",    1],
            [    127,    "rainbow good slow top",    16],
            [    127,    "Ghosts riser",    4],
            [    143,    "rainbow good slow top",    16],
            [    143,    "Rainbow bad",    2],
            [    159,    "Rainbow bad",    2],
            [    159,    "hooked wandering bottom",    16],
            [    175,    "Autogen bassline top",    2],
            [    175,    "rainbow good slow top",    16],
            [    191,    "Ghosts riser",    4],
            [    191,    "rainbow good slow top",    16],
            [    207,    "Autogen bassline bottom",    2],
            [    207,    "rainbow good slow top",    16],
            [    223,    "Ghosts riser",    4],
            [    223,    "rainbow good slow top",    16],
            [    239,    "UV pulse",    1],
            [    239,    "UV pulse",    1],
            [    240,    "Autogen bassline sidechain bottom",    2],
            [    240,    "Rainbow bad",    2],
            [    242,    "rainbow good slow top",    16],
            [    242,    "Ghosts riser",    4],
            [    258,    "Autogen bassline sidechain bottom",    2],
            [    258,    "Autogen bassline bottom",    2],
            [    260,    "Autogen bassline sidechain bottom",    2],
            [    260,    "Autogen bassline sidechain bottom",    2],
            [    262,    "RBBB 1 bar",    4],
            [    262,    "Rainbow bad",    2],
            [    266,    "Autogen bassline top",    2],
            [    266,    "RBBB 1 bar",    4],
            [    270,    "Ghosts riser",    4],
            [    270,    "hooked wandering top",    16],
            [    286,    "Autogen Strobe",    1],
            [    286,    "Ghosts riser",    4],
            [    290,    "Rainbow bad",    2],
            [    290,    "Autogen bassline sidechain bottom",    2],
            [    292,    "Autogen bassline sidechain bottom",    2],
            [    292,    "Autogen bassline bottom",    2],
            [    294,    "Rainbow bad",    2],
            [    294,    "UV pulse slow",    2],
            [    296,    "hooked wandering top",    16],
            [    296,    "Rainbow bad",    2],
            [    312,    "Autogen bassline bottom",    2],
            [    312,    "hooked wandering top",    16],
            [    328,    "RBBB 1 bar",    4],
            [    328,    "Rainbow bad",    2],
            [    332,    "Autogen bassline sidechain bottom",    2],
            [    332,    "Autogen Strobe",    1],
            [    334,    "Autogen bassline top",    2],
            [    334,    "Autogen UV Strobe",    1],
            [    336,    "Autogen bassline bottom",    2],
            [    336,    "hooked wandering bottom",    16],
            [    352,    "rainbow good slow top",    16],
            [    352,    "RBBB 1 bar",    4],
            [    368,    "Ghosts riser",    4],
            [    368,    "hooked wandering top",    16],
            [    384,    "Autogen bassline sidechain bottom",    2],
            [    384,    "UV pulse slow",    2],
            [    386,    "UV pulse",    1],
            [    386,    "Autogen bassline bottom",    2],
            [    388,    "hooked wandering top",    16],
            [    388,    "hooked wandering bottom",    16],
            [    404,    "UV pulse",    1],
            [    404,    "Autogen UV Strobe",    1],
            [    405,    "UV pulse slow",    2],
            [    405,    "RBBB 1 bar",    4],
            [    409,    "Autogen UV Strobe",    1],
            [    409,    "Autogen Strobe",    1],
            [    410,    "UV pulse",    1],
            [    410,    "Autogen Strobe",    1],
            [    411,    "UV pulse slow",    2],
            [    411,    "Autogen UV Strobe",    1],
            [    413,    "Ghosts riser",    4],
            [    413,    "Ghosts riser",    4],
            [    417,    "UV pulse slow",    2],
            [    417,    "hooked wandering top",    16],
            [    433,    "UV pulse",    1],
            [    433,    "hooked wandering top",    16]
        ],
        "bpm": 128,
        "delay_lights": 0.024050000000000002,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/Notion - Hooked.ogg"
    }
}