effects = {
    "g_Not Butter": {
        "beats": [
            [    1,    "rainbow good slow top",    16],
            [    1,    "Autogen bassline sidechain bottom",    2],
            [    17,    "UV pulse slow",    2],
            [    17,    "hooked wandering bottom",    16],
            [    33,    "Autogen UV Strobe",    1],
            [    33,    "Autogen bassline top",    2],
            [    35,    "UV pulse",    1],
            [    35,    "Ghosts riser",    4],
            [    39,    "UV pulse slow",    2],
            [    39,    "rainbow good slow top",    16],
            [    55,    "hooked wandering bottom",    16],
            [    55,    "Rainbow bad",    2],
            [    71,    "Autogen Strobe",    1],
            [    71,    "Ghosts riser",    4],
            [    75,    "Autogen Strobe",    1],
            [    75,    "hooked wandering bottom",    16],
            [    91,    "Autogen UV Strobe",    1],
            [    91,    "Autogen bassline bottom",    2],
            [    93,    "RBBB 1 bar",    4],
            [    93,    "UV pulse slow",    2],
            [    97,    "RBBB 1 bar",    4],
            [    97,    "RBBB 1 bar",    4],
            [    101,    "Rainbow bad",    2],
            [    101,    "Autogen UV Strobe",    1],
            [    103,    "Autogen bassline bottom",    2],
            [    103,    "RBBB 1 bar",    4],
            [    107,    "Autogen bassline sidechain bottom",    2],
            [    107,    "Rainbow bad",    2],
            [    109,    "Autogen bassline bottom",    2],
            [    109,    "Autogen bassline sidechain bottom",    2],
            [    111,    "RBBB 1 bar",    4],
            [    111,    "UV pulse",    1],
            [    115,    "UV pulse",    1],
            [    115,    "hooked wandering top",    16],
            [    131,    "hooked wandering top",    16],
            [    131,    "RBBB 1 bar",    4],
            [    147,    "rainbow good slow top",    16],
            [    147,    "UV pulse slow",    2],
            [    163,    "Autogen bassline bottom",    2],
            [    163,    "RBBB 1 bar",    4],
            [    167,    "hooked wandering bottom",    16],
            [    167,    "Autogen Strobe",    1],
            [    183,    "Autogen bassline bottom",    2],
            [    183,    "UV pulse",    1],
            [    185,    "Autogen bassline bottom",    2],
            [    185,    "RBBB 1 bar",    4],
            [    189,    "hooked wandering top",    16],
            [    189,    "Autogen UV Strobe",    1],
            [    205,    "Ghosts riser",    4],
            [    205,    "Autogen bassline sidechain bottom",    2],
            [    209,    "Autogen bassline top",    2],
            [    209,    "RBBB 1 bar",    4],
            [    213,    "hooked wandering bottom",    16],
            [    213,    "hooked wandering bottom",    16],
            [    229,    "Autogen UV Strobe",    1],
            [    229,    "Rainbow bad",    2],
            [    231,    "UV pulse",    1],
            [    231,    "Autogen Strobe",    1],
            [    232,    "Autogen bassline top",    2],
            [    232,    "Autogen bassline sidechain bottom",    2],
            [    234,    "Autogen UV Strobe",    1],
            [    234,    "Autogen bassline sidechain bottom",    2],
            [    236,    "RBBB 1 bar",    4],
            [    236,    "Autogen Strobe",    1],
            [    240,    "RBBB 1 bar",    4],
            [    240,    "Autogen bassline sidechain bottom",    2],
            [    244,    "hooked wandering top",    16],
            [    244,    "Autogen Strobe",    1],
            [    260,    "Autogen bassline top",    2],
            [    260,    "Autogen bassline sidechain bottom",    2],
            [    262,    "hooked wandering top",    16],
            [    262,    "Autogen bassline sidechain bottom",    2],
            [    278,    "Autogen bassline sidechain bottom",    2],
            [    278,    "UV pulse slow",    2],
            [    280,    "Autogen Strobe",    1],
            [    280,    "Autogen bassline bottom",    2],
            [    282,    "Autogen bassline sidechain bottom",    2],
            [    282,    "RBBB 1 bar",    4],
            [    286,    "Autogen Strobe",    1],
            [    286,    "Autogen UV Strobe",    1],
            [    287,    "rainbow good slow top",    16],
            [    287,    "Autogen Strobe",    1],
            [    303,    "Autogen bassline top",    2],
            [    303,    "rainbow good slow top",    16],
            [    319,    "hooked wandering bottom",    16],
            [    319,    "Autogen UV Strobe",    1],
            [    335,    "Autogen bassline top",    2],
            [    335,    "RBBB 1 bar",    4],
            [    339,    "Autogen UV Strobe",    1],
            [    339,    "rainbow good slow top",    16],
            [    355,    "UV pulse",    1],
            [    355,    "hooked wandering top",    16],
            [    371,    "Autogen UV Strobe",    1],
            [    371,    "Autogen bassline sidechain bottom",    2],
            [    373,    "Rainbow bad",    2],
            [    373,    "hooked wandering top",    16],
            [    389,    "Autogen bassline sidechain bottom",    2],
            [    389,    "RBBB 1 bar",    4],
            [    393,    "Autogen bassline top",    2],
            [    393,    "hooked wandering bottom",    16],
            [    409,    "Rainbow bad",    2],
            [    409,    "UV pulse slow",    2],
            [    411,    "RBBB 1 bar",    4],
            [    411,    "UV pulse slow",    2],
            [    415,    "hooked wandering bottom",    16],
            [    415,    "Autogen Strobe",    1],
            [    431,    "RBBB 1 bar",    4],
            [    431,    "hooked wandering bottom",    16],
            [    447,    "rainbow good slow top",    16],
            [    447,    "UV pulse",    1]
        ],
        "bpm": 112,
        "delay_lights": 0.1375,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/Not Butter.ogg"
    }
}