effects = {
    "g_Porter Robinson - Musician (Official Music Video)": {
        "beats": [
            [    1,    "hooked wandering bottom",    16],
            [    1,    "Autogen bassline bottom",    2],
            [    17,    "RBBB 1 bar",    4],
            [    17,    "Autogen Strobe",    1],
            [    21,    "hooked wandering bottom",    16],
            [    21,    "Autogen Strobe",    1],
            [    37,    "Autogen bassline sidechain bottom",    2],
            [    37,    "Autogen bassline sidechain bottom",    2],
            [    39,    "Autogen bassline bottom",    2],
            [    39,    "Ghosts riser",    4],
            [    43,    "rainbow good slow top",    16],
            [    43,    "Autogen bassline sidechain bottom",    2],
            [    59,    "UV pulse slow",    2],
            [    59,    "hooked wandering bottom",    16],
            [    75,    "Ghosts riser",    4],
            [    75,    "Autogen UV Strobe",    1],
            [    79,    "Autogen Strobe",    1],
            [    79,    "Autogen Strobe",    1],
            [    80,    "Autogen bassline bottom",    2],
            [    80,    "hooked wandering top",    16],
            [    96,    "Ghosts riser",    4],
            [    96,    "UV pulse",    1],
            [    100,    "UV pulse slow",    2],
            [    100,    "Autogen bassline bottom",    2],
            [    102,    "Autogen bassline top",    2],
            [    102,    "UV pulse",    1],
            [    104,    "hooked wandering top",    16],
            [    104,    "Autogen Strobe",    1],
            [    120,    "Autogen bassline bottom",    2],
            [    120,    "Autogen bassline top",    2],
            [    122,    "Autogen Strobe",    1],
            [    122,    "rainbow good slow top",    16],
            [    138,    "Ghosts riser",    4],
            [    138,    "Rainbow bad",    2],
            [    142,    "RBBB 1 bar",    4],
            [    142,    "RBBB 1 bar",    4],
            [    146,    "hooked wandering top",    16],
            [    146,    "Autogen bassline sidechain bottom",    2],
            [    162,    "Ghosts riser",    4],
            [    162,    "hooked wandering bottom",    16],
            [    178,    "hooked wandering bottom",    16],
            [    178,    "hooked wandering top",    16],
            [    194,    "Rainbow bad",    2],
            [    194,    "Autogen bassline sidechain bottom",    2],
            [    196,    "hooked wandering top",    16],
            [    196,    "Autogen Strobe",    1],
            [    212,    "hooked wandering bottom",    16],
            [    212,    "Rainbow bad",    2],
            [    228,    "RBBB 1 bar",    4],
            [    228,    "Autogen bassline bottom",    2],
            [    232,    "UV pulse slow",    2],
            [    232,    "UV pulse slow",    2],
            [    234,    "Autogen bassline bottom",    2],
            [    234,    "Ghosts riser",    4],
            [    238,    "Autogen bassline top",    2],
            [    238,    "RBBB 1 bar",    4],
            [    242,    "Autogen bassline bottom",    2],
            [    242,    "Autogen UV Strobe",    1],
            [    244,    "RBBB 1 bar",    4],
            [    244,    "Rainbow bad",    2],
            [    248,    "rainbow good slow top",    16],
            [    248,    "Autogen bassline bottom",    2],
            [    264,    "hooked wandering bottom",    16],
            [    264,    "Autogen Strobe",    1],
            [    280,    "Autogen Strobe",    1],
            [    280,    "rainbow good slow top",    16],
            [    296,    "hooked wandering top",    16],
            [    296,    "UV pulse slow",    2],
            [    312,    "Autogen UV Strobe",    1],
            [    312,    "UV pulse",    1],
            [    313,    "UV pulse slow",    2],
            [    313,    "hooked wandering bottom",    16],
            [    329,    "Rainbow bad",    2],
            [    329,    "Autogen Strobe",    1],
            [    331,    "Rainbow bad",    2],
            [    331,    "Ghosts riser",    4],
            [    335,    "Autogen bassline top",    2],
            [    335,    "UV pulse",    1],
            [    337,    "Autogen Strobe",    1],
            [    337,    "Autogen bassline sidechain bottom",    2],
            [    339,    "Rainbow bad",    2],
            [    339,    "rainbow good slow top",    16],
            [    355,    "rainbow good slow top",    16],
            [    355,    "Autogen bassline top",    2],
            [    371,    "Autogen bassline sidechain bottom",    2],
            [    371,    "Autogen bassline top",    2],
            [    373,    "Autogen bassline sidechain bottom",    2],
            [    373,    "RBBB 1 bar",    4],
            [    377,    "hooked wandering top",    16],
            [    377,    "rainbow good slow top",    16],
            [    393,    "Ghosts riser",    4],
            [    393,    "hooked wandering top",    16],
            [    409,    "Autogen Strobe",    1],
            [    409,    "hooked wandering bottom",    16],
            [    425,    "Rainbow bad",    2],
            [    425,    "Autogen bassline sidechain bottom",    2],
            [    427,    "UV pulse",    1],
            [    427,    "UV pulse",    1],
            [    428,    "Autogen bassline sidechain bottom",    2],
            [    428,    "Autogen bassline sidechain bottom",    2],
            [    430,    "Autogen bassline sidechain bottom",    2],
            [    430,    "Rainbow bad",    2],
            [    432,    "rainbow good slow top",    16],
            [    432,    "Ghosts riser",    4],
            [    448,    "hooked wandering bottom",    16],
            [    448,    "UV pulse slow",    2],
            [    464,    "UV pulse slow",    2],
            [    464,    "hooked wandering top",    16],
            [    480,    "Autogen bassline bottom",    2],
            [    480,    "Autogen bassline bottom",    2]
        ],
        "bpm": 120,
        "delay_lights": 0.02565,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/Porter Robinson - Musician (Official Music Video).ogg"
    }
}