effects = {
    "g_Porter Robinson - Musician (Official Music Video)": {
        "beats": [
            [    1,    "hooked wandering bottom",    16],
            [    1,    "Autogen bassline sidechain bottom",    2],
            [    17,    "rainbow good slow top",    16],
            [    17,    "UV pulse slow",    2],
            [    33,    "hooked wandering top",    16],
            [    33,    "Autogen bassline bottom",    2],
            [    49,    "UV pulse",    1],
            [    49,    "rainbow good slow top",    16],
            [    65,    "hooked wandering bottom",    16],
            [    65,    "RBBB 1 bar",    4],
            [    81,    "Ghosts riser",    4],
            [    81,    "rainbow good slow top",    16],
            [    97,    "UV pulse",    1],
            [    97,    "RBBB 1 bar",    4],
            [    101,    "Rainbow bad",    2],
            [    101,    "Autogen UV Strobe",    1],
            [    103,    "hooked wandering bottom",    16],
            [    103,    "Autogen Strobe",    1],
            [    119,    "Autogen UV Strobe",    1],
            [    119,    "UV pulse slow",    2],
            [    121,    "Rainbow bad",    2],
            [    121,    "Autogen bassline sidechain bottom",    2],
            [    123,    "Autogen bassline top",    2],
            [    123,    "UV pulse slow",    2],
            [    125,    "Autogen Strobe",    1],
            [    125,    "hooked wandering bottom",    16],
            [    141,    "Autogen bassline sidechain bottom",    2],
            [    141,    "Ghosts riser",    4],
            [    145,    "UV pulse slow",    2],
            [    145,    "rainbow good slow top",    16],
            [    161,    "UV pulse",    1],
            [    161,    "Ghosts riser",    4],
            [    165,    "RBBB 1 bar",    4],
            [    165,    "rainbow good slow top",    16],
            [    181,    "Autogen UV Strobe",    1],
            [    181,    "Ghosts riser",    4],
            [    185,    "hooked wandering bottom",    16],
            [    185,    "hooked wandering bottom",    16],
            [    201,    "rainbow good slow top",    16],
            [    201,    "Autogen Strobe",    1],
            [    217,    "Autogen bassline sidechain bottom",    2],
            [    217,    "rainbow good slow top",    16],
            [    233,    "Autogen bassline sidechain bottom",    2],
            [    233,    "hooked wandering bottom",    16],
            [    249,    "Autogen Strobe",    1],
            [    249,    "RBBB 1 bar",    4],
            [    253,    "rainbow good slow top",    16],
            [    253,    "Rainbow bad",    2],
            [    269,    "Autogen Strobe",    1],
            [    269,    "hooked wandering bottom",    16],
            [    285,    "RBBB 1 bar",    4],
            [    285,    "Autogen bassline bottom",    2],
            [    289,    "hooked wandering top",    16],
            [    289,    "Autogen bassline top",    2],
            [    305,    "hooked wandering top",    16],
            [    305,    "rainbow good slow top",    16],
            [    321,    "Rainbow bad",    2],
            [    321,    "Autogen bassline bottom",    2],
            [    323,    "Autogen bassline top",    2],
            [    323,    "rainbow good slow top",    16],
            [    339,    "UV pulse",    1],
            [    339,    "Autogen bassline bottom",    2],
            [    341,    "Autogen bassline bottom",    2],
            [    341,    "Autogen Strobe",    1],
            [    343,    "Autogen UV Strobe",    1],
            [    343,    "Autogen Strobe",    1],
            [    344,    "Autogen Strobe",    1],
            [    344,    "RBBB 1 bar",    4],
            [    348,    "Autogen bassline sidechain bottom",    2],
            [    348,    "Rainbow bad",    2],
            [    350,    "Autogen UV Strobe",    1],
            [    350,    "RBBB 1 bar",    4],
            [    354,    "Autogen bassline top",    2],
            [    354,    "hooked wandering bottom",    16],
            [    370,    "UV pulse",    1],
            [    370,    "rainbow good slow top",    16],
            [    386,    "Autogen bassline sidechain bottom",    2],
            [    386,    "Ghosts riser",    4],
            [    390,    "hooked wandering bottom",    16],
            [    390,    "hooked wandering bottom",    16],
            [    406,    "Autogen bassline sidechain bottom",    2],
            [    406,    "Autogen bassline top",    2],
            [    408,    "Autogen bassline top",    2],
            [    408,    "Autogen bassline top",    2],
            [    410,    "hooked wandering top",    16],
            [    410,    "Rainbow bad",    2],
            [    426,    "Autogen Strobe",    1],
            [    426,    "Autogen bassline bottom",    2],
            [    428,    "Autogen bassline sidechain bottom",    2],
            [    428,    "RBBB 1 bar",    4],
            [    432,    "UV pulse slow",    2],
            [    432,    "Autogen UV Strobe",    1],
            [    434,    "Autogen bassline top",    2],
            [    434,    "Autogen Strobe",    1],
            [    436,    "Autogen Strobe",    1],
            [    436,    "hooked wandering bottom",    16],
            [    452,    "UV pulse slow",    2],
            [    452,    "hooked wandering bottom",    16],
            [    468,    "Rainbow bad",    2],
            [    468,    "hooked wandering bottom",    16]
        ],
        "bpm": 120,
        "delay_lights": 0.02565,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/Porter Robinson - Musician (Official Music Video).ogg"
    }
}