effects = {
    "g_Radiohead - Everything in Its Right Place (Sam Goku Edit)": {
        "beats": [
            [    1,    "UV pulse slow",    2],
            [    1,    "UV pulse slow",    2],
            [    3,    "Ghosts riser",    4],
            [    3,    "Autogen Strobe",    1],
            [    7,    "UV pulse slow",    2],
            [    7,    "Autogen Strobe",    1],
            [    9,    "UV pulse",    1],
            [    9,    "Autogen bassline sidechain bottom",    2],
            [    11,    "Autogen UV Strobe",    1],
            [    11,    "rainbow good slow top",    16],
            [    27,    "hooked wandering top",    16],
            [    27,    "rainbow good slow top",    16],
            [    43,    "Autogen Strobe",    1],
            [    43,    "Rainbow bad",    2],
            [    45,    "Autogen UV Strobe",    1],
            [    45,    "RBBB 1 bar",    4],
            [    49,    "rainbow good slow top",    16],
            [    49,    "UV pulse slow",    2],
            [    65,    "Autogen UV Strobe",    1],
            [    65,    "UV pulse slow",    2],
            [    67,    "Autogen Strobe",    1],
            [    67,    "RBBB 1 bar",    4],
            [    71,    "Autogen bassline sidechain bottom",    2],
            [    71,    "Ghosts riser",    4],
            [    75,    "Rainbow bad",    2],
            [    75,    "RBBB 1 bar",    4],
            [    79,    "Ghosts riser",    4],
            [    79,    "hooked wandering top",    16],
            [    95,    "Rainbow bad",    2],
            [    95,    "hooked wandering top",    16],
            [    111,    "UV pulse",    1],
            [    111,    "Autogen bassline bottom",    2],
            [    113,    "Autogen bassline top",    2],
            [    113,    "hooked wandering bottom",    16],
            [    129,    "hooked wandering bottom",    16],
            [    129,    "Autogen UV Strobe",    1],
            [    145,    "Autogen bassline sidechain bottom",    2],
            [    145,    "Autogen bassline sidechain bottom",    2],
            [    147,    "Rainbow bad",    2],
            [    147,    "Autogen Strobe",    1],
            [    149,    "UV pulse",    1],
            [    149,    "RBBB 1 bar",    4],
            [    153,    "hooked wandering top",    16],
            [    153,    "RBBB 1 bar",    4],
            [    169,    "Autogen Strobe",    1],
            [    169,    "rainbow good slow top",    16],
            [    185,    "rainbow good slow top",    16],
            [    185,    "Autogen Strobe",    1],
            [    201,    "Autogen bassline top",    2],
            [    201,    "hooked wandering bottom",    16],
            [    217,    "Autogen Strobe",    1],
            [    217,    "Autogen bassline top",    2],
            [    219,    "Autogen UV Strobe",    1],
            [    219,    "Autogen bassline top",    2],
            [    221,    "Autogen Strobe",    1],
            [    221,    "UV pulse",    1],
            [    222,    "rainbow good slow top",    16],
            [    222,    "RBBB 1 bar",    4],
            [    238,    "hooked wandering top",    16],
            [    238,    "UV pulse slow",    2],
            [    254,    "Autogen Strobe",    1],
            [    254,    "Autogen Strobe",    1],
            [    255,    "hooked wandering bottom",    16],
            [    255,    "Autogen bassline sidechain bottom",    2],
            [    271,    "Autogen bassline sidechain bottom",    2],
            [    271,    "RBBB 1 bar",    4],
            [    275,    "Ghosts riser",    4],
            [    275,    "Autogen bassline sidechain bottom",    2],
            [    279,    "UV pulse slow",    2],
            [    279,    "Autogen Strobe",    1],
            [    281,    "rainbow good slow top",    16],
            [    281,    "Autogen bassline top",    2],
            [    297,    "rainbow good slow top",    16],
            [    297,    "Rainbow bad",    2],
            [    313,    "Autogen UV Strobe",    1],
            [    313,    "UV pulse slow",    2],
            [    315,    "hooked wandering top",    16],
            [    315,    "Autogen bassline bottom",    2],
            [    331,    "rainbow good slow top",    16],
            [    331,    "Autogen bassline top",    2],
            [    347,    "Autogen UV Strobe",    1],
            [    347,    "hooked wandering bottom",    16],
            [    363,    "Autogen bassline sidechain bottom",    2],
            [    363,    "RBBB 1 bar",    4],
            [    367,    "Autogen bassline sidechain bottom",    2],
            [    367,    "Autogen bassline sidechain bottom",    2],
            [    369,    "Autogen bassline bottom",    2],
            [    369,    "Autogen bassline bottom",    2],
            [    371,    "UV pulse",    1],
            [    371,    "UV pulse slow",    2],
            [    373,    "rainbow good slow top",    16],
            [    373,    "UV pulse slow",    2],
            [    389,    "Autogen bassline bottom",    2],
            [    389,    "Autogen bassline top",    2],
            [    391,    "Autogen UV Strobe",    1],
            [    391,    "UV pulse slow",    2],
            [    393,    "RBBB 1 bar",    4],
            [    393,    "Ghosts riser",    4],
            [    397,    "UV pulse",    1],
            [    397,    "Ghosts riser",    4],
            [    401,    "Autogen UV Strobe",    1],
            [    401,    "RBBB 1 bar",    4],
            [    405,    "Autogen bassline top",    2],
            [    405,    "hooked wandering bottom",    16],
            [    421,    "UV pulse slow",    2],
            [    421,    "UV pulse slow",    2],
            [    423,    "Ghosts riser",    4],
            [    423,    "hooked wandering bottom",    16],
            [    439,    "Autogen UV Strobe",    1],
            [    439,    "UV pulse slow",    2],
            [    441,    "hooked wandering bottom",    16],
            [    441,    "hooked wandering bottom",    16],
            [    457,    "Autogen bassline sidechain bottom",    2],
            [    457,    "hooked wandering top",    16],
            [    473,    "UV pulse",    1],
            [    473,    "Autogen bassline top",    2],
            [    475,    "UV pulse",    1],
            [    475,    "Autogen Strobe",    1],
            [    476,    "Autogen bassline bottom",    2],
            [    476,    "UV pulse",    1],
            [    478,    "RBBB 1 bar",    4],
            [    478,    "Autogen bassline top",    2],
            [    482,    "Rainbow bad",    2],
            [    482,    "RBBB 1 bar",    4],
            [    486,    "rainbow good slow top",    16],
            [    486,    "Rainbow bad",    2],
            [    502,    "UV pulse",    1],
            [    502,    "UV pulse slow",    2],
            [    504,    "Autogen bassline sidechain bottom",    2],
            [    504,    "Autogen bassline sidechain bottom",    2],
            [    506,    "RBBB 1 bar",    4],
            [    506,    "Autogen Strobe",    1],
            [    510,    "Ghosts riser",    4],
            [    510,    "UV pulse",    1],
            [    514,    "UV pulse",    1],
            [    514,    "Autogen bassline bottom",    2],
            [    516,    "Rainbow bad",    2],
            [    516,    "Autogen bassline sidechain bottom",    2],
            [    518,    "Ghosts riser",    4],
            [    518,    "Autogen bassline top",    2],
            [    522,    "RBBB 1 bar",    4],
            [    522,    "Autogen bassline bottom",    2],
            [    526,    "Rainbow bad",    2],
            [    526,    "hooked wandering top",    16],
            [    542,    "Ghosts riser",    4],
            [    542,    "UV pulse",    1],
            [    546,    "hooked wandering top",    16],
            [    546,    "Autogen bassline sidechain bottom",    2],
            [    562,    "Autogen bassline bottom",    2],
            [    562,    "RBBB 1 bar",    4],
            [    566,    "UV pulse",    1],
            [    566,    "RBBB 1 bar",    4],
            [    570,    "RBBB 1 bar",    4],
            [    570,    "Autogen Strobe",    1],
            [    574,    "Autogen UV Strobe",    1],
            [    574,    "Autogen bassline top",    2],
            [    576,    "rainbow good slow top",    16],
            [    576,    "hooked wandering bottom",    16],
            [    592,    "hooked wandering bottom",    16],
            [    592,    "Autogen bassline sidechain bottom",    2],
            [    608,    "rainbow good slow top",    16],
            [    608,    "RBBB 1 bar",    4],
            [    624,    "Autogen UV Strobe",    1],
            [    624,    "Rainbow bad",    2],
            [    626,    "UV pulse slow",    2],
            [    626,    "hooked wandering top",    16],
            [    642,    "Autogen Strobe",    1],
            [    642,    "RBBB 1 bar",    4],
            [    646,    "hooked wandering top",    16],
            [    646,    "Ghosts riser",    4],
            [    662,    "UV pulse",    1],
            [    662,    "UV pulse",    1],
            [    663,    "rainbow good slow top",    16],
            [    663,    "UV pulse slow",    2],
            [    679,    "hooked wandering top",    16],
            [    679,    "hooked wandering top",    16],
            [    695,    "Autogen bassline bottom",    2],
            [    695,    "hooked wandering bottom",    16],
            [    711,    "rainbow good slow top",    16],
            [    711,    "hooked wandering bottom",    16]
        ],
        "bpm": 120,
        "delay_lights": 0.10235,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/Radiohead - Everything in Its Right Place (Sam Goku Edit).ogg"
    }
}