effects = {
    "g_s_Snails House  Chiffon": {
        "beats": [
            [    1,    "g_UV pulse",    2],
            [    3,    "g_Strobe",    1],
            [    4,    "RGB Flash",    1],
            [    5,    "g_UV Strobe",    1],
            [    6,    "RGB Flash",    1],
            [    7,    "g_solid top cycle",    16],
            [    23,    "g_solid top cycle",    16],
            [    39,    "g_UV pulse",    4],
            [    43,    "g_cyan top pulse",    16],
            [    43,    "g_green sidechain bottom pulse",    16],
            [    59,    "g_solid mixed double",    16],
            [    59,    "g_UV",    16],
            [    75,    "RGB Flash",    1],
            [    76,    "g_solid mixed double",    16],
            [    76,    "g_UV",    16],
            [    92,    "g_solid mixed double",    16],
            [    92,    "g_UV",    16],
            [    108,    "g_solid top cycle",    16],
            [    108,    "g_purple green bottom pulse",    16],
            [    108,    "g_UV",    16],
            [    124,    "g_solid mixed cycle",    16],
            [    140,    "g_solid mixed cycle",    16],
            [    140,    "g_UV",    16],
            [    156,    "g_rainbow good slow top",    16],
            [    156,    "g_solid bottom cycle",    16],
            [    172,    "g_solid top cycle",    16],
            [    172,    "g_UV",    16],
            [    188,    "g_cyan top pulse",    16],
            [    188,    "g_UV",    16],
            [    204,    "g_cyan top pulse",    16],
            [    204,    "g_green sidechain bottom pulse",    16],
            [    204,    "g_UV",    16],
            [    220,    "g_solid mixed double",    16],
            [    236,    "g_green sidechain bottom pulse",    16],
            [    236,    "g_UV",    16],
            [    252,    "g_solid top cycle",    16],
            [    252,    "g_UV",    16],
            [    268,    "g_green sidechain bottom pulse",    16],
            [    268,    "g_UV",    16],
            [    284,    "g_cyan top pulse",    16],
            [    300,    "g_cyan top pulse",    16],
            [    300,    "g_UV",    16],
            [    316,    "g_solid bottom cycle",    16],
            [    316,    "g_UV",    16],
            [    332,    "g_solid mixed double",    16],
            [    348,    "g_rainbow good slow top",    16],
            [    348,    "g_green sidechain bottom pulse",    16],
            [    364,    "g_Strobe",    1],
            [    365,    "g_UV pulse",    1],
            [    366,    "g_UV pulse",    4],
            [    370,    "g_UV pulse",    2],
            [    372,    "g_solid bottom cycle",    16],
            [    388,    "g_solid mixed double",    16],
            [    404,    "g_rainbow good top",    16],
            [    404,    "g_purple green bottom pulse",    16],
            [    420,    "RGB Flash",    1],
            [    421,    "g_solid top cycle",    16],
            [    421,    "g_UV",    16],
            [    437,    "RGB Flash",    1],
            [    438,    "g_purple green bottom pulse",    16],
            [    454,    "g_solid bottom cycle",    16],
            [    470,    "g_UV Strobe",    1],
            [    471,    "g_solid top cycle",    16],
            [    471,    "g_solid bottom cycle",    16],
            [    471,    "g_UV",    16],
            [    487,    "g_solid top cycle",    16],
            [    487,    "g_UV",    16],
            [    503,    "g_solid top cycle",    16],
            [    503,    "g_UV",    16],
            [    519,    "g_Strobe",    1],
            [    520,    "g_cyan top pulse",    16],
            [    520,    "g_solid bottom cycle",    16],
            [    536,    "g_solid mixed cycle",    16],
            [    536,    "g_UV",    16],
            [    552,    "g_cyan top pulse",    16],
            [    552,    "g_purple green bottom pulse",    16],
            [    568,    "g_solid mixed double",    16],
            [    568,    "g_UV",    16],
            [    584,    "g_solid top cycle",    16],
            [    584,    "g_solid bottom cycle",    16],
            [    584,    "g_UV",    16],
            [    600,    "RGB Flash",    1],
            [    601,    "g_rainbow good slow top",    16],
            [    601,    "g_green sidechain bottom pulse",    16],
            [    617,    "g_cyan top pulse",    16],
            [    617,    "g_green sidechain bottom pulse",    16],
            [    633,    "g_UV pulse",    2],
            [    635,    "RGB Flash",    1],
            [    636,    "g_UV pulse",    4],
            [    640,    "g_solid top cycle",    16],
            [    640,    "g_solid bottom cycle",    16],
            [    640,    "g_UV",    16],
            [    656,    "g_purple green bottom pulse",    16],
            [    656,    "g_UV",    16],
            [    672,    "g_cyan top pulse",    16],
            [    672,    "g_green sidechain bottom pulse",    16],
            [    672,    "g_UV",    16]
        ],
        "bpm": 169,
        "delay_lights": 0.2640795857988165,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/s_Snails House  Chiffon.ogg",
        "was_autogenerated": True
    }
}