effects = {
    "g_s_\u30e8\u30eb\u30b7\u30ab  \u5de6\u53f3\u76f2OFFICIAL VIDEO": {
        "beats": [
            [    1,    "Autogen bassline top",    2],
            [    1,    "UV pulse slow",    2],
            [    3,    "rainbow good slow top",    16],
            [    3,    "UV pulse",    1],
            [    19,    "Autogen Strobe",    1],
            [    19,    "rainbow good slow top",    16],
            [    35,    "UV pulse slow",    2],
            [    35,    "Autogen bassline top",    2],
            [    37,    "hooked wandering top",    16],
            [    37,    "Autogen UV Strobe",    1],
            [    53,    "hooked wandering top",    16],
            [    53,    "Autogen bassline sidechain bottom",    2],
            [    69,    "hooked wandering top",    16],
            [    69,    "Autogen UV Strobe",    1],
            [    85,    "hooked wandering bottom",    16],
            [    85,    "rainbow good slow top",    16],
            [    101,    "Autogen Strobe",    1],
            [    101,    "Rainbow bad",    2],
            [    103,    "hooked wandering bottom",    16],
            [    103,    "UV pulse slow",    2],
            [    119,    "RBBB 1 bar",    4],
            [    119,    "Ghosts riser",    4],
            [    123,    "Rainbow bad",    2],
            [    123,    "hooked wandering bottom",    16],
            [    139,    "UV pulse slow",    2],
            [    139,    "UV pulse",    1],
            [    141,    "Autogen Strobe",    1],
            [    141,    "Ghosts riser",    4],
            [    145,    "Autogen bassline sidechain bottom",    2],
            [    145,    "hooked wandering top",    16],
            [    161,    "Autogen bassline bottom",    2],
            [    161,    "hooked wandering top",    16],
            [    177,    "hooked wandering bottom",    16],
            [    177,    "Autogen Strobe",    1],
            [    193,    "Autogen Strobe",    1],
            [    193,    "RBBB 1 bar",    4],
            [    197,    "Autogen UV Strobe",    1],
            [    197,    "RBBB 1 bar",    4],
            [    201,    "rainbow good slow top",    16],
            [    201,    "Autogen Strobe",    1],
            [    217,    "UV pulse",    1],
            [    217,    "UV pulse",    1],
            [    218,    "Autogen bassline bottom",    2],
            [    218,    "rainbow good slow top",    16],
            [    234,    "hooked wandering bottom",    16],
            [    234,    "UV pulse slow",    2],
            [    250,    "Rainbow bad",    2],
            [    250,    "hooked wandering top",    16],
            [    266,    "hooked wandering top",    16],
            [    266,    "Autogen Strobe",    1],
            [    282,    "Autogen bassline sidechain bottom",    2],
            [    282,    "UV pulse slow",    2],
            [    284,    "UV pulse slow",    2],
            [    284,    "hooked wandering bottom",    16],
            [    300,    "hooked wandering bottom",    16],
            [    300,    "Autogen bassline top",    2],
            [    316,    "Autogen Strobe",    1],
            [    316,    "hooked wandering top",    16],
            [    332,    "rainbow good slow top",    16],
            [    332,    "hooked wandering bottom",    16],
            [    348,    "Autogen bassline bottom",    2],
            [    348,    "Autogen bassline bottom",    2],
            [    350,    "rainbow good slow top",    16],
            [    350,    "UV pulse",    1],
            [    366,    "UV pulse slow",    2],
            [    366,    "RBBB 1 bar",    4],
            [    370,    "Autogen Strobe",    1],
            [    370,    "UV pulse",    1],
            [    371,    "Autogen Strobe",    1],
            [    371,    "Autogen bassline bottom",    2],
            [    373,    "Autogen Strobe",    1],
            [    373,    "hooked wandering bottom",    16],
            [    389,    "Autogen bassline top",    2],
            [    389,    "hooked wandering top",    16],
            [    405,    "hooked wandering top",    16],
            [    405,    "hooked wandering bottom",    16],
            [    421,    "hooked wandering bottom",    16],
            [    421,    "RBBB 1 bar",    4],
            [    437,    "Autogen bassline sidechain bottom",    2],
            [    437,    "RBBB 1 bar",    4],
            [    441,    "Ghosts riser",    4],
            [    441,    "Autogen bassline bottom",    2],
            [    445,    "hooked wandering top",    16],
            [    445,    "Autogen UV Strobe",    1],
            [    461,    "Ghosts riser",    4],
            [    461,    "Autogen bassline top",    2],
            [    465,    "Autogen bassline top",    2],
            [    465,    "hooked wandering bottom",    16],
            [    481,    "UV pulse",    1],
            [    481,    "Autogen Strobe",    1],
            [    482,    "RBBB 1 bar",    4],
            [    482,    "Ghosts riser",    4],
            [    486,    "Autogen bassline bottom",    2],
            [    486,    "UV pulse slow",    2],
            [    488,    "Autogen Strobe",    1],
            [    488,    "Autogen Strobe",    1],
            [    489,    "RBBB 1 bar",    4],
            [    489,    "Autogen bassline top",    2],
            [    493,    "Ghosts riser",    4],
            [    493,    "Rainbow bad",    2],
            [    497,    "Rainbow bad",    2],
            [    497,    "hooked wandering top",    16],
            [    513,    "Autogen bassline top",    2],
            [    513,    "RBBB 1 bar",    4],
            [    517,    "Autogen bassline top",    2],
            [    517,    "Ghosts riser",    4],
            [    521,    "UV pulse",    1],
            [    521,    "hooked wandering bottom",    16],
            [    537,    "hooked wandering top",    16],
            [    537,    "Autogen Strobe",    1],
            [    553,    "Rainbow bad",    2],
            [    553,    "hooked wandering top",    16],
            [    569,    "Ghosts riser",    4],
            [    569,    "Autogen bassline sidechain bottom",    2],
            [    573,    "UV pulse slow",    2],
            [    573,    "Rainbow bad",    2],
            [    575,    "RBBB 1 bar",    4],
            [    575,    "hooked wandering bottom",    16],
            [    591,    "UV pulse slow",    2],
            [    591,    "Autogen bassline bottom",    2],
            [    593,    "Autogen bassline bottom",    2],
            [    593,    "Autogen Strobe",    1],
            [    595,    "hooked wandering bottom",    16],
            [    595,    "Autogen bassline top",    2],
            [    611,    "Ghosts riser",    4],
            [    611,    "Autogen Strobe",    1],
            [    615,    "Ghosts riser",    4],
            [    615,    "UV pulse slow",    2],
            [    619,    "Autogen bassline bottom",    2],
            [    619,    "Rainbow bad",    2],
            [    621,    "UV pulse",    1],
            [    621,    "Rainbow bad",    2],
            [    623,    "Autogen bassline bottom",    2],
            [    623,    "hooked wandering bottom",    16],
            [    639,    "Rainbow bad",    2],
            [    639,    "rainbow good slow top",    16],
            [    655,    "Autogen bassline bottom",    2],
            [    655,    "Autogen UV Strobe",    1],
            [    657,    "rainbow good slow top",    16],
            [    657,    "Autogen bassline sidechain bottom",    2],
            [    673,    "Autogen UV Strobe",    1],
            [    673,    "UV pulse slow",    2],
            [    675,    "UV pulse slow",    2],
            [    675,    "UV pulse",    1],
            [    677,    "RBBB 1 bar",    4],
            [    677,    "Rainbow bad",    2],
            [    681,    "UV pulse slow",    2],
            [    681,    "Rainbow bad",    2],
            [    683,    "UV pulse slow",    2],
            [    683,    "Autogen bassline bottom",    2],
            [    685,    "rainbow good slow top",    16],
            [    685,    "hooked wandering top",    16]
        ],
        "bpm": 152,
        "delay_lights": 0.1215,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/s_\u30e8\u30eb\u30b7\u30ab  \u5de6\u53f3\u76f2OFFICIAL VIDEO.ogg"
    }
}