effects = {
    "g_s_Groundbreaking BOF2012 ginkiha  EOS Long Version": {
        "beats": [
            [    1,    "Autogen Strobe",    1],
            [    1,    "hooked wandering bottom",    16],
            [    17,    "Autogen bassline bottom",    2],
            [    17,    "Autogen bassline bottom",    2],
            [    19,    "UV pulse",    1],
            [    19,    "Autogen bassline sidechain bottom",    2],
            [    21,    "Autogen bassline top",    2],
            [    21,    "hooked wandering bottom",    16],
            [    37,    "Rainbow bad",    2],
            [    37,    "Autogen bassline bottom",    2],
            [    39,    "Autogen bassline sidechain bottom",    2],
            [    39,    "Autogen Strobe",    1],
            [    41,    "Autogen bassline sidechain bottom",    2],
            [    41,    "Ghosts riser",    4],
            [    45,    "Autogen bassline bottom",    2],
            [    45,    "Autogen bassline bottom",    2],
            [    47,    "UV pulse",    1],
            [    47,    "hooked wandering top",    16],
            [    63,    "Autogen bassline top",    2],
            [    63,    "UV pulse",    1],
            [    65,    "Rainbow bad",    2],
            [    65,    "rainbow good slow top",    16],
            [    81,    "Ghosts riser",    4],
            [    81,    "Autogen bassline sidechain bottom",    2],
            [    85,    "RBBB 1 bar",    4],
            [    85,    "Autogen bassline top",    2],
            [    89,    "Rainbow bad",    2],
            [    89,    "hooked wandering bottom",    16],
            [    105,    "Autogen Strobe",    1],
            [    105,    "RBBB 1 bar",    4],
            [    109,    "Autogen bassline bottom",    2],
            [    109,    "Autogen bassline sidechain bottom",    2],
            [    111,    "Autogen bassline sidechain bottom",    2],
            [    111,    "UV pulse",    1],
            [    113,    "rainbow good slow top",    16],
            [    113,    "UV pulse",    1],
            [    129,    "Autogen bassline bottom",    2],
            [    129,    "UV pulse",    1],
            [    131,    "hooked wandering bottom",    16],
            [    131,    "Autogen bassline sidechain bottom",    2],
            [    147,    "Rainbow bad",    2],
            [    147,    "hooked wandering top",    16],
            [    163,    "Ghosts riser",    4],
            [    163,    "Autogen UV Strobe",    1],
            [    167,    "rainbow good slow top",    16],
            [    167,    "Ghosts riser",    4],
            [    183,    "rainbow good slow top",    16],
            [    183,    "rainbow good slow top",    16],
            [    199,    "Autogen UV Strobe",    1],
            [    199,    "Autogen Strobe",    1],
            [    200,    "Autogen bassline top",    2],
            [    200,    "Ghosts riser",    4],
            [    204,    "UV pulse",    1],
            [    204,    "Autogen Strobe",    1],
            [    205,    "Autogen bassline top",    2],
            [    205,    "Rainbow bad",    2],
            [    207,    "hooked wandering bottom",    16],
            [    207,    "Autogen Strobe",    1],
            [    223,    "hooked wandering bottom",    16],
            [    223,    "Autogen bassline sidechain bottom",    2],
            [    239,    "Autogen bassline bottom",    2],
            [    239,    "UV pulse",    1],
            [    241,    "Rainbow bad",    2],
            [    241,    "Autogen bassline bottom",    2],
            [    243,    "Autogen Strobe",    1],
            [    243,    "Autogen bassline sidechain bottom",    2],
            [    245,    "UV pulse slow",    2],
            [    245,    "UV pulse",    1],
            [    247,    "UV pulse slow",    2],
            [    247,    "Autogen UV Strobe",    1],
            [    249,    "Autogen UV Strobe",    1],
            [    249,    "Autogen UV Strobe",    1],
            [    250,    "Ghosts riser",    4],
            [    250,    "rainbow good slow top",    16],
            [    266,    "Ghosts riser",    4],
            [    266,    "rainbow good slow top",    16],
            [    282,    "hooked wandering top",    16],
            [    282,    "Rainbow bad",    2],
            [    298,    "RBBB 1 bar",    4],
            [    298,    "Rainbow bad",    2],
            [    302,    "Ghosts riser",    4],
            [    302,    "Autogen bassline bottom",    2],
            [    306,    "Autogen bassline sidechain bottom",    2],
            [    306,    "Autogen bassline sidechain bottom",    2],
            [    308,    "hooked wandering bottom",    16],
            [    308,    "RBBB 1 bar",    4],
            [    324,    "UV pulse slow",    2],
            [    324,    "hooked wandering top",    16],
            [    340,    "UV pulse",    1],
            [    340,    "Autogen bassline top",    2],
            [    342,    "UV pulse",    1],
            [    342,    "Autogen bassline sidechain bottom",    2],
            [    344,    "Rainbow bad",    2],
            [    344,    "rainbow good slow top",    16],
            [    360,    "Ghosts riser",    4],
            [    360,    "Rainbow bad",    2],
            [    364,    "RBBB 1 bar",    4],
            [    364,    "Autogen bassline top",    2],
            [    368,    "Autogen bassline bottom",    2],
            [    368,    "UV pulse slow",    2],
            [    370,    "hooked wandering top",    16],
            [    370,    "Autogen bassline bottom",    2],
            [    386,    "Autogen Strobe",    1],
            [    386,    "hooked wandering top",    16],
            [    402,    "hooked wandering bottom",    16],
            [    402,    "hooked wandering top",    16],
            [    418,    "UV pulse slow",    2],
            [    418,    "Autogen Strobe",    1],
            [    420,    "hooked wandering top",    16],
            [    420,    "Rainbow bad",    2],
            [    436,    "RBBB 1 bar",    4],
            [    436,    "Autogen UV Strobe",    1],
            [    440,    "UV pulse",    1],
            [    440,    "hooked wandering bottom",    16],
            [    456,    "Autogen bassline bottom",    2],
            [    456,    "hooked wandering bottom",    16],
            [    472,    "Autogen bassline sidechain bottom",    2],
            [    472,    "rainbow good slow top",    16],
            [    488,    "Rainbow bad",    2],
            [    488,    "rainbow good slow top",    16],
            [    504,    "Autogen bassline bottom",    2],
            [    504,    "Ghosts riser",    4],
            [    508,    "UV pulse",    1],
            [    508,    "hooked wandering bottom",    16],
            [    524,    "Autogen bassline top",    2],
            [    524,    "Autogen bassline sidechain bottom",    2],
            [    526,    "Autogen bassline top",    2],
            [    526,    "rainbow good slow top",    16],
            [    542,    "UV pulse slow",    2],
            [    542,    "Rainbow bad",    2],
            [    544,    "Autogen Strobe",    1],
            [    544,    "Ghosts riser",    4],
            [    548,    "Autogen bassline sidechain bottom",    2],
            [    548,    "hooked wandering top",    16],
            [    564,    "Autogen bassline sidechain bottom",    2],
            [    564,    "Autogen bassline bottom",    2],
            [    566,    "Autogen UV Strobe",    1],
            [    566,    "hooked wandering bottom",    16],
            [    582,    "Autogen Strobe",    1],
            [    582,    "Rainbow bad",    2],
            [    584,    "Autogen UV Strobe",    1],
            [    584,    "rainbow good slow top",    16],
            [    600,    "UV pulse",    1],
            [    600,    "UV pulse",    1],
            [    601,    "hooked wandering bottom",    16],
            [    601,    "Autogen bassline bottom",    2],
            [    617,    "Autogen Strobe",    1],
            [    617,    "Autogen Strobe",    1],
            [    618,    "Rainbow bad",    2],
            [    618,    "Autogen bassline bottom",    2],
            [    620,    "Autogen UV Strobe",    1],
            [    620,    "rainbow good slow top",    16],
            [    636,    "rainbow good slow top",    16],
            [    636,    "Autogen bassline sidechain bottom",    2],
            [    652,    "Autogen UV Strobe",    1],
            [    652,    "Autogen bassline sidechain bottom",    2],
            [    654,    "Autogen bassline sidechain bottom",    2],
            [    654,    "Autogen Strobe",    1],
            [    656,    "Autogen Strobe",    1],
            [    656,    "Autogen bassline sidechain bottom",    2],
            [    658,    "Autogen UV Strobe",    1],
            [    658,    "Autogen bassline top",    2],
            [    660,    "Rainbow bad",    2],
            [    660,    "hooked wandering bottom",    16],
            [    676,    "Autogen bassline bottom",    2],
            [    676,    "Autogen Strobe",    1],
            [    678,    "rainbow good slow top",    16],
            [    678,    "hooked wandering top",    16],
            [    694,    "hooked wandering bottom",    16],
            [    694,    "hooked wandering top",    16],
            [    710,    "hooked wandering bottom",    16],
            [    710,    "Autogen bassline bottom",    2],
            [    726,    "Autogen bassline sidechain bottom",    2],
            [    726,    "Autogen UV Strobe",    1],
            [    728,    "hooked wandering top",    16],
            [    728,    "UV pulse slow",    2],
            [    744,    "RBBB 1 bar",    4],
            [    744,    "rainbow good slow top",    16]
        ],
        "bpm": 175,
        "delay_lights": 0.32526214285714283,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/s_Groundbreaking BOF2012 ginkiha  EOS Long Version.ogg"
    }
}