effects = {
    "g_s_Groundbreaking BOF2012 ginkiha  EOS Long Version": {
        "beats": [
            [    1,    "g_solid mixed cycle",    16],
            [    17,    "g_solid top cycle",    16],
            [    17,    "g_UV",    16],
            [    33,    "g_solid top cycle",    16],
            [    33,    "g_UV",    16],
            [    49,    "g_UV pulse",    2],
            [    51,    "g_UV Strobe",    1],
            [    52,    "g_cyan top pulse",    16],
            [    52,    "g_green sidechain bottom pulse",    16],
            [    68,    "g_UV pulse",    1],
            [    69,    "g_rainbow good slow top",    16],
            [    69,    "g_solid bottom cycle",    16],
            [    85,    "g_UV pulse",    1],
            [    86,    "g_solid mixed double",    16],
            [    86,    "g_UV",    16],
            [    102,    "g_solid mixed double",    16],
            [    118,    "g_solid mixed cycle",    16],
            [    134,    "g_green sidechain bottom pulse",    16],
            [    134,    "g_UV",    16],
            [    150,    "g_UV pulse",    1],
            [    151,    "g_UV pulse",    1],
            [    152,    "g_solid top cycle",    16],
            [    152,    "g_solid bottom cycle",    16],
            [    152,    "g_UV",    16],
            [    168,    "RGB Flash",    1],
            [    169,    "g_solid bottom cycle",    16],
            [    185,    "g_UV pulse",    1],
            [    186,    "g_green sidechain bottom pulse",    16],
            [    202,    "g_solid mixed double",    16],
            [    202,    "g_UV",    16],
            [    218,    "g_cyan top pulse",    16],
            [    234,    "g_UV pulse",    2],
            [    236,    "g_solid top cycle",    16],
            [    236,    "g_green sidechain bottom pulse",    16],
            [    236,    "g_UV",    16],
            [    252,    "g_solid mixed cycle",    16],
            [    268,    "g_green sidechain bottom pulse",    16],
            [    284,    "g_cyan top pulse",    16],
            [    284,    "g_purple green bottom pulse",    16],
            [    300,    "g_UV pulse",    1],
            [    301,    "g_solid mixed cycle",    16],
            [    317,    "g_rainbow good slow top",    16],
            [    317,    "g_purple green bottom pulse",    16],
            [    333,    "g_green sidechain bottom pulse",    16],
            [    333,    "g_UV",    16],
            [    349,    "g_UV pulse",    2],
            [    351,    "g_solid top cycle",    16],
            [    351,    "g_solid bottom cycle",    16],
            [    367,    "g_purple green bottom pulse",    16],
            [    367,    "g_UV",    16],
            [    383,    "g_green sidechain bottom pulse",    16],
            [    383,    "g_UV",    16],
            [    399,    "g_UV pulse",    1],
            [    400,    "g_solid top cycle",    16],
            [    400,    "g_UV",    16],
            [    416,    "g_UV pulse",    2],
            [    418,    "g_UV pulse",    4],
            [    422,    "RGB Flash",    1],
            [    423,    "g_solid bottom cycle",    16],
            [    439,    "g_solid bottom cycle",    16],
            [    455,    "g_purple green bottom pulse",    16],
            [    471,    "RGB Flash",    1],
            [    472,    "g_UV pulse",    2],
            [    474,    "g_UV pulse",    2],
            [    476,    "g_solid mixed double",    16],
            [    476,    "g_UV",    16],
            [    492,    "g_rainbow good slow top",    16],
            [    492,    "g_green sidechain bottom pulse",    16],
            [    508,    "RGB Flash",    1],
            [    509,    "g_UV pulse",    4],
            [    513,    "g_UV pulse",    2],
            [    515,    "g_UV pulse",    2],
            [    517,    "g_UV pulse",    2],
            [    519,    "g_green sidechain bottom pulse",    16],
            [    519,    "g_UV",    16],
            [    535,    "g_rainbow good top",    16],
            [    535,    "g_solid bottom cycle",    16],
            [    551,    "g_Strobe",    1],
            [    552,    "g_UV Strobe",    1],
            [    553,    "g_cyan top pulse",    16],
            [    553,    "g_solid bottom cycle",    16],
            [    569,    "g_UV pulse",    1],
            [    570,    "g_rainbow good top",    16],
            [    570,    "g_green sidechain bottom pulse",    16],
            [    586,    "g_solid mixed cycle",    16],
            [    602,    "RGB Flash",    1],
            [    603,    "g_cyan top pulse",    16],
            [    603,    "g_solid bottom cycle",    16],
            [    603,    "g_UV",    16],
            [    619,    "g_cyan top pulse",    16],
            [    619,    "g_purple green bottom pulse",    16],
            [    619,    "g_UV",    16],
            [    635,    "g_UV pulse",    2],
            [    637,    "g_UV pulse",    1],
            [    638,    "g_solid mixed cycle",    16],
            [    638,    "g_UV",    16],
            [    654,    "g_green sidechain bottom pulse",    16],
            [    654,    "g_UV",    16],
            [    670,    "g_UV pulse",    2],
            [    672,    "g_cyan top pulse",    16],
            [    672,    "g_UV",    16],
            [    688,    "g_solid top cycle",    16],
            [    688,    "g_green sidechain bottom pulse",    16],
            [    704,    "g_cyan top pulse",    16],
            [    704,    "g_purple green bottom pulse",    16],
            [    720,    "g_UV pulse",    1],
            [    721,    "g_solid mixed double",    16],
            [    721,    "g_UV",    16],
            [    737,    "g_UV pulse",    2],
            [    739,    "g_UV pulse",    2],
            [    741,    "g_UV pulse",    2],
            [    743,    "g_UV pulse",    4],
            [    747,    "g_UV pulse",    4],
            [    751,    "g_cyan top pulse",    16],
            [    751,    "g_solid bottom cycle",    16],
            [    751,    "g_UV",    16]
        ],
        "bpm": 175,
        "delay_lights": 0.32526214285714283,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/s_Groundbreaking BOF2012 ginkiha  EOS Long Version.ogg",
        "was_autogenerated": True
    }
}