effects = {
    "g_s_Madeon  Gonna Be Good": {
        "beats": [
            [    1,    "g_cyan top pulse",    16],
            [    1,    "g_UV",    16],
            [    17,    "g_solid mixed double",    16],
            [    33,    "g_UV pulse",    1],
            [    34,    "g_cyan top pulse",    16],
            [    34,    "g_UV",    16],
            [    50,    "g_solid bottom cycle",    16],
            [    66,    "g_cyan top pulse",    16],
            [    66,    "g_UV",    16],
            [    82,    "g_UV Strobe",    1],
            [    83,    "g_UV pulse",    4],
            [    87,    "g_solid top cycle",    16],
            [    103,    "RGB Flash",    1],
            [    104,    "g_UV pulse",    1],
            [    105,    "g_solid bottom cycle",    16],
            [    105,    "g_UV",    16],
            [    121,    "g_cyan top pulse",    16],
            [    121,    "g_UV",    16],
            [    137,    "g_solid mixed double",    16],
            [    137,    "g_UV",    16],
            [    153,    "g_cyan top pulse",    16],
            [    153,    "g_UV",    16],
            [    169,    "g_cyan top pulse",    16],
            [    169,    "g_green sidechain bottom pulse",    16],
            [    169,    "g_UV",    16],
            [    185,    "g_UV pulse",    1],
            [    186,    "RGB Flash",    1],
            [    187,    "g_cyan top pulse",    16],
            [    203,    "g_solid mixed double",    16],
            [    203,    "g_UV",    16],
            [    219,    "g_cyan top pulse",    16],
            [    219,    "g_UV",    16],
            [    235,    "g_cyan top pulse",    16],
            [    235,    "g_UV",    16],
            [    251,    "g_cyan top pulse",    16],
            [    251,    "g_solid bottom cycle",    16],
            [    251,    "g_UV",    16],
            [    267,    "g_Strobe",    1],
            [    268,    "g_solid mixed double",    16],
            [    284,    "g_UV pulse",    4],
            [    288,    "g_solid top cycle",    16],
            [    288,    "g_green sidechain bottom pulse",    16],
            [    304,    "RGB Flash",    1],
            [    305,    "g_solid top cycle",    16],
            [    305,    "g_green sidechain bottom pulse",    16],
            [    305,    "g_UV",    16],
            [    321,    "g_solid top cycle",    16],
            [    337,    "g_UV pulse",    2],
            [    339,    "g_UV pulse",    4],
            [    343,    "RGB Flash",    1],
            [    344,    "g_solid mixed double",    16],
            [    344,    "g_UV",    16],
            [    360,    "g_solid top cycle",    16],
            [    376,    "g_UV pulse",    2],
            [    378,    "g_solid top cycle",    16],
            [    394,    "g_solid bottom cycle",    16],
            [    410,    "g_rainbow good top",    16],
            [    410,    "g_green sidechain bottom pulse",    16],
            [    426,    "g_solid top cycle",    16],
            [    426,    "g_UV",    16],
            [    442,    "g_rainbow good top",    16],
            [    442,    "g_purple green bottom pulse",    16],
            [    458,    "g_cyan top pulse",    16],
            [    474,    "g_UV pulse",    2],
            [    476,    "g_solid top cycle",    16],
            [    476,    "g_green sidechain bottom pulse",    16],
            [    476,    "g_UV",    16],
            [    492,    "g_UV pulse",    1],
            [    493,    "g_cyan top pulse",    16],
            [    493,    "g_UV",    16],
            [    509,    "RGB Flash",    1],
            [    510,    "g_purple green bottom pulse",    16],
            [    526,    "g_solid mixed double",    16],
            [    526,    "g_UV",    16],
            [    542,    "g_solid mixed double",    16],
            [    558,    "g_solid top cycle",    16],
            [    558,    "g_solid bottom cycle",    16],
            [    574,    "g_cyan top pulse",    16],
            [    590,    "g_green sidechain bottom pulse",    16],
            [    590,    "g_UV",    16],
            [    606,    "g_solid top cycle",    16],
            [    606,    "g_green sidechain bottom pulse",    16],
            [    606,    "g_UV",    16],
            [    622,    "g_cyan top pulse",    16],
            [    638,    "g_cyan top pulse",    16],
            [    638,    "g_purple green bottom pulse",    16],
            [    638,    "g_UV",    16],
            [    654,    "g_cyan top pulse",    16],
            [    654,    "g_solid bottom cycle",    16],
            [    654,    "g_UV",    16],
            [    670,    "g_solid top cycle",    16],
            [    670,    "g_solid bottom cycle",    16],
            [    670,    "g_UV",    16],
            [    686,    "g_solid mixed double",    16],
            [    702,    "g_purple green bottom pulse",    16],
            [    702,    "g_UV",    16]
        ],
        "bpm": 159,
        "delay_lights": 0.01934,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/s_Madeon  Gonna Be Good.ogg",
        "was_autogenerated": True
    }
}