effects = {
    "g_s_\u30e8\u30eb\u30b7\u30ab  \u5de6\u53f3\u76f2OFFICIAL VIDEO": {
        "beats": [
            [    1,    "g_cyan top pulse",    16],
            [    17,    "g_UV pulse",    2],
            [    19,    "g_Strobe",    1],
            [    20,    "g_cyan top pulse",    16],
            [    20,    "g_solid bottom cycle",    16],
            [    36,    "g_cyan top pulse",    16],
            [    36,    "g_UV",    16],
            [    52,    "g_solid mixed cycle",    16],
            [    52,    "g_UV",    16],
            [    68,    "g_green sidechain bottom pulse",    16],
            [    84,    "g_solid top cycle",    16],
            [    84,    "g_green sidechain bottom pulse",    16],
            [    84,    "g_UV",    16],
            [    100,    "g_UV pulse",    2],
            [    102,    "g_green sidechain bottom pulse",    16],
            [    118,    "g_UV pulse",    2],
            [    120,    "g_Strobe",    1],
            [    121,    "g_UV pulse",    1],
            [    122,    "g_solid mixed double",    16],
            [    122,    "g_UV",    16],
            [    138,    "g_solid mixed cycle",    16],
            [    138,    "g_UV",    16],
            [    154,    "g_rainbow good slow top",    16],
            [    154,    "g_solid bottom cycle",    16],
            [    170,    "g_rainbow good slow top",    16],
            [    170,    "g_purple green bottom pulse",    16],
            [    186,    "g_cyan top pulse",    16],
            [    186,    "g_purple green bottom pulse",    16],
            [    186,    "g_UV",    16],
            [    202,    "g_cyan top pulse",    16],
            [    218,    "g_green sidechain bottom pulse",    16],
            [    234,    "g_solid top cycle",    16],
            [    234,    "g_green sidechain bottom pulse",    16],
            [    250,    "g_UV pulse",    1],
            [    251,    "g_UV pulse",    4],
            [    255,    "g_UV pulse",    1],
            [    256,    "g_UV pulse",    1],
            [    257,    "RGB Flash",    1],
            [    258,    "g_UV pulse",    4],
            [    262,    "g_solid mixed cycle",    16],
            [    262,    "g_UV",    16],
            [    278,    "g_cyan top pulse",    16],
            [    294,    "g_UV pulse",    4],
            [    298,    "g_rainbow good slow top",    16],
            [    298,    "g_green sidechain bottom pulse",    16],
            [    314,    "g_solid top cycle",    16],
            [    314,    "g_UV",    16],
            [    330,    "g_solid mixed double",    16],
            [    330,    "g_UV",    16],
            [    346,    "g_UV pulse",    4],
            [    350,    "g_rainbow good top",    16],
            [    350,    "g_green sidechain bottom pulse",    16],
            [    366,    "g_UV pulse",    1],
            [    367,    "g_UV pulse",    1],
            [    368,    "g_UV pulse",    2],
            [    370,    "g_solid top cycle",    16],
            [    370,    "g_UV",    16],
            [    386,    "g_solid mixed double",    16],
            [    386,    "g_UV",    16],
            [    402,    "g_solid top cycle",    16],
            [    402,    "g_green sidechain bottom pulse",    16],
            [    418,    "g_purple green bottom pulse",    16],
            [    418,    "g_UV",    16],
            [    434,    "g_solid mixed cycle",    16],
            [    450,    "g_purple green bottom pulse",    16],
            [    466,    "g_solid bottom cycle",    16],
            [    482,    "g_UV pulse",    2],
            [    484,    "g_solid mixed cycle",    16],
            [    500,    "g_purple green bottom pulse",    16],
            [    500,    "g_UV",    16],
            [    516,    "g_solid top cycle",    16],
            [    516,    "g_solid bottom cycle",    16],
            [    516,    "g_UV",    16],
            [    532,    "g_solid mixed cycle",    16],
            [    532,    "g_UV",    16],
            [    548,    "g_cyan top pulse",    16],
            [    548,    "g_solid bottom cycle",    16],
            [    548,    "g_UV",    16],
            [    564,    "g_UV pulse",    1],
            [    565,    "g_solid mixed cycle",    16],
            [    565,    "g_UV",    16],
            [    581,    "g_cyan top pulse",    16],
            [    581,    "g_purple green bottom pulse",    16],
            [    597,    "g_Strobe",    1],
            [    598,    "g_solid mixed double",    16],
            [    614,    "g_UV pulse",    4],
            [    618,    "RGB Flash",    1],
            [    619,    "g_solid mixed double",    16],
            [    635,    "g_green sidechain bottom pulse",    16],
            [    635,    "g_UV",    16],
            [    651,    "g_cyan top pulse",    16],
            [    651,    "g_purple green bottom pulse",    16],
            [    651,    "g_UV",    16],
            [    667,    "g_solid top cycle",    16],
            [    667,    "g_UV",    16],
            [    683,    "g_solid mixed double",    16],
            [    683,    "g_UV",    16]
        ],
        "bpm": 152,
        "delay_lights": 0.1215,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/s_\u30e8\u30eb\u30b7\u30ab  \u5de6\u53f3\u76f2OFFICIAL VIDEO.ogg",
        "was_autogenerated": True
    }
}