effects = {
    "g_s_Madeon  Technicolor": {
        "beats": [
            [    1,    "g_UV pulse",    4],
            [    5,    "g_solid bottom cycle",    16],
            [    5,    "g_UV",    16],
            [    21,    "g_UV pulse",    1],
            [    22,    "g_UV pulse",    4],
            [    26,    "g_UV pulse",    2],
            [    28,    "RGB Flash",    1],
            [    29,    "g_green sidechain bottom pulse",    16],
            [    29,    "g_UV",    16],
            [    45,    "RGB Flash",    1],
            [    46,    "g_UV pulse",    1],
            [    47,    "g_solid top cycle",    16],
            [    47,    "g_UV",    16],
            [    63,    "g_UV pulse",    1],
            [    64,    "RGB Flash",    1],
            [    65,    "g_UV pulse",    2],
            [    67,    "g_solid top cycle",    16],
            [    67,    "g_solid bottom cycle",    16],
            [    67,    "g_UV",    16],
            [    83,    "g_UV pulse",    1],
            [    84,    "g_UV pulse",    4],
            [    88,    "RGB Flash",    1],
            [    89,    "g_UV Strobe",    1],
            [    90,    "g_solid top cycle",    16],
            [    106,    "g_UV pulse",    2],
            [    108,    "g_solid mixed cycle",    16],
            [    108,    "g_UV",    16],
            [    124,    "g_solid top cycle",    16],
            [    124,    "g_solid bottom cycle",    16],
            [    140,    "g_solid top cycle",    16],
            [    140,    "g_solid bottom cycle",    16],
            [    140,    "g_UV",    16],
            [    156,    "RGB Flash",    1],
            [    157,    "g_UV pulse",    4],
            [    161,    "g_rainbow good top",    16],
            [    161,    "g_purple green bottom pulse",    16],
            [    177,    "g_cyan top pulse",    16],
            [    177,    "g_UV",    16],
            [    193,    "g_cyan top pulse",    16],
            [    193,    "g_green sidechain bottom pulse",    16],
            [    193,    "g_UV",    16],
            [    209,    "g_UV pulse",    2],
            [    211,    "g_UV pulse",    2],
            [    213,    "g_UV pulse",    2],
            [    215,    "g_cyan top pulse",    16],
            [    231,    "g_solid mixed double",    16],
            [    247,    "g_UV Strobe",    1],
            [    248,    "g_Strobe",    1],
            [    249,    "RGB Flash",    1],
            [    250,    "g_UV pulse",    2],
            [    252,    "g_solid top cycle",    16],
            [    252,    "g_solid bottom cycle",    16],
            [    252,    "g_UV",    16],
            [    268,    "RGB Flash",    1],
            [    269,    "g_green sidechain bottom pulse",    16],
            [    269,    "g_UV",    16],
            [    285,    "g_UV pulse",    4],
            [    289,    "g_solid mixed double",    16],
            [    305,    "g_green sidechain bottom pulse",    16],
            [    321,    "g_solid top cycle",    16],
            [    337,    "g_rainbow good top",    16],
            [    337,    "g_green sidechain bottom pulse",    16],
            [    353,    "g_solid bottom cycle",    16],
            [    353,    "g_UV",    16],
            [    369,    "g_UV Strobe",    1],
            [    370,    "g_UV pulse",    4],
            [    374,    "g_green sidechain bottom pulse",    16],
            [    390,    "g_cyan top pulse",    16],
            [    406,    "g_solid mixed cycle",    16],
            [    406,    "g_UV",    16],
            [    422,    "g_solid mixed double",    16],
            [    438,    "g_cyan top pulse",    16],
            [    438,    "g_purple green bottom pulse",    16],
            [    454,    "g_solid mixed double",    16],
            [    454,    "g_UV",    16],
            [    470,    "g_UV Strobe",    1],
            [    471,    "g_solid top cycle",    16],
            [    471,    "g_UV",    16],
            [    487,    "g_purple green bottom pulse",    16],
            [    503,    "g_UV pulse",    4],
            [    507,    "g_cyan top pulse",    16],
            [    507,    "g_UV",    16],
            [    523,    "g_cyan top pulse",    16],
            [    523,    "g_UV",    16],
            [    539,    "g_rainbow good slow top",    16],
            [    539,    "g_green sidechain bottom pulse",    16],
            [    555,    "g_solid top cycle",    16],
            [    555,    "g_purple green bottom pulse",    16],
            [    555,    "g_UV",    16],
            [    571,    "g_solid mixed double",    16],
            [    571,    "g_UV",    16],
            [    587,    "g_UV pulse",    1],
            [    588,    "RGB Flash",    1],
            [    589,    "g_green sidechain bottom pulse",    16],
            [    605,    "g_UV pulse",    2],
            [    607,    "g_solid bottom cycle",    16],
            [    607,    "g_UV",    16],
            [    623,    "g_cyan top pulse",    16],
            [    639,    "g_solid top cycle",    16],
            [    639,    "g_purple green bottom pulse",    16],
            [    655,    "g_purple green bottom pulse",    16],
            [    671,    "g_UV pulse",    1],
            [    672,    "g_purple green bottom pulse",    16],
            [    672,    "g_UV",    16],
            [    688,    "g_green sidechain bottom pulse",    16],
            [    688,    "g_UV",    16],
            [    704,    "g_purple green bottom pulse",    16],
            [    704,    "g_UV",    16],
            [    720,    "g_UV pulse",    4],
            [    724,    "g_UV pulse",    2],
            [    726,    "g_UV pulse",    4],
            [    730,    "g_solid top cycle",    16],
            [    730,    "g_UV",    16],
            [    746,    "g_solid mixed double",    16],
            [    746,    "g_UV",    16],
            [    762,    "g_Strobe",    1],
            [    763,    "g_solid top cycle",    16],
            [    763,    "g_purple green bottom pulse",    16],
            [    763,    "g_UV",    16],
            [    779,    "g_cyan top pulse",    16],
            [    779,    "g_purple green bottom pulse",    16],
            [    795,    "g_solid top cycle",    16]
        ],
        "bpm": 124,
        "delay_lights": 0.3598709677419355,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/s_Madeon  Technicolor.ogg",
        "was_autogenerated": True
    }
}