effects = {
    "g_s_Snails House  Kitty": {
        "beats": [
            [    1,    "g_UV pulse",    2],
            [    3,    "g_cyan top pulse",    16],
            [    3,    "g_green sidechain bottom pulse",    16],
            [    3,    "g_UV",    16],
            [    19,    "g_solid mixed cycle",    16],
            [    35,    "g_solid top cycle",    16],
            [    51,    "RGB Flash",    1],
            [    52,    "g_cyan top pulse",    16],
            [    52,    "g_purple green bottom pulse",    16],
            [    52,    "g_UV",    16],
            [    68,    "g_rainbow good slow top",    16],
            [    68,    "g_green sidechain bottom pulse",    16],
            [    84,    "g_green sidechain bottom pulse",    16],
            [    100,    "g_UV pulse",    1],
            [    101,    "g_cyan top pulse",    16],
            [    101,    "g_UV",    16],
            [    117,    "g_solid top cycle",    16],
            [    133,    "g_UV pulse",    4],
            [    137,    "g_rainbow good slow top",    16],
            [    137,    "g_solid bottom cycle",    16],
            [    153,    "RGB Flash",    1],
            [    154,    "g_solid mixed cycle",    16],
            [    154,    "g_UV",    16],
            [    170,    "g_rainbow good slow top",    16],
            [    170,    "g_green sidechain bottom pulse",    16],
            [    186,    "g_UV pulse",    4],
            [    190,    "g_solid top cycle",    16],
            [    190,    "g_UV",    16],
            [    206,    "g_rainbow good slow top",    16],
            [    206,    "g_purple green bottom pulse",    16],
            [    222,    "g_solid mixed double",    16],
            [    222,    "g_UV",    16],
            [    238,    "g_solid top cycle",    16],
            [    238,    "g_UV",    16],
            [    254,    "g_solid bottom cycle",    16],
            [    270,    "g_UV pulse",    1],
            [    271,    "g_UV pulse",    1],
            [    272,    "RGB Flash",    1],
            [    273,    "g_solid bottom cycle",    16],
            [    289,    "g_solid mixed cycle",    16],
            [    289,    "g_UV",    16],
            [    305,    "g_solid top cycle",    16],
            [    305,    "g_green sidechain bottom pulse",    16],
            [    305,    "g_UV",    16],
            [    321,    "g_UV pulse",    4],
            [    325,    "g_UV Strobe",    1],
            [    326,    "g_purple green bottom pulse",    16],
            [    326,    "g_UV",    16],
            [    342,    "g_cyan top pulse",    16],
            [    342,    "g_UV",    16],
            [    358,    "g_solid mixed double",    16],
            [    374,    "RGB Flash",    1],
            [    375,    "g_solid top cycle",    16],
            [    375,    "g_green sidechain bottom pulse",    16],
            [    375,    "g_UV",    16],
            [    391,    "g_UV pulse",    4],
            [    395,    "g_cyan top pulse",    16],
            [    395,    "g_green sidechain bottom pulse",    16],
            [    395,    "g_UV",    16],
            [    411,    "g_rainbow good top",    16],
            [    411,    "g_purple green bottom pulse",    16],
            [    427,    "g_cyan top pulse",    16],
            [    427,    "g_purple green bottom pulse",    16],
            [    443,    "g_rainbow good top",    16],
            [    443,    "g_purple green bottom pulse",    16],
            [    459,    "g_Strobe",    1],
            [    460,    "g_cyan top pulse",    16],
            [    460,    "g_UV",    16],
            [    476,    "g_solid top cycle",    16],
            [    476,    "g_purple green bottom pulse",    16],
            [    476,    "g_UV",    16],
            [    492,    "g_solid top cycle",    16],
            [    508,    "g_UV pulse",    2],
            [    510,    "g_UV pulse",    2],
            [    512,    "g_solid mixed double",    16],
            [    528,    "g_solid top cycle",    16],
            [    528,    "g_purple green bottom pulse",    16],
            [    544,    "g_Strobe",    1],
            [    545,    "g_solid top cycle",    16],
            [    545,    "g_purple green bottom pulse",    16],
            [    545,    "g_UV",    16],
            [    561,    "g_UV pulse",    1],
            [    562,    "g_UV pulse",    4],
            [    566,    "g_Strobe",    1],
            [    567,    "g_UV pulse",    4],
            [    571,    "g_rainbow good top",    16],
            [    571,    "g_solid bottom cycle",    16],
            [    587,    "g_UV Strobe",    1],
            [    588,    "g_UV pulse",    2],
            [    590,    "g_rainbow good top",    16],
            [    590,    "g_green sidechain bottom pulse",    16],
            [    606,    "g_solid mixed double",    16],
            [    606,    "g_UV",    16],
            [    622,    "g_green sidechain bottom pulse",    16],
            [    638,    "g_solid top cycle",    16],
            [    638,    "g_purple green bottom pulse",    16],
            [    654,    "g_solid bottom cycle",    16],
            [    670,    "g_solid mixed double",    16],
            [    686,    "g_solid mixed cycle",    16]
        ],
        "bpm": 182,
        "delay_lights": 0.19417032967032966,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/s_Snails House  Kitty.ogg",
        "was_autogenerated": True
    }
}