effects = {
    "g_s_Madeon  Beings Audio": {
        "beats": [
            [    1,    "Rainbow bad",    2],
            [    1,    "Rainbow bad",    2],
            [    3,    "Ghosts riser",    4],
            [    3,    "Ghosts riser",    4],
            [    7,    "Autogen bassline top",    2],
            [    7,    "Autogen bassline sidechain bottom",    2],
            [    9,    "Autogen UV Strobe",    1],
            [    9,    "hooked wandering top",    16],
            [    25,    "hooked wandering top",    16],
            [    25,    "Rainbow bad",    2],
            [    41,    "Autogen bassline bottom",    2],
            [    41,    "Autogen UV Strobe",    1],
            [    43,    "hooked wandering top",    16],
            [    43,    "UV pulse slow",    2],
            [    59,    "Autogen bassline bottom",    2],
            [    59,    "Autogen bassline top",    2],
            [    61,    "Ghosts riser",    4],
            [    61,    "Autogen Strobe",    1],
            [    65,    "Autogen bassline bottom",    2],
            [    65,    "Ghosts riser",    4],
            [    69,    "Rainbow bad",    2],
            [    69,    "UV pulse slow",    2],
            [    71,    "UV pulse slow",    2],
            [    71,    "UV pulse slow",    2],
            [    73,    "UV pulse",    1],
            [    73,    "Rainbow bad",    2],
            [    75,    "Rainbow bad",    2],
            [    75,    "RBBB 1 bar",    4],
            [    79,    "hooked wandering top",    16],
            [    79,    "hooked wandering top",    16],
            [    95,    "rainbow good slow top",    16],
            [    95,    "Autogen bassline top",    2],
            [    111,    "Autogen UV Strobe",    1],
            [    111,    "rainbow good slow top",    16],
            [    127,    "Autogen UV Strobe",    1],
            [    127,    "RBBB 1 bar",    4],
            [    131,    "hooked wandering top",    16],
            [    131,    "hooked wandering bottom",    16],
            [    147,    "hooked wandering top",    16],
            [    147,    "Ghosts riser",    4],
            [    163,    "hooked wandering bottom",    16],
            [    163,    "Autogen bassline bottom",    2],
            [    179,    "RBBB 1 bar",    4],
            [    179,    "rainbow good slow top",    16],
            [    195,    "UV pulse slow",    2],
            [    195,    "Autogen bassline sidechain bottom",    2],
            [    197,    "rainbow good slow top",    16],
            [    197,    "UV pulse slow",    2],
            [    213,    "Autogen bassline top",    2],
            [    213,    "UV pulse slow",    2],
            [    215,    "hooked wandering top",    16],
            [    215,    "hooked wandering top",    16],
            [    231,    "hooked wandering bottom",    16],
            [    231,    "UV pulse",    1],
            [    247,    "Autogen bassline bottom",    2],
            [    247,    "UV pulse slow",    2],
            [    249,    "UV pulse",    1],
            [    249,    "Rainbow bad",    2],
            [    251,    "hooked wandering bottom",    16],
            [    251,    "hooked wandering bottom",    16],
            [    267,    "UV pulse",    1],
            [    267,    "Autogen UV Strobe",    1],
            [    268,    "rainbow good slow top",    16],
            [    268,    "Autogen bassline top",    2],
            [    284,    "rainbow good slow top",    16],
            [    284,    "Autogen bassline top",    2],
            [    300,    "Autogen UV Strobe",    1],
            [    300,    "RBBB 1 bar",    4],
            [    304,    "Autogen Strobe",    1],
            [    304,    "hooked wandering top",    16],
            [    320,    "Autogen bassline sidechain bottom",    2],
            [    320,    "Autogen bassline bottom",    2],
            [    322,    "rainbow good slow top",    16],
            [    322,    "Autogen Strobe",    1],
            [    338,    "hooked wandering top",    16],
            [    338,    "Rainbow bad",    2],
            [    354,    "rainbow good slow top",    16],
            [    354,    "hooked wandering bottom",    16],
            [    370,    "UV pulse",    1],
            [    370,    "Autogen bassline bottom",    2],
            [    372,    "Rainbow bad",    2],
            [    372,    "Autogen Strobe",    1],
            [    374,    "hooked wandering top",    16],
            [    374,    "Autogen Strobe",    1]
        ],
        "bpm": 106,
        "delay_lights": 0.3915377358490566,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "/home/andrew/programming/python/light-show/songs/s_Madeon  Beings Audio.ogg"
    }
}