effects = {
    "g_s_\u30e8\u30eb\u30b7\u30ab  \u5de6\u53f3\u76f2OFFICIAL VIDEO": {
        "beats": [
            [    1,    "Autogen Strobe",    1],
            [    1,    "hooked wandering top",    16],
            [    17,    "Autogen Strobe",    1],
            [    17,    "UV pulse slow",    2],
            [    19,    "Autogen bassline sidechain bottom",    2],
            [    19,    "Rainbow bad",    2],
            [    21,    "rainbow good slow top",    16],
            [    21,    "rainbow good slow top",    16],
            [    37,    "UV pulse slow",    2],
            [    37,    "Rainbow bad",    2],
            [    39,    "Autogen Strobe",    1],
            [    39,    "Autogen UV Strobe",    1],
            [    40,    "Autogen UV Strobe",    1],
            [    40,    "Autogen UV Strobe",    1],
            [    41,    "Autogen Strobe",    1],
            [    41,    "Autogen bassline top",    2],
            [    43,    "Autogen bassline top",    2],
            [    43,    "UV pulse slow",    2],
            [    45,    "rainbow good slow top",    16],
            [    45,    "Autogen bassline sidechain bottom",    2],
            [    61,    "UV pulse",    1],
            [    61,    "Ghosts riser",    4],
            [    65,    "rainbow good slow top",    16],
            [    65,    "Autogen UV Strobe",    1],
            [    81,    "Autogen UV Strobe",    1],
            [    81,    "UV pulse slow",    2],
            [    83,    "Autogen UV Strobe",    1],
            [    83,    "hooked wandering top",    16],
            [    99,    "Rainbow bad",    2],
            [    99,    "Rainbow bad",    2],
            [    101,    "Autogen bassline bottom",    2],
            [    101,    "hooked wandering top",    16],
            [    117,    "Autogen bassline top",    2],
            [    117,    "Ghosts riser",    4],
            [    121,    "Autogen bassline sidechain bottom",    2],
            [    121,    "hooked wandering top",    16],
            [    137,    "RBBB 1 bar",    4],
            [    137,    "UV pulse slow",    2],
            [    141,    "UV pulse",    1],
            [    141,    "Autogen Strobe",    1],
            [    142,    "UV pulse slow",    2],
            [    142,    "UV pulse slow",    2],
            [    144,    "Ghosts riser",    4],
            [    144,    "Autogen bassline sidechain bottom",    2],
            [    148,    "Autogen UV Strobe",    1],
            [    148,    "UV pulse",    1],
            [    149,    "Ghosts riser",    4],
            [    149,    "rainbow good slow top",    16],
            [    165,    "Autogen UV Strobe",    1],
            [    165,    "Ghosts riser",    4],
            [    169,    "Autogen Strobe",    1],
            [    169,    "Autogen bassline sidechain bottom",    2],
            [    171,    "RBBB 1 bar",    4],
            [    171,    "hooked wandering bottom",    16],
            [    187,    "hooked wandering top",    16],
            [    187,    "Autogen Strobe",    1],
            [    203,    "UV pulse",    1],
            [    203,    "hooked wandering bottom",    16],
            [    219,    "Autogen bassline bottom",    2],
            [    219,    "hooked wandering bottom",    16],
            [    235,    "rainbow good slow top",    16],
            [    235,    "RBBB 1 bar",    4],
            [    251,    "Autogen bassline bottom",    2],
            [    251,    "hooked wandering bottom",    16],
            [    267,    "Autogen UV Strobe",    1],
            [    267,    "UV pulse",    1],
            [    268,    "rainbow good slow top",    16],
            [    268,    "Ghosts riser",    4],
            [    284,    "Autogen Strobe",    1],
            [    284,    "Autogen bassline bottom",    2],
            [    286,    "rainbow good slow top",    16],
            [    286,    "rainbow good slow top",    16],
            [    302,    "RBBB 1 bar",    4],
            [    302,    "hooked wandering bottom",    16],
            [    318,    "Autogen Strobe",    1],
            [    318,    "UV pulse slow",    2],
            [    320,    "UV pulse",    1],
            [    320,    "RBBB 1 bar",    4],
            [    324,    "hooked wandering bottom",    16],
            [    324,    "RBBB 1 bar",    4],
            [    340,    "Autogen Strobe",    1],
            [    340,    "RBBB 1 bar",    4],
            [    344,    "hooked wandering top",    16],
            [    344,    "hooked wandering bottom",    16],
            [    360,    "Rainbow bad",    2],
            [    360,    "hooked wandering bottom",    16],
            [    376,    "hooked wandering top",    16],
            [    376,    "rainbow good slow top",    16],
            [    392,    "Ghosts riser",    4],
            [    392,    "hooked wandering top",    16],
            [    408,    "hooked wandering bottom",    16],
            [    408,    "hooked wandering bottom",    16],
            [    424,    "Autogen bassline bottom",    2],
            [    424,    "hooked wandering top",    16],
            [    440,    "hooked wandering bottom",    16],
            [    440,    "Autogen UV Strobe",    1],
            [    456,    "UV pulse",    1],
            [    456,    "Ghosts riser",    4],
            [    460,    "hooked wandering bottom",    16],
            [    460,    "Autogen UV Strobe",    1],
            [    476,    "Autogen bassline bottom",    2],
            [    476,    "RBBB 1 bar",    4],
            [    480,    "Autogen UV Strobe",    1],
            [    480,    "RBBB 1 bar",    4],
            [    484,    "Ghosts riser",    4],
            [    484,    "UV pulse",    1],
            [    488,    "hooked wandering top",    16],
            [    488,    "Autogen bassline bottom",    2],
            [    504,    "Autogen bassline top",    2],
            [    504,    "Rainbow bad",    2],
            [    506,    "Autogen Strobe",    1],
            [    506,    "hooked wandering top",    16],
            [    522,    "Autogen bassline bottom",    2],
            [    522,    "Autogen bassline bottom",    2],
            [    524,    "UV pulse",    1],
            [    524,    "RBBB 1 bar",    4],
            [    528,    "hooked wandering top",    16],
            [    528,    "Autogen Strobe",    1],
            [    544,    "RBBB 1 bar",    4],
            [    544,    "UV pulse slow",    2],
            [    548,    "hooked wandering top",    16],
            [    548,    "Autogen UV Strobe",    1],
            [    564,    "hooked wandering bottom",    16],
            [    564,    "hooked wandering bottom",    16],
            [    580,    "Autogen UV Strobe",    1],
            [    580,    "rainbow good slow top",    16],
            [    596,    "rainbow good slow top",    16],
            [    596,    "Autogen bassline bottom",    2],
            [    612,    "Ghosts riser",    4],
            [    612,    "Autogen bassline sidechain bottom",    2],
            [    616,    "Rainbow bad",    2],
            [    616,    "rainbow good slow top",    16],
            [    632,    "RBBB 1 bar",    4],
            [    632,    "Autogen bassline bottom",    2],
            [    636,    "hooked wandering top",    16],
            [    636,    "RBBB 1 bar",    4],
            [    652,    "hooked wandering bottom",    16],
            [    652,    "rainbow good slow top",    16],
            [    668,    "Ghosts riser",    4],
            [    668,    "UV pulse slow",    2],
            [    672,    "Autogen bassline top",    2],
            [    672,    "UV pulse",    1],
            [    674,    "RBBB 1 bar",    4],
            [    674,    "Ghosts riser",    4],
            [    678,    "Rainbow bad",    2],
            [    678,    "Autogen bassline sidechain bottom",    2],
            [    680,    "Autogen bassline bottom",    2],
            [    680,    "Autogen bassline top",    2],
            [    682,    "RBBB 1 bar",    4],
            [    682,    "RBBB 1 bar",    4],
            [    686,    "UV pulse slow",    2],
            [    686,    "Rainbow bad",    2]
        ],
        "bpm": 152,
        "delay_lights": 0.1215,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/s_\u30e8\u30eb\u30b7\u30ab  \u5de6\u53f3\u76f2OFFICIAL VIDEO.ogg"
    }
}