effects = {
    "g_Sakamoto Maaya - Okaerinasai (tomatomerde Remix)": {
        "beats": [
            [    1,    "hooked wandering bottom",    16],
            [    1,    "rainbow good slow top",    16],
            [    17,    "Autogen bassline bottom",    2],
            [    17,    "UV pulse",    1],
            [    19,    "rainbow good slow top",    16],
            [    19,    "UV pulse slow",    2],
            [    35,    "hooked wandering bottom",    16],
            [    35,    "Autogen bassline bottom",    2],
            [    51,    "Ghosts riser",    4],
            [    51,    "Autogen bassline bottom",    2],
            [    55,    "Autogen Strobe",    1],
            [    55,    "Ghosts riser",    4],
            [    59,    "Autogen Strobe",    1],
            [    59,    "Autogen bassline bottom",    2],
            [    61,    "rainbow good slow top",    16],
            [    61,    "Autogen bassline top",    2],
            [    77,    "hooked wandering top",    16],
            [    77,    "Rainbow bad",    2],
            [    93,    "hooked wandering top",    16],
            [    93,    "Autogen Strobe",    1],
            [    109,    "Autogen bassline bottom",    2],
            [    109,    "RBBB 1 bar",    4],
            [    113,    "Ghosts riser",    4],
            [    113,    "Autogen Strobe",    1],
            [    117,    "Ghosts riser",    4],
            [    117,    "UV pulse",    1],
            [    121,    "hooked wandering top",    16],
            [    121,    "Autogen bassline top",    2],
            [    137,    "rainbow good slow top",    16],
            [    137,    "RBBB 1 bar",    4],
            [    153,    "Autogen Strobe",    1],
            [    153,    "Autogen bassline bottom",    2],
            [    155,    "Autogen bassline top",    2],
            [    155,    "Rainbow bad",    2],
            [    157,    "Autogen bassline sidechain bottom",    2],
            [    157,    "Autogen bassline top",    2],
            [    159,    "UV pulse",    1],
            [    159,    "UV pulse slow",    2],
            [    161,    "Rainbow bad",    2],
            [    161,    "Autogen UV Strobe",    1],
            [    163,    "Autogen bassline sidechain bottom",    2],
            [    163,    "rainbow good slow top",    16],
            [    179,    "Rainbow bad",    2],
            [    179,    "rainbow good slow top",    16],
            [    195,    "UV pulse",    1],
            [    195,    "Ghosts riser",    4],
            [    199,    "UV pulse",    1],
            [    199,    "Ghosts riser",    4],
            [    203,    "Autogen bassline bottom",    2],
            [    203,    "UV pulse slow",    2],
            [    205,    "Autogen UV Strobe",    1],
            [    205,    "RBBB 1 bar",    4],
            [    209,    "Rainbow bad",    2],
            [    209,    "hooked wandering bottom",    16],
            [    225,    "Autogen bassline sidechain bottom",    2],
            [    225,    "Autogen UV Strobe",    1],
            [    227,    "hooked wandering top",    16],
            [    227,    "Autogen Strobe",    1],
            [    243,    "Autogen bassline bottom",    2],
            [    243,    "rainbow good slow top",    16],
            [    259,    "UV pulse",    1],
            [    259,    "hooked wandering bottom",    16],
            [    275,    "UV pulse",    1],
            [    275,    "hooked wandering bottom",    16],
            [    291,    "Ghosts riser",    4],
            [    291,    "hooked wandering bottom",    16],
            [    307,    "hooked wandering top",    16],
            [    307,    "Rainbow bad",    2],
            [    323,    "UV pulse slow",    2],
            [    323,    "UV pulse slow",    2],
            [    325,    "Ghosts riser",    4],
            [    325,    "Rainbow bad",    2],
            [    329,    "hooked wandering top",    16],
            [    329,    "Autogen bassline top",    2],
            [    345,    "hooked wandering top",    16],
            [    345,    "RBBB 1 bar",    4],
            [    361,    "hooked wandering top",    16],
            [    361,    "hooked wandering top",    16],
            [    377,    "hooked wandering top",    16],
            [    377,    "Autogen Strobe",    1],
            [    393,    "UV pulse slow",    2],
            [    393,    "UV pulse slow",    2],
            [    395,    "hooked wandering bottom",    16],
            [    395,    "Ghosts riser",    4],
            [    411,    "Rainbow bad",    2],
            [    411,    "Autogen bassline bottom",    2],
            [    413,    "Rainbow bad",    2],
            [    413,    "UV pulse slow",    2],
            [    415,    "Autogen bassline bottom",    2],
            [    415,    "Autogen Strobe",    1],
            [    417,    "hooked wandering bottom",    16],
            [    417,    "Autogen bassline bottom",    2],
            [    433,    "Ghosts riser",    4],
            [    433,    "RBBB 1 bar",    4],
            [    437,    "rainbow good slow top",    16],
            [    437,    "rainbow good slow top",    16],
            [    453,    "Autogen Strobe",    1],
            [    453,    "Autogen UV Strobe",    1],
            [    454,    "hooked wandering top",    16],
            [    454,    "UV pulse",    1],
            [    470,    "UV pulse",    1],
            [    470,    "Autogen bassline top",    2],
            [    472,    "Autogen bassline top",    2],
            [    472,    "RBBB 1 bar",    4],
            [    476,    "UV pulse",    1],
            [    476,    "Autogen bassline sidechain bottom",    2],
            [    478,    "RBBB 1 bar",    4],
            [    478,    "Rainbow bad",    2],
            [    482,    "Autogen Strobe",    1],
            [    482,    "UV pulse",    1],
            [    483,    "UV pulse",    1],
            [    483,    "hooked wandering bottom",    16],
            [    499,    "Autogen Strobe",    1],
            [    499,    "Autogen UV Strobe",    1],
            [    500,    "UV pulse",    1],
            [    500,    "Autogen bassline bottom",    2],
            [    502,    "Autogen bassline bottom",    2],
            [    502,    "Autogen bassline top",    2],
            [    504,    "Autogen UV Strobe",    1],
            [    504,    "Autogen bassline bottom",    2],
            [    506,    "Autogen UV Strobe",    1],
            [    506,    "hooked wandering bottom",    16],
            [    522,    "Autogen bassline top",    2],
            [    522,    "UV pulse slow",    2],
            [    524,    "Autogen UV Strobe",    1],
            [    524,    "Autogen bassline bottom",    2],
            [    526,    "Autogen Strobe",    1],
            [    526,    "UV pulse slow",    2],
            [    528,    "Ghosts riser",    4],
            [    528,    "Autogen UV Strobe",    1],
            [    532,    "hooked wandering bottom",    16],
            [    532,    "RBBB 1 bar",    4],
            [    548,    "hooked wandering top",    16],
            [    548,    "UV pulse",    1],
            [    564,    "Autogen bassline sidechain bottom",    2],
            [    564,    "Rainbow bad",    2],
            [    566,    "Autogen bassline top",    2],
            [    566,    "hooked wandering top",    16],
            [    582,    "Ghosts riser",    4],
            [    582,    "Rainbow bad",    2],
            [    586,    "UV pulse",    1],
            [    586,    "Ghosts riser",    4],
            [    590,    "UV pulse slow",    2],
            [    590,    "hooked wandering bottom",    16],
            [    606,    "hooked wandering bottom",    16],
            [    606,    "hooked wandering bottom",    16],
            [    622,    "hooked wandering bottom",    16],
            [    622,    "Autogen UV Strobe",    1],
            [    638,    "Autogen bassline top",    2],
            [    638,    "rainbow good slow top",    16],
            [    654,    "Autogen Strobe",    1],
            [    654,    "hooked wandering bottom",    16],
            [    670,    "Rainbow bad",    2],
            [    670,    "Autogen bassline bottom",    2],
            [    672,    "Ghosts riser",    4],
            [    672,    "hooked wandering bottom",    16],
            [    688,    "hooked wandering bottom",    16],
            [    688,    "Autogen bassline top",    2],
            [    704,    "RBBB 1 bar",    4],
            [    704,    "hooked wandering top",    16],
            [    720,    "rainbow good slow top",    16],
            [    720,    "Rainbow bad",    2],
            [    736,    "Autogen bassline top",    2],
            [    736,    "Autogen UV Strobe",    1],
            [    738,    "Autogen bassline sidechain bottom",    2],
            [    738,    "Autogen bassline bottom",    2],
            [    740,    "rainbow good slow top",    16],
            [    740,    "Autogen bassline bottom",    2],
            [    756,    "Autogen bassline top",    2],
            [    756,    "hooked wandering top",    16],
            [    772,    "Autogen bassline bottom",    2],
            [    772,    "Autogen bassline sidechain bottom",    2],
            [    774,    "hooked wandering top",    16],
            [    774,    "rainbow good slow top",    16],
            [    790,    "hooked wandering top",    16],
            [    790,    "RBBB 1 bar",    4],
            [    806,    "hooked wandering bottom",    16],
            [    806,    "UV pulse",    1],
            [    822,    "hooked wandering bottom",    16],
            [    822,    "Autogen UV Strobe",    1],
            [    838,    "UV pulse slow",    2],
            [    838,    "Autogen bassline sidechain bottom",    2],
            [    840,    "UV pulse slow",    2],
            [    840,    "Autogen bassline bottom",    2],
            [    842,    "UV pulse",    1],
            [    842,    "hooked wandering top",    16],
            [    858,    "RBBB 1 bar",    4],
            [    858,    "Rainbow bad",    2],
            [    862,    "UV pulse slow",    2],
            [    862,    "Ghosts riser",    4],
            [    866,    "Autogen bassline bottom",    2],
            [    866,    "hooked wandering bottom",    16],
            [    882,    "UV pulse",    1],
            [    882,    "Autogen bassline top",    2],
            [    884,    "Ghosts riser",    4],
            [    884,    "hooked wandering bottom",    16],
            [    900,    "Autogen bassline sidechain bottom",    2],
            [    900,    "Autogen bassline top",    2],
            [    902,    "Autogen UV Strobe",    1],
            [    902,    "Autogen Strobe",    1],
            [    903,    "Autogen Strobe",    1],
            [    903,    "UV pulse",    1],
            [    904,    "Autogen bassline sidechain bottom",    2],
            [    904,    "Autogen bassline top",    2],
            [    906,    "Autogen bassline top",    2],
            [    906,    "hooked wandering bottom",    16],
            [    922,    "Rainbow bad",    2],
            [    922,    "rainbow good slow top",    16],
            [    938,    "Autogen bassline bottom",    2],
            [    938,    "hooked wandering bottom",    16],
            [    954,    "Autogen bassline top",    2],
            [    954,    "hooked wandering top",    16],
            [    970,    "Autogen bassline sidechain bottom",    2],
            [    970,    "Autogen bassline sidechain bottom",    2],
            [    972,    "rainbow good slow top",    16],
            [    972,    "Ghosts riser",    4],
            [    988,    "RBBB 1 bar",    4],
            [    988,    "Autogen bassline sidechain bottom",    2],
            [    992,    "Rainbow bad",    2],
            [    992,    "Ghosts riser",    4],
            [    996,    "UV pulse slow",    2],
            [    996,    "hooked wandering bottom",    16],
            [    1012,    "hooked wandering top",    16],
            [    1012,    "Autogen bassline bottom",    2],
            [    1028,    "Ghosts riser",    4],
            [    1028,    "hooked wandering top",    16],
            [    1044,    "Ghosts riser",    4],
            [    1044,    "Autogen bassline sidechain bottom",    2],
            [    1048,    "Autogen bassline bottom",    2],
            [    1048,    "RBBB 1 bar",    4],
            [    1052,    "RBBB 1 bar",    4],
            [    1052,    "rainbow good slow top",    16],
            [    1068,    "Autogen bassline top",    2],
            [    1068,    "Autogen UV Strobe",    1],
            [    1070,    "UV pulse slow",    2],
            [    1070,    "Rainbow bad",    2],
            [    1072,    "Autogen bassline sidechain bottom",    2],
            [    1072,    "Autogen bassline top",    2],
            [    1074,    "hooked wandering bottom",    16],
            [    1074,    "hooked wandering top",    16]
        ],
        "bpm": 176,
        "delay_lights": 0.14,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/Sakamoto Maaya - Okaerinasai (tomatomerde Remix).ogg"
    }
}