effects = {
    "g_Sakamoto Maaya - Okaerinasai (tomatomerde Remix)": {
        "beats": [
            [    1,    "g_UV pulse",    4],
            [    5,    "g_UV pulse",    1],
            [    6,    "g_solid top cycle",    16],
            [    22,    "g_solid mixed cycle",    16],
            [    38,    "g_cyan top pulse",    16],
            [    38,    "g_green sidechain bottom pulse",    16],
            [    54,    "g_solid top cycle",    16],
            [    70,    "g_solid mixed cycle",    16],
            [    86,    "RGB Flash",    1],
            [    87,    "g_cyan top pulse",    16],
            [    87,    "g_solid bottom cycle",    16],
            [    87,    "g_UV",    16],
            [    103,    "g_rainbow good top",    16],
            [    103,    "g_green sidechain bottom pulse",    16],
            [    119,    "g_UV pulse",    1],
            [    120,    "g_solid mixed cycle",    16],
            [    120,    "g_UV",    16],
            [    136,    "g_cyan top pulse",    16],
            [    136,    "g_green sidechain bottom pulse",    16],
            [    152,    "g_UV pulse",    1],
            [    153,    "g_purple green bottom pulse",    16],
            [    153,    "g_UV",    16],
            [    169,    "g_solid mixed cycle",    16],
            [    169,    "g_UV",    16],
            [    185,    "g_UV pulse",    2],
            [    187,    "g_solid top cycle",    16],
            [    187,    "g_UV",    16],
            [    203,    "g_Strobe",    1],
            [    204,    "g_solid top cycle",    16],
            [    204,    "g_UV",    16],
            [    220,    "g_rainbow good top",    16],
            [    220,    "g_purple green bottom pulse",    16],
            [    236,    "g_rainbow good top",    16],
            [    236,    "g_green sidechain bottom pulse",    16],
            [    252,    "RGB Flash",    1],
            [    253,    "g_solid top cycle",    16],
            [    253,    "g_purple green bottom pulse",    16],
            [    253,    "g_UV",    16],
            [    269,    "g_UV pulse",    2],
            [    271,    "RGB Flash",    1],
            [    272,    "g_solid top cycle",    16],
            [    272,    "g_purple green bottom pulse",    16],
            [    272,    "g_UV",    16],
            [    288,    "g_solid mixed double",    16],
            [    288,    "g_UV",    16],
            [    304,    "g_cyan top pulse",    16],
            [    304,    "g_UV",    16],
            [    320,    "g_rainbow good slow top",    16],
            [    320,    "g_purple green bottom pulse",    16],
            [    336,    "g_purple green bottom pulse",    16],
            [    352,    "g_rainbow good slow top",    16],
            [    352,    "g_purple green bottom pulse",    16],
            [    368,    "g_purple green bottom pulse",    16],
            [    384,    "g_green sidechain bottom pulse",    16],
            [    400,    "g_cyan top pulse",    16],
            [    416,    "RGB Flash",    1],
            [    417,    "g_solid top cycle",    16],
            [    417,    "g_purple green bottom pulse",    16],
            [    417,    "g_UV",    16],
            [    433,    "g_solid mixed double",    16],
            [    433,    "g_UV",    16],
            [    449,    "RGB Flash",    1],
            [    450,    "g_solid mixed cycle",    16],
            [    466,    "g_cyan top pulse",    16],
            [    466,    "g_green sidechain bottom pulse",    16],
            [    482,    "g_solid bottom cycle",    16],
            [    482,    "g_UV",    16],
            [    498,    "g_solid mixed cycle",    16],
            [    498,    "g_UV",    16],
            [    514,    "g_UV pulse",    2],
            [    516,    "g_solid top cycle",    16],
            [    516,    "g_purple green bottom pulse",    16],
            [    532,    "g_UV pulse",    1],
            [    533,    "RGB Flash",    1],
            [    534,    "g_rainbow good top",    16],
            [    534,    "g_solid bottom cycle",    16],
            [    550,    "g_solid mixed cycle",    16],
            [    550,    "g_UV",    16],
            [    566,    "g_solid mixed double",    16],
            [    582,    "g_cyan top pulse",    16],
            [    582,    "g_green sidechain bottom pulse",    16],
            [    582,    "g_UV",    16],
            [    598,    "g_UV pulse",    1],
            [    599,    "g_UV pulse",    1],
            [    600,    "g_solid mixed cycle",    16],
            [    600,    "g_UV",    16],
            [    616,    "g_solid mixed cycle",    16],
            [    616,    "g_UV",    16],
            [    632,    "g_solid top cycle",    16],
            [    632,    "g_UV",    16],
            [    648,    "g_rainbow good slow top",    16],
            [    648,    "g_solid bottom cycle",    16],
            [    664,    "g_rainbow good top",    16],
            [    664,    "g_solid bottom cycle",    16],
            [    680,    "g_solid bottom cycle",    16],
            [    696,    "RGB Flash",    1],
            [    697,    "g_solid top cycle",    16],
            [    713,    "g_rainbow good top",    16],
            [    713,    "g_green sidechain bottom pulse",    16],
            [    729,    "g_UV pulse",    1],
            [    730,    "g_solid mixed cycle",    16],
            [    730,    "g_UV",    16],
            [    746,    "g_solid top cycle",    16],
            [    746,    "g_UV",    16],
            [    762,    "g_solid mixed cycle",    16],
            [    778,    "g_cyan top pulse",    16],
            [    778,    "g_purple green bottom pulse",    16],
            [    778,    "g_UV",    16],
            [    794,    "g_solid mixed cycle",    16],
            [    810,    "g_UV pulse",    4],
            [    814,    "g_Strobe",    1],
            [    815,    "g_solid mixed double",    16],
            [    831,    "g_cyan top pulse",    16],
            [    831,    "g_purple green bottom pulse",    16],
            [    847,    "g_rainbow good top",    16],
            [    847,    "g_purple green bottom pulse",    16],
            [    863,    "g_solid top cycle",    16],
            [    863,    "g_green sidechain bottom pulse",    16],
            [    863,    "g_UV",    16],
            [    879,    "g_cyan top pulse",    16],
            [    879,    "g_green sidechain bottom pulse",    16],
            [    895,    "RGB Flash",    1],
            [    896,    "g_cyan top pulse",    16],
            [    896,    "g_solid bottom cycle",    16],
            [    896,    "g_UV",    16],
            [    912,    "g_solid top cycle",    16],
            [    912,    "g_purple green bottom pulse",    16],
            [    912,    "g_UV",    16],
            [    928,    "g_UV pulse",    4],
            [    932,    "g_UV pulse",    4],
            [    936,    "g_UV pulse",    1],
            [    937,    "g_UV pulse",    2],
            [    939,    "g_UV pulse",    4],
            [    943,    "g_solid top cycle",    16],
            [    943,    "g_UV",    16],
            [    959,    "g_UV pulse",    1],
            [    960,    "g_solid top cycle",    16],
            [    960,    "g_solid bottom cycle",    16],
            [    960,    "g_UV",    16],
            [    976,    "g_solid mixed double",    16],
            [    976,    "g_UV",    16],
            [    992,    "g_UV pulse",    2],
            [    994,    "RGB Flash",    1],
            [    995,    "g_UV pulse",    1],
            [    996,    "g_solid mixed cycle",    16],
            [    996,    "g_UV",    16],
            [    1012,    "g_green sidechain bottom pulse",    16],
            [    1028,    "g_UV pulse",    1],
            [    1029,    "g_green sidechain bottom pulse",    16],
            [    1029,    "g_UV",    16],
            [    1045,    "g_rainbow good top",    16],
            [    1045,    "g_green sidechain bottom pulse",    16],
            [    1061,    "g_UV pulse",    2],
            [    1063,    "g_Strobe",    1],
            [    1064,    "g_solid top cycle",    16],
            [    1064,    "g_UV",    16]
        ],
        "bpm": 176,
        "delay_lights": 0.14,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/Sakamoto Maaya - Okaerinasai (tomatomerde Remix).ogg",
        "was_autogenerated": True
    }
}