effects = {
    "g_Sakamoto Maaya - Okaerinasai (tomatomerde Remix)": {
        "beats": [
            [    1,    "Autogen UV Strobe",    1],
            [    1,    "UV pulse",    1],
            [    2,    "Autogen UV Strobe",    1],
            [    2,    "Autogen Strobe",    1],
            [    3,    "Autogen bassline bottom",    2],
            [    3,    "Rainbow bad",    2],
            [    5,    "Autogen UV Strobe",    1],
            [    5,    "RBBB 1 bar",    4],
            [    9,    "UV pulse slow",    2],
            [    9,    "Autogen bassline top",    2],
            [    11,    "Ghosts riser",    4],
            [    11,    "rainbow good slow top",    16],
            [    27,    "Autogen bassline bottom",    2],
            [    27,    "hooked wandering bottom",    16],
            [    43,    "Autogen UV Strobe",    1],
            [    43,    "Autogen Strobe",    1],
            [    44,    "hooked wandering top",    16],
            [    44,    "RBBB 1 bar",    4],
            [    60,    "Autogen bassline bottom",    2],
            [    60,    "Rainbow bad",    2],
            [    62,    "rainbow good slow top",    16],
            [    62,    "Autogen Strobe",    1],
            [    78,    "UV pulse slow",    2],
            [    78,    "Rainbow bad",    2],
            [    80,    "hooked wandering bottom",    16],
            [    80,    "Rainbow bad",    2],
            [    96,    "Ghosts riser",    4],
            [    96,    "Autogen bassline sidechain bottom",    2],
            [    100,    "Autogen bassline top",    2],
            [    100,    "Ghosts riser",    4],
            [    104,    "hooked wandering bottom",    16],
            [    104,    "Autogen Strobe",    1],
            [    120,    "Rainbow bad",    2],
            [    120,    "hooked wandering top",    16],
            [    136,    "rainbow good slow top",    16],
            [    136,    "Ghosts riser",    4],
            [    152,    "Ghosts riser",    4],
            [    152,    "Autogen bassline sidechain bottom",    2],
            [    156,    "hooked wandering bottom",    16],
            [    156,    "Autogen Strobe",    1],
            [    172,    "Autogen bassline sidechain bottom",    2],
            [    172,    "rainbow good slow top",    16],
            [    188,    "hooked wandering bottom",    16],
            [    188,    "Autogen UV Strobe",    1],
            [    204,    "UV pulse",    1],
            [    204,    "Autogen bassline top",    2],
            [    206,    "Rainbow bad",    2],
            [    206,    "hooked wandering bottom",    16],
            [    222,    "Rainbow bad",    2],
            [    222,    "Autogen Strobe",    1],
            [    224,    "Rainbow bad",    2],
            [    224,    "RBBB 1 bar",    4],
            [    228,    "Autogen bassline bottom",    2],
            [    228,    "Autogen UV Strobe",    1],
            [    230,    "RBBB 1 bar",    4],
            [    230,    "Autogen bassline top",    2],
            [    234,    "Autogen bassline top",    2],
            [    234,    "Autogen bassline sidechain bottom",    2],
            [    236,    "RBBB 1 bar",    4],
            [    236,    "Autogen bassline sidechain bottom",    2],
            [    240,    "Autogen bassline sidechain bottom",    2],
            [    240,    "hooked wandering top",    16],
            [    256,    "Autogen Strobe",    1],
            [    256,    "Autogen Strobe",    1],
            [    257,    "RBBB 1 bar",    4],
            [    257,    "UV pulse",    1],
            [    261,    "rainbow good slow top",    16],
            [    261,    "hooked wandering top",    16],
            [    277,    "UV pulse",    1],
            [    277,    "Autogen bassline sidechain bottom",    2],
            [    279,    "UV pulse slow",    2],
            [    279,    "Autogen bassline bottom",    2],
            [    281,    "Rainbow bad",    2],
            [    281,    "Autogen bassline top",    2],
            [    283,    "Autogen bassline sidechain bottom",    2],
            [    283,    "RBBB 1 bar",    4],
            [    287,    "Rainbow bad",    2],
            [    287,    "Autogen Strobe",    1],
            [    289,    "hooked wandering bottom",    16],
            [    289,    "Autogen Strobe",    1],
            [    305,    "Ghosts riser",    4],
            [    305,    "hooked wandering bottom",    16],
            [    321,    "Rainbow bad",    2],
            [    321,    "Autogen bassline sidechain bottom",    2],
            [    323,    "UV pulse",    1],
            [    323,    "rainbow good slow top",    16],
            [    339,    "hooked wandering bottom",    16],
            [    339,    "hooked wandering top",    16],
            [    355,    "hooked wandering bottom",    16],
            [    355,    "Autogen UV Strobe",    1],
            [    371,    "hooked wandering top",    16],
            [    371,    "RBBB 1 bar",    4],
            [    387,    "RBBB 1 bar",    4],
            [    387,    "Ghosts riser",    4],
            [    391,    "Ghosts riser",    4],
            [    391,    "hooked wandering top",    16],
            [    407,    "Autogen UV Strobe",    1],
            [    407,    "hooked wandering bottom",    16],
            [    423,    "Rainbow bad",    2],
            [    423,    "hooked wandering bottom",    16],
            [    439,    "Rainbow bad",    2],
            [    439,    "hooked wandering top",    16],
            [    455,    "Autogen Strobe",    1],
            [    455,    "Rainbow bad",    2],
            [    457,    "hooked wandering top",    16],
            [    457,    "rainbow good slow top",    16],
            [    473,    "Autogen bassline top",    2],
            [    473,    "RBBB 1 bar",    4],
            [    477,    "UV pulse slow",    2],
            [    477,    "Autogen bassline bottom",    2],
            [    479,    "Autogen bassline top",    2],
            [    479,    "Autogen bassline top",    2],
            [    481,    "Ghosts riser",    4],
            [    481,    "Autogen bassline bottom",    2],
            [    485,    "Autogen UV Strobe",    1],
            [    485,    "hooked wandering bottom",    16],
            [    501,    "hooked wandering bottom",    16],
            [    501,    "hooked wandering top",    16],
            [    517,    "Autogen bassline sidechain bottom",    2],
            [    517,    "Autogen bassline sidechain bottom",    2],
            [    519,    "Autogen UV Strobe",    1],
            [    519,    "hooked wandering bottom",    16],
            [    535,    "Autogen bassline sidechain bottom",    2],
            [    535,    "Rainbow bad",    2],
            [    537,    "UV pulse slow",    2],
            [    537,    "Rainbow bad",    2],
            [    539,    "Rainbow bad",    2],
            [    539,    "UV pulse",    1],
            [    541,    "hooked wandering bottom",    16],
            [    541,    "hooked wandering bottom",    16],
            [    557,    "hooked wandering bottom",    16],
            [    557,    "rainbow good slow top",    16],
            [    573,    "RBBB 1 bar",    4],
            [    573,    "Rainbow bad",    2],
            [    577,    "RBBB 1 bar",    4],
            [    577,    "RBBB 1 bar",    4],
            [    581,    "UV pulse",    1],
            [    581,    "RBBB 1 bar",    4],
            [    585,    "RBBB 1 bar",    4],
            [    585,    "RBBB 1 bar",    4],
            [    589,    "UV pulse slow",    2],
            [    589,    "UV pulse",    1],
            [    591,    "UV pulse",    1],
            [    591,    "Autogen UV Strobe",    1],
            [    592,    "UV pulse",    1],
            [    592,    "Autogen Strobe",    1],
            [    593,    "Autogen Strobe",    1],
            [    593,    "Autogen Strobe",    1],
            [    594,    "Ghosts riser",    4],
            [    594,    "Autogen bassline top",    2],
            [    598,    "Autogen bassline top",    2],
            [    598,    "Autogen Strobe",    1],
            [    600,    "rainbow good slow top",    16],
            [    600,    "Autogen bassline sidechain bottom",    2],
            [    616,    "rainbow good slow top",    16],
            [    616,    "hooked wandering top",    16],
            [    632,    "Ghosts riser",    4],
            [    632,    "Autogen bassline bottom",    2],
            [    636,    "UV pulse slow",    2],
            [    636,    "rainbow good slow top",    16],
            [    652,    "Autogen Strobe",    1],
            [    652,    "Rainbow bad",    2],
            [    654,    "Autogen bassline sidechain bottom",    2],
            [    654,    "Autogen Strobe",    1],
            [    656,    "hooked wandering bottom",    16],
            [    656,    "hooked wandering top",    16],
            [    672,    "UV pulse slow",    2],
            [    672,    "Rainbow bad",    2],
            [    674,    "Autogen UV Strobe",    1],
            [    674,    "Autogen Strobe",    1],
            [    675,    "Autogen Strobe",    1],
            [    675,    "Autogen Strobe",    1],
            [    676,    "Ghosts riser",    4],
            [    676,    "Autogen UV Strobe",    1],
            [    680,    "hooked wandering top",    16],
            [    680,    "UV pulse slow",    2],
            [    696,    "Autogen Strobe",    1],
            [    696,    "hooked wandering bottom",    16],
            [    712,    "Autogen bassline sidechain bottom",    2],
            [    712,    "Autogen UV Strobe",    1],
            [    714,    "Autogen bassline bottom",    2],
            [    714,    "Rainbow bad",    2],
            [    716,    "Ghosts riser",    4],
            [    716,    "Ghosts riser",    4],
            [    720,    "rainbow good slow top",    16],
            [    720,    "rainbow good slow top",    16],
            [    736,    "hooked wandering bottom",    16],
            [    736,    "Rainbow bad",    2],
            [    752,    "hooked wandering top",    16],
            [    752,    "UV pulse slow",    2],
            [    768,    "UV pulse slow",    2],
            [    768,    "hooked wandering top",    16],
            [    784,    "rainbow good slow top",    16],
            [    784,    "Autogen bassline bottom",    2],
            [    800,    "Autogen Strobe",    1],
            [    800,    "Ghosts riser",    4],
            [    804,    "hooked wandering bottom",    16],
            [    804,    "Ghosts riser",    4],
            [    820,    "Autogen Strobe",    1],
            [    820,    "Autogen Strobe",    1],
            [    821,    "hooked wandering top",    16],
            [    821,    "Ghosts riser",    4],
            [    837,    "Autogen bassline sidechain bottom",    2],
            [    837,    "Autogen bassline top",    2],
            [    839,    "UV pulse slow",    2],
            [    839,    "Rainbow bad",    2],
            [    841,    "hooked wandering top",    16],
            [    841,    "UV pulse slow",    2],
            [    857,    "Autogen bassline top",    2],
            [    857,    "hooked wandering top",    16],
            [    873,    "UV pulse",    1],
            [    873,    "hooked wandering bottom",    16],
            [    889,    "hooked wandering bottom",    16],
            [    889,    "Autogen Strobe",    1],
            [    905,    "rainbow good slow top",    16],
            [    905,    "Autogen bassline bottom",    2],
            [    921,    "RBBB 1 bar",    4],
            [    921,    "hooked wandering top",    16],
            [    937,    "UV pulse slow",    2],
            [    937,    "hooked wandering top",    16],
            [    953,    "rainbow good slow top",    16],
            [    953,    "Autogen bassline sidechain bottom",    2],
            [    969,    "Autogen bassline top",    2],
            [    969,    "Rainbow bad",    2],
            [    971,    "Autogen Strobe",    1],
            [    971,    "Autogen bassline bottom",    2],
            [    973,    "Autogen UV Strobe",    1],
            [    973,    "rainbow good slow top",    16],
            [    989,    "UV pulse",    1],
            [    989,    "Ghosts riser",    4],
            [    993,    "Autogen bassline bottom",    2],
            [    993,    "rainbow good slow top",    16],
            [    1009,    "Autogen bassline sidechain bottom",    2],
            [    1009,    "Ghosts riser",    4],
            [    1013,    "RBBB 1 bar",    4],
            [    1013,    "UV pulse slow",    2],
            [    1017,    "hooked wandering top",    16],
            [    1017,    "Autogen bassline top",    2],
            [    1033,    "rainbow good slow top",    16],
            [    1033,    "Autogen bassline bottom",    2],
            [    1049,    "Autogen Strobe",    1],
            [    1049,    "Autogen UV Strobe",    1],
            [    1050,    "RBBB 1 bar",    4],
            [    1050,    "Autogen bassline top",    2],
            [    1054,    "Autogen bassline top",    2],
            [    1054,    "RBBB 1 bar",    4],
            [    1058,    "hooked wandering bottom",    16],
            [    1058,    "Autogen bassline sidechain bottom",    2],
            [    1074,    "Ghosts riser",    4],
            [    1074,    "Autogen Strobe",    1],
            [    1078,    "hooked wandering bottom",    16],
            [    1078,    "Ghosts riser",    4]
        ],
        "bpm": 176,
        "delay_lights": 0.14,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/Sakamoto Maaya - Okaerinasai (tomatomerde Remix).ogg"
    }
}