effects = {
    "g_shelter": {
        "bpm": 100,
        "song_path": "songs/shelter.ogg",
        "delay_lights": 0.277,
        "generated_boundaries": [
            252,
            268,
            363
        ],
        "skip_song": 0.0,
        "profiles": [
            "Generated Shows"
        ],
        "beats": [
            [ 1, "g_solid mixed 3", 16],
            [ 17, "g_solid mixed 2", 16],
            [ 33, "g_solid mixed 1", 16],
            [ 49, "g_solid mixed 2", 16],
            [ 65, "g_solid mixed cycle", 16],
            [ 81, "g_solid mixed cycle", 16],
            [ 97, "g_solid mixed 1", 16],
            [ 113, "g_solid mixed 4", 16],
            [ 129, "g_solid mixed 3", 16],
            [ 145, "hooked bassline", 16],
            [ 161, "g_solid mixed 1", 16],
            [ 177, "g_solid mixed cycle", 16],
            [ 193, "g_solid mixed 2", 16],
            [ 209, "g_solid mixed 2", 16],
            [ 225, "g_solid mixed 3", 16],
            [ 241, "g_UV pulse", 4],
            [ 245, "g_UV pulse", 4],
            [ 249, "g_UV pulse", 4],
            [ 253, "g_purple green bottom pulse", 16],
            [ 253, "g_UV", 16],
            [ 269, "g_solid mixed 4", 16],
            [ 285, "g_solid mixed 4", 16],
            [ 301, "g_solid mixed 1", 16],
            [ 317, "hooked bassline", 16],
            [ 333, "g_solid mixed 3", 16],
            [ 349, "g_UV pulse", 4],
            [ 353, "g_UV pulse", 4],
            [ 357, "g_UV pulse", 4],
            [ 361, "g_UV pulse", 1],
            [ 362, "g_UV pulse", 1],
            [ 363, "g_UV pulse", 1]
        ],
        "was_autogenerated": True
    }
}