effects = {
    "g_shelter": {
        "beats": [
            [    1,    "Autogen bassline top",    2],
            [    1,    "hooked wandering top",    16],
            [    17,    "Autogen Strobe",    1],
            [    17,    "Rainbow bad",    2],
            [    19,    "rainbow good slow top",    16],
            [    19,    "Autogen bassline top",    2],
            [    35,    "hooked wandering top",    16],
            [    35,    "Autogen UV Strobe",    1],
            [    51,    "hooked wandering top",    16],
            [    51,    "Autogen UV Strobe",    1],
            [    67,    "rainbow good slow top",    16],
            [    67,    "hooked wandering bottom",    16],
            [    83,    "Rainbow bad",    2],
            [    83,    "Autogen bassline bottom",    2],
            [    85,    "Autogen bassline sidechain bottom",    2],
            [    85,    "UV pulse slow",    2],
            [    87,    "Autogen bassline top",    2],
            [    87,    "rainbow good slow top",    16],
            [    103,    "UV pulse slow",    2],
            [    103,    "Autogen Strobe",    1],
            [    105,    "hooked wandering top",    16],
            [    105,    "Ghosts riser",    4],
            [    121,    "Rainbow bad",    2],
            [    121,    "Autogen UV Strobe",    1],
            [    123,    "RBBB 1 bar",    4],
            [    123,    "Autogen UV Strobe",    1],
            [    127,    "Autogen bassline top",    2],
            [    127,    "UV pulse",    1],
            [    129,    "Autogen UV Strobe",    1],
            [    129,    "Autogen bassline bottom",    2],
            [    131,    "hooked wandering top",    16],
            [    131,    "Autogen bassline top",    2],
            [    147,    "rainbow good slow top",    16],
            [    147,    "rainbow good slow top",    16],
            [    163,    "RBBB 1 bar",    4],
            [    163,    "Autogen bassline bottom",    2],
            [    167,    "UV pulse slow",    2],
            [    167,    "UV pulse",    1],
            [    169,    "hooked wandering bottom",    16],
            [    169,    "hooked wandering bottom",    16],
            [    185,    "UV pulse",    1],
            [    185,    "Autogen bassline sidechain bottom",    2],
            [    187,    "hooked wandering top",    16],
            [    187,    "UV pulse",    1],
            [    203,    "Autogen bassline top",    2],
            [    203,    "Autogen bassline top",    2],
            [    205,    "rainbow good slow top",    16],
            [    205,    "Ghosts riser",    4],
            [    221,    "Ghosts riser",    4],
            [    221,    "RBBB 1 bar",    4],
            [    225,    "hooked wandering top",    16],
            [    225,    "hooked wandering bottom",    16],
            [    241,    "hooked wandering top",    16],
            [    241,    "RBBB 1 bar",    4],
            [    257,    "Autogen bassline sidechain bottom",    2],
            [    257,    "RBBB 1 bar",    4],
            [    261,    "RBBB 1 bar",    4],
            [    261,    "RBBB 1 bar",    4],
            [    265,    "UV pulse slow",    2],
            [    265,    "hooked wandering top",    16],
            [    281,    "Autogen bassline top",    2],
            [    281,    "Rainbow bad",    2],
            [    283,    "hooked wandering bottom",    16],
            [    283,    "UV pulse slow",    2],
            [    299,    "hooked wandering bottom",    16],
            [    299,    "Autogen bassline sidechain bottom",    2],
            [    315,    "Autogen bassline bottom",    2],
            [    315,    "RBBB 1 bar",    4],
            [    319,    "Autogen UV Strobe",    1],
            [    319,    "UV pulse slow",    2],
            [    321,    "UV pulse slow",    2],
            [    321,    "RBBB 1 bar",    4],
            [    325,    "hooked wandering top",    16],
            [    325,    "UV pulse slow",    2],
            [    341,    "UV pulse slow",    2],
            [    341,    "UV pulse",    1],
            [    343,    "hooked wandering bottom",    16],
            [    343,    "hooked wandering top",    16],
            [    359,    "Autogen bassline top",    2],
            [    359,    "hooked wandering top",    16]
        ],
        "bpm": 100,
        "delay_lights": 0.2925,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/shelter.ogg"
    }
}