effects = {
    "g_shelter": {
        "beats": [
            [    1,    "Rainbow bad",    2],
            [    1,    "Autogen bassline sidechain bottom",    2],
            [    3,    "rainbow good slow top",    16],
            [    3,    "Rainbow bad",    2],
            [    19,    "Autogen UV Strobe",    1],
            [    19,    "Rainbow bad",    2],
            [    21,    "UV pulse",    1],
            [    21,    "Autogen UV Strobe",    1],
            [    22,    "Autogen bassline bottom",    2],
            [    22,    "Rainbow bad",    2],
            [    24,    "Autogen bassline top",    2],
            [    24,    "Autogen bassline sidechain bottom",    2],
            [    26,    "hooked wandering bottom",    16],
            [    26,    "Autogen bassline top",    2],
            [    42,    "UV pulse slow",    2],
            [    42,    "Rainbow bad",    2],
            [    44,    "UV pulse",    1],
            [    44,    "Autogen UV Strobe",    1],
            [    45,    "Ghosts riser",    4],
            [    45,    "Ghosts riser",    4],
            [    49,    "Ghosts riser",    4],
            [    49,    "hooked wandering top",    16],
            [    65,    "Ghosts riser",    4],
            [    65,    "hooked wandering top",    16],
            [    81,    "Autogen Strobe",    1],
            [    81,    "Ghosts riser",    4],
            [    85,    "hooked wandering bottom",    16],
            [    85,    "RBBB 1 bar",    4],
            [    101,    "Rainbow bad",    2],
            [    101,    "UV pulse slow",    2],
            [    103,    "Autogen bassline top",    2],
            [    103,    "RBBB 1 bar",    4],
            [    107,    "Autogen bassline bottom",    2],
            [    107,    "hooked wandering top",    16],
            [    123,    "Autogen Strobe",    1],
            [    123,    "rainbow good slow top",    16],
            [    139,    "hooked wandering top",    16],
            [    139,    "Autogen bassline bottom",    2],
            [    155,    "Rainbow bad",    2],
            [    155,    "hooked wandering top",    16],
            [    171,    "rainbow good slow top",    16],
            [    171,    "Ghosts riser",    4],
            [    187,    "UV pulse slow",    2],
            [    187,    "hooked wandering bottom",    16],
            [    203,    "RBBB 1 bar",    4],
            [    203,    "Autogen UV Strobe",    1],
            [    207,    "Ghosts riser",    4],
            [    207,    "hooked wandering top",    16],
            [    223,    "Ghosts riser",    4],
            [    223,    "Autogen bassline sidechain bottom",    2],
            [    227,    "Ghosts riser",    4],
            [    227,    "hooked wandering top",    16],
            [    243,    "Autogen bassline top",    2],
            [    243,    "Rainbow bad",    2],
            [    245,    "Autogen UV Strobe",    1],
            [    245,    "Ghosts riser",    4],
            [    249,    "Autogen bassline sidechain bottom",    2],
            [    249,    "Rainbow bad",    2],
            [    251,    "hooked wandering top",    16],
            [    251,    "UV pulse",    1],
            [    267,    "Autogen UV Strobe",    1],
            [    267,    "Autogen UV Strobe",    1],
            [    268,    "hooked wandering top",    16],
            [    268,    "hooked wandering top",    16],
            [    284,    "rainbow good slow top",    16],
            [    284,    "UV pulse",    1],
            [    300,    "Rainbow bad",    2],
            [    300,    "UV pulse",    1],
            [    302,    "UV pulse",    1],
            [    302,    "hooked wandering top",    16],
            [    318,    "Autogen bassline top",    2],
            [    318,    "Autogen bassline bottom",    2],
            [    320,    "UV pulse",    1],
            [    320,    "Autogen bassline top",    2],
            [    322,    "UV pulse slow",    2],
            [    322,    "Autogen UV Strobe",    1],
            [    324,    "UV pulse slow",    2],
            [    324,    "rainbow good slow top",    16],
            [    340,    "hooked wandering bottom",    16],
            [    340,    "UV pulse",    1],
            [    356,    "Autogen bassline sidechain bottom",    2],
            [    356,    "Autogen UV Strobe",    1],
            [    358,    "UV pulse slow",    2],
            [    358,    "RBBB 1 bar",    4]
        ],
        "bpm": 100,
        "delay_lights": 0.2925,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/shelter.ogg"
    }
}