effects = {
    "g_slowed_deadmau": {
        "beats": [
            [    1,    "Autogen UV Strobe",    1],
            [    1,    "Autogen UV Strobe",    1],
            [    2,    "Autogen Strobe",    1],
            [    2,    "Autogen UV Strobe",    1],
            [    3,    "Autogen UV Strobe",    1],
            [    3,    "Rainbow bad",    2],
            [    5,    "UV pulse",    1],
            [    5,    "UV pulse",    1],
            [    6,    "RBBB 1 bar",    4],
            [    6,    "RBBB 1 bar",    4],
            [    10,    "rainbow good slow top",    16],
            [    10,    "Ghosts riser",    4],
            [    26,    "rainbow good slow top",    16],
            [    26,    "rainbow good slow top",    16],
            [    42,    "rainbow good slow top",    16],
            [    42,    "Autogen UV Strobe",    1],
            [    58,    "Autogen bassline sidechain bottom",    2],
            [    58,    "UV pulse",    1],
            [    60,    "RBBB 1 bar",    4],
            [    60,    "Autogen bassline top",    2],
            [    64,    "Autogen bassline sidechain bottom",    2],
            [    64,    "Ghosts riser",    4],
            [    68,    "Autogen Strobe",    1],
            [    68,    "Ghosts riser",    4],
            [    72,    "Ghosts riser",    4],
            [    72,    "Autogen bassline top",    2],
            [    76,    "RBBB 1 bar",    4],
            [    76,    "Ghosts riser",    4],
            [    80,    "hooked wandering top",    16],
            [    80,    "rainbow good slow top",    16],
            [    96,    "Autogen bassline sidechain bottom",    2],
            [    96,    "hooked wandering bottom",    16],
            [    112,    "UV pulse slow",    2],
            [    112,    "Ghosts riser",    4],
            [    116,    "RBBB 1 bar",    4],
            [    116,    "UV pulse",    1],
            [    120,    "UV pulse",    1],
            [    120,    "Autogen UV Strobe",    1],
            [    121,    "Autogen UV Strobe",    1],
            [    121,    "RBBB 1 bar",    4],
            [    125,    "Rainbow bad",    2],
            [    125,    "Autogen Strobe",    1],
            [    127,    "Ghosts riser",    4],
            [    127,    "Autogen UV Strobe",    1],
            [    131,    "hooked wandering bottom",    16],
            [    131,    "rainbow good slow top",    16],
            [    147,    "Rainbow bad",    2],
            [    147,    "Autogen UV Strobe",    1],
            [    149,    "RBBB 1 bar",    4],
            [    149,    "Autogen bassline sidechain bottom",    2],
            [    153,    "Rainbow bad",    2],
            [    153,    "Autogen bassline sidechain bottom",    2],
            [    155,    "Rainbow bad",    2],
            [    155,    "Autogen Strobe",    1],
            [    157,    "RBBB 1 bar",    4],
            [    157,    "Autogen UV Strobe",    1],
            [    161,    "Autogen bassline top",    2],
            [    161,    "Autogen Strobe",    1],
            [    163,    "Ghosts riser",    4],
            [    163,    "Rainbow bad",    2],
            [    167,    "UV pulse",    1],
            [    167,    "Autogen bassline bottom",    2],
            [    169,    "hooked wandering top",    16],
            [    169,    "Autogen bassline sidechain bottom",    2],
            [    185,    "Autogen bassline bottom",    2],
            [    185,    "Autogen bassline top",    2],
            [    187,    "UV pulse slow",    2],
            [    187,    "Autogen bassline top",    2],
            [    189,    "hooked wandering bottom",    16],
            [    189,    "Autogen Strobe",    1],
            [    205,    "Ghosts riser",    4],
            [    205,    "Autogen bassline bottom",    2],
            [    209,    "hooked wandering top",    16],
            [    209,    "Autogen bassline top",    2],
            [    225,    "Rainbow bad",    2],
            [    225,    "UV pulse slow",    2],
            [    227,    "hooked wandering bottom",    16],
            [    227,    "Rainbow bad",    2],
            [    243,    "hooked wandering top",    16],
            [    243,    "Ghosts riser",    4],
            [    259,    "rainbow good slow top",    16],
            [    259,    "UV pulse slow",    2],
            [    275,    "UV pulse",    1],
            [    275,    "UV pulse",    1],
            [    276,    "UV pulse",    1],
            [    276,    "UV pulse slow",    2],
            [    278,    "Rainbow bad",    2],
            [    278,    "Autogen UV Strobe",    1],
            [    280,    "Autogen UV Strobe",    1],
            [    280,    "Autogen bassline sidechain bottom",    2],
            [    282,    "RBBB 1 bar",    4],
            [    282,    "RBBB 1 bar",    4],
            [    286,    "RBBB 1 bar",    4],
            [    286,    "Ghosts riser",    4],
            [    290,    "Autogen bassline top",    2],
            [    290,    "Autogen bassline bottom",    2],
            [    292,    "UV pulse",    1],
            [    292,    "Autogen bassline bottom",    2],
            [    294,    "Rainbow bad",    2],
            [    294,    "UV pulse",    1],
            [    296,    "Rainbow bad",    2],
            [    296,    "Autogen bassline bottom",    2],
            [    298,    "rainbow good slow top",    16],
            [    298,    "rainbow good slow top",    16],
            [    314,    "Autogen bassline sidechain bottom",    2],
            [    314,    "Rainbow bad",    2],
            [    316,    "Autogen Strobe",    1],
            [    316,    "hooked wandering top",    16],
            [    332,    "Rainbow bad",    2],
            [    332,    "Autogen Strobe",    1],
            [    334,    "Autogen Strobe",    1],
            [    334,    "Autogen bassline top",    2],
            [    336,    "Autogen UV Strobe",    1],
            [    336,    "Autogen bassline sidechain bottom",    2],
            [    338,    "rainbow good slow top",    16],
            [    338,    "UV pulse slow",    2],
            [    354,    "Ghosts riser",    4],
            [    354,    "Autogen bassline sidechain bottom",    2],
            [    358,    "rainbow good slow top",    16],
            [    358,    "UV pulse",    1],
            [    374,    "Autogen bassline top",    2],
            [    374,    "UV pulse",    1],
            [    376,    "Rainbow bad",    2],
            [    376,    "Autogen bassline bottom",    2],
            [    378,    "Autogen bassline top",    2],
            [    378,    "RBBB 1 bar",    4],
            [    382,    "Autogen bassline sidechain bottom",    2],
            [    382,    "Ghosts riser",    4],
            [    386,    "RBBB 1 bar",    4],
            [    386,    "hooked wandering top",    16],
            [    402,    "Autogen bassline top",    2],
            [    402,    "Autogen Strobe",    1],
            [    404,    "hooked wandering bottom",    16],
            [    404,    "Autogen bassline sidechain bottom",    2],
            [    420,    "Autogen UV Strobe",    1],
            [    420,    "Autogen bassline top",    2],
            [    422,    "RBBB 1 bar",    4],
            [    422,    "Autogen UV Strobe",    1],
            [    426,    "Autogen bassline bottom",    2],
            [    426,    "rainbow good slow top",    16],
            [    442,    "Ghosts riser",    4],
            [    442,    "Ghosts riser",    4],
            [    446,    "Autogen bassline top",    2],
            [    446,    "rainbow good slow top",    16],
            [    462,    "Rainbow bad",    2],
            [    462,    "Autogen bassline bottom",    2],
            [    464,    "Ghosts riser",    4],
            [    464,    "Autogen bassline bottom",    2],
            [    468,    "Ghosts riser",    4],
            [    468,    "Rainbow bad",    2],
            [    472,    "RBBB 1 bar",    4],
            [    472,    "UV pulse slow",    2],
            [    476,    "Autogen bassline sidechain bottom",    2],
            [    476,    "Autogen Strobe",    1],
            [    478,    "UV pulse slow",    2],
            [    478,    "hooked wandering bottom",    16],
            [    494,    "rainbow good slow top",    16],
            [    494,    "Autogen bassline bottom",    2],
            [    510,    "RBBB 1 bar",    4],
            [    510,    "Ghosts riser",    4],
            [    514,    "RBBB 1 bar",    4],
            [    514,    "hooked wandering bottom",    16],
            [    530,    "Autogen bassline sidechain bottom",    2],
            [    530,    "Ghosts riser",    4],
            [    534,    "Autogen Strobe",    1],
            [    534,    "hooked wandering bottom",    16],
            [    550,    "Autogen bassline sidechain bottom",    2],
            [    550,    "rainbow good slow top",    16],
            [    566,    "UV pulse slow",    2],
            [    566,    "Autogen UV Strobe",    1],
            [    568,    "Rainbow bad",    2],
            [    568,    "Ghosts riser",    4],
            [    572,    "Autogen Strobe",    1],
            [    572,    "hooked wandering bottom",    16],
            [    588,    "Autogen bassline top",    2],
            [    588,    "hooked wandering bottom",    16],
            [    604,    "Ghosts riser",    4],
            [    604,    "UV pulse slow",    2],
            [    608,    "Ghosts riser",    4],
            [    608,    "hooked wandering bottom",    16],
            [    624,    "Autogen UV Strobe",    1],
            [    624,    "hooked wandering top",    16],
            [    640,    "UV pulse",    1],
            [    640,    "UV pulse",    1],
            [    641,    "rainbow good slow top",    16],
            [    641,    "Ghosts riser",    4],
            [    657,    "hooked wandering top",    16],
            [    657,    "Autogen Strobe",    1],
            [    673,    "UV pulse slow",    2],
            [    673,    "Rainbow bad",    2],
            [    675,    "hooked wandering top",    16],
            [    675,    "Autogen Strobe",    1],
            [    691,    "Ghosts riser",    4],
            [    691,    "RBBB 1 bar",    4],
            [    695,    "UV pulse",    1],
            [    695,    "Rainbow bad",    2],
            [    697,    "Rainbow bad",    2],
            [    697,    "UV pulse",    1],
            [    699,    "Autogen bassline top",    2],
            [    699,    "rainbow good slow top",    16],
            [    715,    "Autogen bassline bottom",    2],
            [    715,    "Rainbow bad",    2],
            [    717,    "UV pulse slow",    2],
            [    717,    "Autogen Strobe",    1],
            [    719,    "Autogen bassline top",    2],
            [    719,    "Autogen bassline bottom",    2],
            [    721,    "Autogen bassline top",    2],
            [    721,    "Autogen UV Strobe",    1],
            [    723,    "Rainbow bad",    2],
            [    723,    "rainbow good slow top",    16],
            [    739,    "Autogen Strobe",    1],
            [    739,    "RBBB 1 bar",    4],
            [    743,    "UV pulse",    1],
            [    743,    "Rainbow bad",    2],
            [    745,    "Autogen bassline top",    2],
            [    745,    "hooked wandering top",    16],
            [    761,    "Autogen bassline sidechain bottom",    2],
            [    761,    "UV pulse slow",    2],
            [    763,    "Autogen bassline bottom",    2],
            [    763,    "RBBB 1 bar",    4],
            [    767,    "Autogen Strobe",    1],
            [    767,    "Autogen Strobe",    1],
            [    768,    "Rainbow bad",    2],
            [    768,    "Autogen bassline bottom",    2],
            [    770,    "Autogen bassline sidechain bottom",    2],
            [    770,    "hooked wandering bottom",    16],
            [    786,    "hooked wandering bottom",    16],
            [    786,    "Autogen bassline top",    2],
            [    802,    "Autogen UV Strobe",    1],
            [    802,    "rainbow good slow top",    16],
            [    818,    "RBBB 1 bar",    4],
            [    818,    "hooked wandering top",    16],
            [    834,    "rainbow good slow top",    16],
            [    834,    "Autogen UV Strobe",    1],
            [    850,    "Ghosts riser",    4],
            [    850,    "hooked wandering top",    16],
            [    866,    "Autogen bassline top",    2],
            [    866,    "Autogen bassline sidechain bottom",    2],
            [    868,    "UV pulse slow",    2],
            [    868,    "rainbow good slow top",    16],
            [    884,    "UV pulse",    1],
            [    884,    "hooked wandering bottom",    16],
            [    900,    "UV pulse",    1],
            [    900,    "Autogen Strobe",    1],
            [    901,    "Autogen UV Strobe",    1],
            [    901,    "Autogen Strobe",    1],
            [    902,    "Autogen UV Strobe",    1],
            [    902,    "Autogen bassline sidechain bottom",    2],
            [    904,    "Autogen bassline sidechain bottom",    2],
            [    904,    "Autogen Strobe",    1],
            [    906,    "hooked wandering bottom",    16],
            [    906,    "Ghosts riser",    4],
            [    922,    "Autogen bassline bottom",    2],
            [    922,    "UV pulse",    1],
            [    924,    "Autogen UV Strobe",    1],
            [    924,    "Ghosts riser",    4],
            [    928,    "UV pulse slow",    2],
            [    928,    "hooked wandering top",    16],
            [    944,    "UV pulse",    1],
            [    944,    "RBBB 1 bar",    4],
            [    948,    "Rainbow bad",    2],
            [    948,    "Autogen bassline bottom",    2],
            [    950,    "Ghosts riser",    4],
            [    950,    "Autogen bassline sidechain bottom",    2],
            [    954,    "Rainbow bad",    2],
            [    954,    "Autogen bassline top",    2],
            [    956,    "hooked wandering top",    16],
            [    956,    "hooked wandering top",    16],
            [    972,    "Autogen UV Strobe",    1],
            [    972,    "Rainbow bad",    2],
            [    974,    "Autogen Strobe",    1],
            [    974,    "hooked wandering bottom",    16],
            [    990,    "Autogen bassline sidechain bottom",    2],
            [    990,    "UV pulse slow",    2],
            [    992,    "Autogen UV Strobe",    1],
            [    992,    "Autogen UV Strobe",    1],
            [    993,    "Autogen bassline bottom",    2],
            [    993,    "Autogen Strobe",    1],
            [    995,    "Ghosts riser",    4],
            [    995,    "Autogen bassline sidechain bottom",    2],
            [    999,    "RBBB 1 bar",    4],
            [    999,    "Autogen bassline top",    2],
            [    1003,    "Ghosts riser",    4],
            [    1003,    "UV pulse",    1],
            [    1007,    "UV pulse",    1],
            [    1007,    "Autogen UV Strobe",    1],
            [    1008,    "Rainbow bad",    2],
            [    1008,    "RBBB 1 bar",    4],
            [    1012,    "Autogen Strobe",    1],
            [    1012,    "rainbow good slow top",    16],
            [    1028,    "RBBB 1 bar",    4],
            [    1028,    "Autogen UV Strobe",    1],
            [    1032,    "Autogen UV Strobe",    1],
            [    1032,    "rainbow good slow top",    16],
            [    1048,    "Autogen bassline top",    2],
            [    1048,    "Ghosts riser",    4],
            [    1052,    "Autogen bassline top",    2],
            [    1052,    "Rainbow bad",    2],
            [    1054,    "hooked wandering top",    16],
            [    1054,    "hooked wandering bottom",    16],
            [    1070,    "Rainbow bad",    2],
            [    1070,    "Autogen UV Strobe",    1],
            [    1072,    "UV pulse",    1],
            [    1072,    "Autogen UV Strobe",    1],
            [    1073,    "Autogen UV Strobe",    1],
            [    1073,    "Autogen bassline bottom",    2],
            [    1075,    "Rainbow bad",    2],
            [    1075,    "UV pulse",    1],
            [    1077,    "Ghosts riser",    4],
            [    1077,    "RBBB 1 bar",    4],
            [    1081,    "Autogen UV Strobe",    1],
            [    1081,    "Autogen bassline sidechain bottom",    2],
            [    1083,    "Autogen Strobe",    1],
            [    1083,    "RBBB 1 bar",    4],
            [    1087,    "Ghosts riser",    4],
            [    1087,    "Ghosts riser",    4],
            [    1091,    "Autogen bassline bottom",    2],
            [    1091,    "rainbow good slow top",    16],
            [    1107,    "Autogen bassline bottom",    2],
            [    1107,    "UV pulse",    1],
            [    1109,    "Autogen bassline top",    2],
            [    1109,    "hooked wandering bottom",    16],
            [    1125,    "rainbow good slow top",    16],
            [    1125,    "UV pulse",    1],
            [    1141,    "Rainbow bad",    2],
            [    1141,    "Autogen bassline top",    2],
            [    1143,    "hooked wandering top",    16],
            [    1143,    "Autogen UV Strobe",    1],
            [    1159,    "UV pulse",    1],
            [    1159,    "Autogen bassline bottom",    2],
            [    1161,    "hooked wandering top",    16],
            [    1161,    "UV pulse slow",    2],
            [    1177,    "hooked wandering top",    16],
            [    1177,    "RBBB 1 bar",    4],
            [    1193,    "hooked wandering top",    16],
            [    1193,    "hooked wandering bottom",    16],
            [    1209,    "UV pulse slow",    2],
            [    1209,    "UV pulse",    1],
            [    1211,    "RBBB 1 bar",    4],
            [    1211,    "UV pulse slow",    2],
            [    1215,    "Ghosts riser",    4],
            [    1215,    "UV pulse slow",    2],
            [    1219,    "RBBB 1 bar",    4],
            [    1219,    "Autogen bassline bottom",    2],
            [    1223,    "Ghosts riser",    4],
            [    1223,    "hooked wandering top",    16],
            [    1239,    "Autogen bassline bottom",    2],
            [    1239,    "Autogen bassline sidechain bottom",    2],
            [    1241,    "UV pulse slow",    2],
            [    1241,    "Ghosts riser",    4],
            [    1245,    "RBBB 1 bar",    4],
            [    1245,    "hooked wandering bottom",    16],
            [    1261,    "hooked wandering bottom",    16],
            [    1261,    "Autogen bassline bottom",    2]
        ],
        "bpm": 90,
        "delay_lights": 0.10275000000000001,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/slowed_deadmau.ogg"
    }
}