effects = {
    "g_slowed_deadmau": {
        "beats": [
            [    1,    "RGB Flash",    1],
            [    2,    "g_solid mixed double",    16],
            [    18,    "RGB Flash",    1],
            [    19,    "g_solid bottom cycle",    16],
            [    19,    "g_UV",    16],
            [    35,    "g_UV pulse",    2],
            [    37,    "g_cyan top pulse",    16],
            [    37,    "g_UV",    16],
            [    53,    "g_UV pulse",    4],
            [    57,    "g_purple green bottom pulse",    16],
            [    73,    "g_solid mixed double",    16],
            [    73,    "g_UV",    16],
            [    89,    "g_Strobe",    1],
            [    90,    "RGB Flash",    1],
            [    91,    "g_solid mixed cycle",    16],
            [    91,    "g_UV",    16],
            [    107,    "g_solid top cycle",    16],
            [    107,    "g_purple green bottom pulse",    16],
            [    123,    "g_solid top cycle",    16],
            [    123,    "g_UV",    16],
            [    139,    "g_rainbow good slow top",    16],
            [    139,    "g_green sidechain bottom pulse",    16],
            [    155,    "g_UV pulse",    4],
            [    159,    "g_green sidechain bottom pulse",    16],
            [    175,    "g_UV pulse",    1],
            [    176,    "RGB Flash",    1],
            [    177,    "g_UV pulse",    2],
            [    179,    "g_solid bottom cycle",    16],
            [    179,    "g_UV",    16],
            [    195,    "g_cyan top pulse",    16],
            [    211,    "g_solid mixed double",    16],
            [    227,    "g_solid bottom cycle",    16],
            [    243,    "g_cyan top pulse",    16],
            [    243,    "g_green sidechain bottom pulse",    16],
            [    243,    "g_UV",    16],
            [    259,    "g_solid top cycle",    16],
            [    259,    "g_purple green bottom pulse",    16],
            [    275,    "g_solid mixed double",    16],
            [    275,    "g_UV",    16],
            [    291,    "RGB Flash",    1],
            [    292,    "RGB Flash",    1],
            [    293,    "g_solid mixed cycle",    16],
            [    293,    "g_UV",    16],
            [    309,    "g_UV pulse",    1],
            [    310,    "g_cyan top pulse",    16],
            [    310,    "g_green sidechain bottom pulse",    16],
            [    310,    "g_UV",    16],
            [    326,    "g_solid mixed cycle",    16],
            [    326,    "g_UV",    16],
            [    342,    "g_UV pulse",    1],
            [    343,    "g_UV Strobe",    1],
            [    344,    "g_UV pulse",    4],
            [    348,    "g_solid mixed double",    16],
            [    348,    "g_UV",    16],
            [    364,    "g_UV Strobe",    1],
            [    365,    "g_solid top cycle",    16],
            [    365,    "g_green sidechain bottom pulse",    16],
            [    365,    "g_UV",    16],
            [    381,    "g_UV pulse",    4],
            [    385,    "g_cyan top pulse",    16],
            [    401,    "g_UV pulse",    2],
            [    403,    "RGB Flash",    1],
            [    404,    "RGB Flash",    1],
            [    405,    "g_UV pulse",    2],
            [    407,    "g_rainbow good top",    16],
            [    407,    "g_purple green bottom pulse",    16],
            [    423,    "g_UV pulse",    2],
            [    425,    "g_purple green bottom pulse",    16],
            [    425,    "g_UV",    16],
            [    441,    "g_UV pulse",    1],
            [    442,    "g_rainbow good top",    16],
            [    442,    "g_purple green bottom pulse",    16],
            [    458,    "g_solid top cycle",    16],
            [    458,    "g_UV",    16],
            [    474,    "g_UV pulse",    2],
            [    476,    "g_solid bottom cycle",    16],
            [    476,    "g_UV",    16],
            [    492,    "g_solid bottom cycle",    16],
            [    492,    "g_UV",    16],
            [    508,    "g_UV Strobe",    1],
            [    509,    "g_Strobe",    1],
            [    510,    "g_solid top cycle",    16],
            [    510,    "g_UV",    16],
            [    526,    "g_solid top cycle",    16],
            [    542,    "g_solid top cycle",    16],
            [    542,    "g_solid bottom cycle",    16],
            [    542,    "g_UV",    16],
            [    558,    "g_UV pulse",    1],
            [    559,    "g_rainbow good top",    16],
            [    559,    "g_green sidechain bottom pulse",    16],
            [    575,    "g_UV pulse",    4],
            [    579,    "g_UV pulse",    1],
            [    580,    "g_solid top cycle",    16],
            [    580,    "g_solid bottom cycle",    16],
            [    596,    "g_UV pulse",    4],
            [    600,    "g_solid mixed double",    16],
            [    616,    "g_solid top cycle",    16],
            [    632,    "g_UV pulse",    1],
            [    633,    "g_solid top cycle",    16],
            [    649,    "g_rainbow good top",    16],
            [    649,    "g_green sidechain bottom pulse",    16],
            [    665,    "g_green sidechain bottom pulse",    16],
            [    681,    "g_solid bottom cycle",    16],
            [    681,    "g_UV",    16],
            [    697,    "g_UV Strobe",    1],
            [    698,    "g_UV pulse",    2],
            [    700,    "g_cyan top pulse",    16],
            [    700,    "g_UV",    16],
            [    716,    "g_rainbow good top",    16],
            [    716,    "g_solid bottom cycle",    16],
            [    732,    "g_cyan top pulse",    16],
            [    732,    "g_solid bottom cycle",    16],
            [    748,    "g_solid bottom cycle",    16],
            [    748,    "g_UV",    16],
            [    764,    "g_UV Strobe",    1],
            [    765,    "g_UV pulse",    1],
            [    766,    "g_solid mixed cycle",    16],
            [    766,    "g_UV",    16],
            [    782,    "g_solid bottom cycle",    16],
            [    782,    "g_UV",    16],
            [    798,    "g_UV pulse",    2],
            [    800,    "g_rainbow good slow top",    16],
            [    800,    "g_solid bottom cycle",    16],
            [    816,    "g_cyan top pulse",    16],
            [    816,    "g_green sidechain bottom pulse",    16],
            [    816,    "g_UV",    16],
            [    832,    "g_rainbow good top",    16],
            [    832,    "g_solid bottom cycle",    16],
            [    848,    "g_cyan top pulse",    16],
            [    848,    "g_green sidechain bottom pulse",    16],
            [    864,    "g_solid mixed cycle",    16],
            [    880,    "g_cyan top pulse",    16],
            [    880,    "g_solid bottom cycle",    16],
            [    880,    "g_UV",    16],
            [    896,    "RGB Flash",    1],
            [    897,    "g_solid top cycle",    16],
            [    897,    "g_purple green bottom pulse",    16],
            [    897,    "g_UV",    16],
            [    913,    "g_solid top cycle",    16],
            [    913,    "g_solid bottom cycle",    16],
            [    913,    "g_UV",    16],
            [    929,    "g_solid top cycle",    16],
            [    945,    "g_UV pulse",    4],
            [    949,    "g_UV pulse",    2],
            [    951,    "g_Strobe",    1],
            [    952,    "g_cyan top pulse",    16],
            [    952,    "g_UV",    16],
            [    968,    "g_Strobe",    1],
            [    969,    "g_solid mixed double",    16],
            [    969,    "g_UV",    16],
            [    985,    "g_solid mixed double",    16],
            [    1001,    "g_solid bottom cycle",    16],
            [    1001,    "g_UV",    16],
            [    1017,    "g_solid mixed double",    16],
            [    1017,    "g_UV",    16],
            [    1033,    "g_green sidechain bottom pulse",    16],
            [    1033,    "g_UV",    16],
            [    1049,    "g_UV Strobe",    1],
            [    1050,    "g_green sidechain bottom pulse",    16],
            [    1066,    "g_purple green bottom pulse",    16],
            [    1066,    "g_UV",    16],
            [    1082,    "g_UV pulse",    1],
            [    1083,    "g_solid top cycle",    16],
            [    1083,    "g_UV",    16],
            [    1099,    "g_rainbow good top",    16],
            [    1099,    "g_solid bottom cycle",    16],
            [    1115,    "g_UV pulse",    2],
            [    1117,    "g_solid mixed double",    16],
            [    1117,    "g_UV",    16],
            [    1133,    "g_UV pulse",    2],
            [    1135,    "g_cyan top pulse",    16],
            [    1135,    "g_UV",    16],
            [    1151,    "g_rainbow good slow top",    16],
            [    1151,    "g_purple green bottom pulse",    16],
            [    1167,    "g_purple green bottom pulse",    16],
            [    1183,    "g_cyan top pulse",    16],
            [    1183,    "g_green sidechain bottom pulse",    16],
            [    1199,    "g_purple green bottom pulse",    16],
            [    1199,    "g_UV",    16],
            [    1215,    "g_UV pulse",    4],
            [    1219,    "g_rainbow good top",    16],
            [    1219,    "g_solid bottom cycle",    16],
            [    1235,    "g_solid top cycle",    16],
            [    1235,    "g_UV",    16],
            [    1251,    "g_UV pulse",    4],
            [    1255,    "g_UV pulse",    1],
            [    1256,    "g_solid top cycle",    16]
        ],
        "bpm": 90,
        "delay_lights": 0.10275000000000001,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/slowed_deadmau.ogg",
        "was_autogenerated": True
    }
}