effects = {
    "g_slowed_deadmau": {
        "beats": [
            [    1,    "hooked wandering bottom",    16],
            [    1,    "UV pulse slow",    2],
            [    17,    "hooked wandering bottom",    16],
            [    17,    "UV pulse",    1],
            [    33,    "Autogen Strobe",    1],
            [    33,    "UV pulse slow",    2],
            [    35,    "Autogen bassline sidechain bottom",    2],
            [    35,    "hooked wandering bottom",    16],
            [    51,    "Autogen bassline top",    2],
            [    51,    "rainbow good slow top",    16],
            [    67,    "RBBB 1 bar",    4],
            [    67,    "rainbow good slow top",    16],
            [    83,    "UV pulse",    1],
            [    83,    "hooked wandering top",    16],
            [    99,    "UV pulse slow",    2],
            [    99,    "Autogen Strobe",    1],
            [    101,    "Autogen bassline top",    2],
            [    101,    "rainbow good slow top",    16],
            [    117,    "Autogen Strobe",    1],
            [    117,    "Rainbow bad",    2],
            [    119,    "Autogen UV Strobe",    1],
            [    119,    "Autogen bassline sidechain bottom",    2],
            [    121,    "UV pulse slow",    2],
            [    121,    "Autogen bassline sidechain bottom",    2],
            [    123,    "Autogen bassline bottom",    2],
            [    123,    "Autogen bassline sidechain bottom",    2],
            [    125,    "hooked wandering top",    16],
            [    125,    "rainbow good slow top",    16],
            [    141,    "Autogen bassline bottom",    2],
            [    141,    "UV pulse",    1],
            [    143,    "rainbow good slow top",    16],
            [    143,    "Autogen bassline bottom",    2],
            [    159,    "UV pulse slow",    2],
            [    159,    "Autogen UV Strobe",    1],
            [    161,    "UV pulse",    1],
            [    161,    "Rainbow bad",    2],
            [    163,    "Autogen UV Strobe",    1],
            [    163,    "Autogen Strobe",    1],
            [    164,    "UV pulse slow",    2],
            [    164,    "Ghosts riser",    4],
            [    168,    "hooked wandering bottom",    16],
            [    168,    "Ghosts riser",    4],
            [    184,    "Rainbow bad",    2],
            [    184,    "Autogen bassline bottom",    2],
            [    186,    "hooked wandering top",    16],
            [    186,    "hooked wandering bottom",    16],
            [    202,    "Autogen UV Strobe",    1],
            [    202,    "Rainbow bad",    2],
            [    204,    "Autogen UV Strobe",    1],
            [    204,    "Rainbow bad",    2],
            [    206,    "Autogen bassline bottom",    2],
            [    206,    "Ghosts riser",    4],
            [    210,    "UV pulse",    1],
            [    210,    "Autogen UV Strobe",    1],
            [    211,    "RBBB 1 bar",    4],
            [    211,    "Autogen Strobe",    1],
            [    215,    "Autogen Strobe",    1],
            [    215,    "Autogen UV Strobe",    1],
            [    216,    "rainbow good slow top",    16],
            [    216,    "hooked wandering bottom",    16],
            [    232,    "hooked wandering top",    16],
            [    232,    "hooked wandering top",    16],
            [    248,    "rainbow good slow top",    16],
            [    248,    "RBBB 1 bar",    4],
            [    264,    "Ghosts riser",    4],
            [    264,    "Autogen Strobe",    1],
            [    268,    "hooked wandering top",    16],
            [    268,    "UV pulse slow",    2],
            [    284,    "Rainbow bad",    2],
            [    284,    "UV pulse",    1],
            [    286,    "Autogen bassline bottom",    2],
            [    286,    "Autogen Strobe",    1],
            [    288,    "UV pulse slow",    2],
            [    288,    "UV pulse slow",    2],
            [    290,    "UV pulse",    1],
            [    290,    "Autogen Strobe",    1],
            [    291,    "Autogen UV Strobe",    1],
            [    291,    "Ghosts riser",    4],
            [    295,    "hooked wandering bottom",    16],
            [    295,    "hooked wandering top",    16],
            [    311,    "Autogen bassline top",    2],
            [    311,    "RBBB 1 bar",    4],
            [    315,    "UV pulse",    1],
            [    315,    "Ghosts riser",    4],
            [    319,    "hooked wandering top",    16],
            [    319,    "hooked wandering bottom",    16],
            [    335,    "Autogen UV Strobe",    1],
            [    335,    "hooked wandering bottom",    16],
            [    351,    "UV pulse slow",    2],
            [    351,    "UV pulse slow",    2],
            [    353,    "RBBB 1 bar",    4],
            [    353,    "UV pulse slow",    2],
            [    357,    "Autogen Strobe",    1],
            [    357,    "rainbow good slow top",    16],
            [    373,    "Autogen bassline top",    2],
            [    373,    "Autogen bassline sidechain bottom",    2],
            [    375,    "Rainbow bad",    2],
            [    375,    "hooked wandering bottom",    16],
            [    391,    "Autogen Strobe",    1],
            [    391,    "rainbow good slow top",    16],
            [    407,    "hooked wandering bottom",    16],
            [    407,    "rainbow good slow top",    16],
            [    423,    "Autogen bassline sidechain bottom",    2],
            [    423,    "Ghosts riser",    4],
            [    427,    "Autogen Strobe",    1],
            [    427,    "hooked wandering bottom",    16],
            [    443,    "UV pulse",    1],
            [    443,    "Rainbow bad",    2],
            [    445,    "Autogen bassline top",    2],
            [    445,    "RBBB 1 bar",    4],
            [    449,    "UV pulse slow",    2],
            [    449,    "Autogen UV Strobe",    1],
            [    451,    "RBBB 1 bar",    4],
            [    451,    "Autogen bassline top",    2],
            [    455,    "Autogen bassline bottom",    2],
            [    455,    "Autogen bassline top",    2],
            [    457,    "Autogen bassline top",    2],
            [    457,    "rainbow good slow top",    16],
            [    473,    "Autogen UV Strobe",    1],
            [    473,    "Autogen bassline bottom",    2],
            [    475,    "Autogen bassline bottom",    2],
            [    475,    "hooked wandering top",    16],
            [    491,    "hooked wandering top",    16],
            [    491,    "Autogen Strobe",    1],
            [    507,    "hooked wandering bottom",    16],
            [    507,    "Autogen Strobe",    1],
            [    523,    "rainbow good slow top",    16],
            [    523,    "Autogen bassline sidechain bottom",    2],
            [    539,    "rainbow good slow top",    16],
            [    539,    "RBBB 1 bar",    4],
            [    555,    "rainbow good slow top",    16],
            [    555,    "hooked wandering bottom",    16],
            [    571,    "Autogen bassline sidechain bottom",    2],
            [    571,    "UV pulse",    1],
            [    573,    "UV pulse",    1],
            [    573,    "UV pulse",    1],
            [    574,    "hooked wandering top",    16],
            [    574,    "Autogen UV Strobe",    1],
            [    590,    "rainbow good slow top",    16],
            [    590,    "Autogen UV Strobe",    1],
            [    606,    "hooked wandering bottom",    16],
            [    606,    "hooked wandering bottom",    16],
            [    622,    "Ghosts riser",    4],
            [    622,    "Autogen bassline top",    2],
            [    626,    "hooked wandering bottom",    16],
            [    626,    "Autogen bassline bottom",    2],
            [    642,    "UV pulse slow",    2],
            [    642,    "Autogen UV Strobe",    1],
            [    644,    "RBBB 1 bar",    4],
            [    644,    "Autogen UV Strobe",    1],
            [    648,    "Autogen Strobe",    1],
            [    648,    "RBBB 1 bar",    4],
            [    652,    "rainbow good slow top",    16],
            [    652,    "RBBB 1 bar",    4],
            [    668,    "UV pulse slow",    2],
            [    668,    "UV pulse slow",    2],
            [    670,    "hooked wandering bottom",    16],
            [    670,    "hooked wandering bottom",    16],
            [    686,    "Autogen bassline bottom",    2],
            [    686,    "RBBB 1 bar",    4],
            [    690,    "hooked wandering top",    16],
            [    690,    "Rainbow bad",    2],
            [    706,    "hooked wandering top",    16],
            [    706,    "Ghosts riser",    4],
            [    722,    "Autogen bassline bottom",    2],
            [    722,    "Rainbow bad",    2],
            [    724,    "Ghosts riser",    4],
            [    724,    "Autogen bassline top",    2],
            [    728,    "Ghosts riser",    4],
            [    728,    "Autogen UV Strobe",    1],
            [    732,    "hooked wandering bottom",    16],
            [    732,    "UV pulse slow",    2],
            [    748,    "Autogen bassline top",    2],
            [    748,    "rainbow good slow top",    16],
            [    764,    "hooked wandering top",    16],
            [    764,    "Autogen bassline sidechain bottom",    2],
            [    780,    "rainbow good slow top",    16],
            [    780,    "Ghosts riser",    4],
            [    796,    "rainbow good slow top",    16],
            [    796,    "Rainbow bad",    2],
            [    812,    "Autogen bassline top",    2],
            [    812,    "Autogen UV Strobe",    1],
            [    814,    "UV pulse slow",    2],
            [    814,    "Ghosts riser",    4],
            [    818,    "Autogen UV Strobe",    1],
            [    818,    "UV pulse",    1],
            [    819,    "Ghosts riser",    4],
            [    819,    "Ghosts riser",    4],
            [    823,    "Autogen bassline top",    2],
            [    823,    "Rainbow bad",    2],
            [    825,    "Autogen bassline sidechain bottom",    2],
            [    825,    "RBBB 1 bar",    4],
            [    829,    "Autogen bassline bottom",    2],
            [    829,    "Autogen bassline top",    2],
            [    831,    "Autogen Strobe",    1],
            [    831,    "Ghosts riser",    4],
            [    835,    "Autogen bassline bottom",    2],
            [    835,    "UV pulse slow",    2],
            [    837,    "Autogen Strobe",    1],
            [    837,    "Autogen Strobe",    1],
            [    838,    "Autogen UV Strobe",    1],
            [    838,    "Autogen bassline top",    2],
            [    840,    "Ghosts riser",    4],
            [    840,    "Autogen bassline top",    2],
            [    844,    "UV pulse",    1],
            [    844,    "Autogen UV Strobe",    1],
            [    845,    "Rainbow bad",    2],
            [    845,    "Autogen bassline bottom",    2],
            [    847,    "hooked wandering top",    16],
            [    847,    "Autogen bassline bottom",    2],
            [    863,    "rainbow good slow top",    16],
            [    863,    "Autogen UV Strobe",    1],
            [    879,    "Rainbow bad",    2],
            [    879,    "UV pulse slow",    2],
            [    881,    "UV pulse",    1],
            [    881,    "hooked wandering bottom",    16],
            [    897,    "hooked wandering bottom",    16],
            [    897,    "Rainbow bad",    2],
            [    913,    "RBBB 1 bar",    4],
            [    913,    "Autogen UV Strobe",    1],
            [    917,    "Ghosts riser",    4],
            [    917,    "Ghosts riser",    4],
            [    921,    "UV pulse slow",    2],
            [    921,    "Rainbow bad",    2],
            [    923,    "Autogen Strobe",    1],
            [    923,    "Rainbow bad",    2],
            [    925,    "Autogen bassline bottom",    2],
            [    925,    "Autogen bassline top",    2],
            [    927,    "Autogen Strobe",    1],
            [    927,    "hooked wandering top",    16],
            [    943,    "hooked wandering top",    16],
            [    943,    "UV pulse",    1],
            [    959,    "rainbow good slow top",    16],
            [    959,    "hooked wandering top",    16],
            [    975,    "Autogen bassline sidechain bottom",    2],
            [    975,    "Ghosts riser",    4],
            [    979,    "Autogen bassline top",    2],
            [    979,    "Autogen Strobe",    1],
            [    981,    "Autogen bassline top",    2],
            [    981,    "Autogen bassline sidechain bottom",    2],
            [    983,    "hooked wandering bottom",    16],
            [    983,    "hooked wandering bottom",    16],
            [    999,    "Autogen bassline sidechain bottom",    2],
            [    999,    "Autogen bassline bottom",    2],
            [    1001,    "hooked wandering bottom",    16],
            [    1001,    "hooked wandering bottom",    16],
            [    1017,    "RBBB 1 bar",    4],
            [    1017,    "Autogen Strobe",    1],
            [    1021,    "Autogen bassline sidechain bottom",    2],
            [    1021,    "Autogen Strobe",    1],
            [    1023,    "RBBB 1 bar",    4],
            [    1023,    "UV pulse slow",    2],
            [    1027,    "Autogen Strobe",    1],
            [    1027,    "rainbow good slow top",    16],
            [    1043,    "Autogen Strobe",    1],
            [    1043,    "Rainbow bad",    2],
            [    1045,    "hooked wandering bottom",    16],
            [    1045,    "Rainbow bad",    2],
            [    1061,    "Autogen bassline top",    2],
            [    1061,    "Autogen UV Strobe",    1],
            [    1063,    "Autogen bassline sidechain bottom",    2],
            [    1063,    "UV pulse",    1],
            [    1065,    "Ghosts riser",    4],
            [    1065,    "Autogen Strobe",    1],
            [    1069,    "Autogen UV Strobe",    1],
            [    1069,    "Autogen bassline sidechain bottom",    2],
            [    1071,    "hooked wandering bottom",    16],
            [    1071,    "Autogen bassline sidechain bottom",    2],
            [    1087,    "Autogen bassline sidechain bottom",    2],
            [    1087,    "Autogen bassline top",    2],
            [    1089,    "RBBB 1 bar",    4],
            [    1089,    "rainbow good slow top",    16],
            [    1105,    "hooked wandering bottom",    16],
            [    1105,    "Autogen bassline sidechain bottom",    2],
            [    1121,    "hooked wandering bottom",    16],
            [    1121,    "hooked wandering bottom",    16],
            [    1137,    "Autogen Strobe",    1],
            [    1137,    "Rainbow bad",    2],
            [    1139,    "Autogen UV Strobe",    1],
            [    1139,    "Autogen bassline sidechain bottom",    2],
            [    1141,    "Autogen bassline sidechain bottom",    2],
            [    1141,    "Rainbow bad",    2],
            [    1143,    "Autogen bassline bottom",    2],
            [    1143,    "Autogen UV Strobe",    1],
            [    1145,    "RBBB 1 bar",    4],
            [    1145,    "Autogen bassline bottom",    2],
            [    1149,    "Autogen Strobe",    1],
            [    1149,    "Autogen bassline sidechain bottom",    2],
            [    1151,    "UV pulse",    1],
            [    1151,    "Autogen bassline bottom",    2],
            [    1153,    "Autogen bassline sidechain bottom",    2],
            [    1153,    "hooked wandering bottom",    16],
            [    1169,    "RBBB 1 bar",    4],
            [    1169,    "hooked wandering bottom",    16],
            [    1185,    "hooked wandering bottom",    16],
            [    1185,    "UV pulse",    1],
            [    1201,    "Autogen Strobe",    1],
            [    1201,    "hooked wandering bottom",    16],
            [    1217,    "hooked wandering bottom",    16],
            [    1217,    "Autogen bassline bottom",    2],
            [    1233,    "rainbow good slow top",    16],
            [    1233,    "RBBB 1 bar",    4],
            [    1249,    "Autogen bassline bottom",    2],
            [    1249,    "Rainbow bad",    2],
            [    1251,    "Rainbow bad",    2],
            [    1251,    "RBBB 1 bar",    4],
            [    1255,    "Ghosts riser",    4],
            [    1255,    "rainbow good slow top",    16]
        ],
        "bpm": 90,
        "delay_lights": 0.10275000000000001,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/slowed_deadmau.ogg"
    }
}