effects = {
    "g_Superhumanoids - Too Young For Love": {
        "beats": [
            [    1,    "hooked wandering bottom",    16],
            [    1,    "Autogen bassline top",    2],
            [    17,    "Autogen UV Strobe",    1],
            [    17,    "Autogen bassline bottom",    2],
            [    19,    "UV pulse slow",    2],
            [    19,    "Autogen UV Strobe",    1],
            [    21,    "hooked wandering bottom",    16],
            [    21,    "hooked wandering top",    16],
            [    37,    "Autogen bassline bottom",    2],
            [    37,    "Autogen bassline top",    2],
            [    39,    "Autogen Strobe",    1],
            [    39,    "Autogen UV Strobe",    1],
            [    40,    "Autogen Strobe",    1],
            [    40,    "Autogen Strobe",    1],
            [    41,    "Rainbow bad",    2],
            [    41,    "Autogen bassline bottom",    2],
            [    43,    "UV pulse",    1],
            [    43,    "rainbow good slow top",    16],
            [    59,    "hooked wandering top",    16],
            [    59,    "RBBB 1 bar",    4],
            [    75,    "hooked wandering top",    16],
            [    75,    "UV pulse slow",    2],
            [    91,    "Rainbow bad",    2],
            [    91,    "Autogen bassline top",    2],
            [    93,    "Autogen bassline sidechain bottom",    2],
            [    93,    "hooked wandering top",    16],
            [    109,    "Autogen bassline bottom",    2],
            [    109,    "Autogen UV Strobe",    1],
            [    111,    "Autogen bassline sidechain bottom",    2],
            [    111,    "hooked wandering bottom",    16],
            [    127,    "Autogen UV Strobe",    1],
            [    127,    "rainbow good slow top",    16],
            [    143,    "Rainbow bad",    2],
            [    143,    "Autogen bassline sidechain bottom",    2],
            [    145,    "Autogen UV Strobe",    1],
            [    145,    "Autogen bassline bottom",    2],
            [    147,    "Rainbow bad",    2],
            [    147,    "Autogen bassline sidechain bottom",    2],
            [    149,    "hooked wandering top",    16],
            [    149,    "Autogen bassline bottom",    2],
            [    165,    "hooked wandering top",    16],
            [    165,    "RBBB 1 bar",    4],
            [    181,    "Autogen bassline top",    2],
            [    181,    "UV pulse",    1],
            [    183,    "Autogen UV Strobe",    1],
            [    183,    "UV pulse",    1],
            [    184,    "Ghosts riser",    4],
            [    184,    "hooked wandering top",    16],
            [    200,    "Autogen Strobe",    1],
            [    200,    "Autogen bassline top",    2],
            [    202,    "Autogen UV Strobe",    1],
            [    202,    "Autogen bassline top",    2],
            [    204,    "Autogen bassline top",    2],
            [    204,    "Autogen bassline sidechain bottom",    2],
            [    206,    "hooked wandering bottom",    16],
            [    206,    "UV pulse slow",    2],
            [    222,    "hooked wandering bottom",    16],
            [    222,    "Ghosts riser",    4],
            [    238,    "rainbow good slow top",    16],
            [    238,    "hooked wandering bottom",    16],
            [    254,    "Autogen bassline sidechain bottom",    2],
            [    254,    "UV pulse",    1],
            [    256,    "Ghosts riser",    4],
            [    256,    "UV pulse slow",    2],
            [    260,    "UV pulse",    1],
            [    260,    "hooked wandering top",    16],
            [    276,    "Rainbow bad",    2],
            [    276,    "hooked wandering top",    16],
            [    292,    "hooked wandering top",    16],
            [    292,    "hooked wandering top",    16],
            [    308,    "Ghosts riser",    4],
            [    308,    "UV pulse slow",    2],
            [    312,    "Autogen bassline sidechain bottom",    2],
            [    312,    "UV pulse",    1],
            [    314,    "hooked wandering top",    16],
            [    314,    "rainbow good slow top",    16],
            [    330,    "Autogen Strobe",    1],
            [    330,    "rainbow good slow top",    16],
            [    346,    "UV pulse slow",    2],
            [    346,    "UV pulse",    1],
            [    348,    "Autogen UV Strobe",    1],
            [    348,    "hooked wandering top",    16],
            [    364,    "Autogen UV Strobe",    1],
            [    364,    "rainbow good slow top",    16],
            [    380,    "Autogen bassline sidechain bottom",    2],
            [    380,    "Autogen bassline sidechain bottom",    2],
            [    382,    "UV pulse slow",    2],
            [    382,    "Autogen UV Strobe",    1],
            [    384,    "UV pulse",    1],
            [    384,    "Autogen Strobe",    1],
            [    385,    "Autogen Strobe",    1],
            [    385,    "RBBB 1 bar",    4],
            [    389,    "rainbow good slow top",    16],
            [    389,    "hooked wandering top",    16],
            [    405,    "Autogen bassline bottom",    2],
            [    405,    "Rainbow bad",    2],
            [    407,    "Autogen bassline top",    2],
            [    407,    "Autogen bassline sidechain bottom",    2],
            [    409,    "UV pulse slow",    2],
            [    409,    "Autogen bassline top",    2],
            [    411,    "Autogen bassline bottom",    2],
            [    411,    "Autogen UV Strobe",    1],
            [    413,    "Autogen bassline top",    2],
            [    413,    "Autogen bassline bottom",    2],
            [    415,    "Rainbow bad",    2],
            [    415,    "UV pulse",    1],
            [    417,    "Autogen bassline sidechain bottom",    2],
            [    417,    "rainbow good slow top",    16],
            [    433,    "Rainbow bad",    2],
            [    433,    "Ghosts riser",    4],
            [    437,    "Autogen bassline top",    2],
            [    437,    "hooked wandering bottom",    16],
            [    453,    "UV pulse",    1],
            [    453,    "Autogen bassline top",    2],
            [    455,    "Autogen bassline top",    2],
            [    455,    "hooked wandering top",    16],
            [    471,    "rainbow good slow top",    16],
            [    471,    "UV pulse slow",    2],
            [    487,    "UV pulse slow",    2],
            [    487,    "Autogen UV Strobe",    1],
            [    489,    "Rainbow bad",    2],
            [    489,    "RBBB 1 bar",    4],
            [    493,    "UV pulse",    1],
            [    493,    "Autogen Strobe",    1],
            [    494,    "rainbow good slow top",    16],
            [    494,    "Rainbow bad",    2],
            [    510,    "Autogen bassline sidechain bottom",    2],
            [    510,    "hooked wandering bottom",    16],
            [    526,    "hooked wandering bottom",    16],
            [    526,    "Autogen UV Strobe",    1]
        ],
        "bpm": 138,
        "delay_lights": 0.089,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/Superhumanoids - Too Young For Love.ogg"
    }
}