effects = {
    "g_Superhumanoids - Too Young For Love": {
        "beats": [
            [    1,    "RBBB 1 bar",    4],
            [    1,    "Autogen UV Strobe",    1],
            [    5,    "Rainbow bad",    2],
            [    5,    "Autogen Strobe",    1],
            [    7,    "UV pulse slow",    2],
            [    7,    "Ghosts riser",    4],
            [    11,    "Autogen bassline top",    2],
            [    11,    "Autogen UV Strobe",    1],
            [    13,    "UV pulse slow",    2],
            [    13,    "UV pulse slow",    2],
            [    15,    "UV pulse slow",    2],
            [    15,    "Autogen Strobe",    1],
            [    17,    "RBBB 1 bar",    4],
            [    17,    "Autogen bassline bottom",    2],
            [    21,    "hooked wandering bottom",    16],
            [    21,    "hooked wandering bottom",    16],
            [    37,    "Autogen UV Strobe",    1],
            [    37,    "Ghosts riser",    4],
            [    41,    "UV pulse slow",    2],
            [    41,    "hooked wandering top",    16],
            [    57,    "RBBB 1 bar",    4],
            [    57,    "rainbow good slow top",    16],
            [    73,    "Autogen Strobe",    1],
            [    73,    "Rainbow bad",    2],
            [    75,    "hooked wandering top",    16],
            [    75,    "rainbow good slow top",    16],
            [    91,    "UV pulse slow",    2],
            [    91,    "hooked wandering top",    16],
            [    107,    "Autogen UV Strobe",    1],
            [    107,    "hooked wandering top",    16],
            [    123,    "Autogen Strobe",    1],
            [    123,    "rainbow good slow top",    16],
            [    139,    "Rainbow bad",    2],
            [    139,    "Autogen Strobe",    1],
            [    141,    "Autogen UV Strobe",    1],
            [    141,    "Autogen bassline sidechain bottom",    2],
            [    143,    "Autogen UV Strobe",    1],
            [    143,    "Autogen bassline top",    2],
            [    145,    "Ghosts riser",    4],
            [    145,    "hooked wandering bottom",    16],
            [    161,    "UV pulse slow",    2],
            [    161,    "Autogen bassline bottom",    2],
            [    163,    "Autogen bassline top",    2],
            [    163,    "Autogen UV Strobe",    1],
            [    165,    "Autogen Strobe",    1],
            [    165,    "Ghosts riser",    4],
            [    169,    "Autogen UV Strobe",    1],
            [    169,    "Autogen Strobe",    1],
            [    170,    "Ghosts riser",    4],
            [    170,    "hooked wandering top",    16],
            [    186,    "hooked wandering bottom",    16],
            [    186,    "hooked wandering bottom",    16],
            [    202,    "Autogen Strobe",    1],
            [    202,    "RBBB 1 bar",    4],
            [    206,    "hooked wandering bottom",    16],
            [    206,    "hooked wandering bottom",    16],
            [    222,    "Autogen bassline top",    2],
            [    222,    "hooked wandering bottom",    16],
            [    238,    "hooked wandering top",    16],
            [    238,    "UV pulse slow",    2],
            [    254,    "UV pulse",    1],
            [    254,    "hooked wandering bottom",    16],
            [    270,    "UV pulse",    1],
            [    270,    "Autogen bassline top",    2],
            [    272,    "Autogen Strobe",    1],
            [    272,    "Autogen bassline top",    2],
            [    274,    "rainbow good slow top",    16],
            [    274,    "hooked wandering top",    16],
            [    290,    "Autogen bassline top",    2],
            [    290,    "Autogen bassline bottom",    2],
            [    292,    "hooked wandering bottom",    16],
            [    292,    "Ghosts riser",    4],
            [    308,    "hooked wandering top",    16],
            [    308,    "UV pulse",    1],
            [    324,    "UV pulse slow",    2],
            [    324,    "UV pulse slow",    2],
            [    326,    "hooked wandering top",    16],
            [    326,    "Autogen Strobe",    1],
            [    342,    "Rainbow bad",    2],
            [    342,    "Autogen bassline bottom",    2],
            [    344,    "UV pulse",    1],
            [    344,    "Ghosts riser",    4],
            [    348,    "rainbow good slow top",    16],
            [    348,    "Ghosts riser",    4],
            [    364,    "RBBB 1 bar",    4],
            [    364,    "Ghosts riser",    4],
            [    368,    "Ghosts riser",    4],
            [    368,    "UV pulse slow",    2],
            [    372,    "Autogen bassline bottom",    2],
            [    372,    "Ghosts riser",    4],
            [    376,    "Ghosts riser",    4],
            [    376,    "UV pulse",    1],
            [    380,    "hooked wandering top",    16],
            [    380,    "hooked wandering top",    16],
            [    396,    "hooked wandering bottom",    16],
            [    396,    "rainbow good slow top",    16],
            [    412,    "Autogen bassline sidechain bottom",    2],
            [    412,    "UV pulse",    1],
            [    414,    "Autogen bassline top",    2],
            [    414,    "Autogen Strobe",    1],
            [    416,    "hooked wandering top",    16],
            [    416,    "RBBB 1 bar",    4],
            [    432,    "Autogen UV Strobe",    1],
            [    432,    "hooked wandering bottom",    16],
            [    448,    "UV pulse slow",    2],
            [    448,    "Autogen bassline bottom",    2],
            [    450,    "rainbow good slow top",    16],
            [    450,    "Autogen bassline bottom",    2],
            [    466,    "Autogen Strobe",    1],
            [    466,    "UV pulse",    1],
            [    467,    "Rainbow bad",    2],
            [    467,    "rainbow good slow top",    16],
            [    483,    "Autogen bassline top",    2],
            [    483,    "RBBB 1 bar",    4],
            [    487,    "UV pulse",    1],
            [    487,    "rainbow good slow top",    16],
            [    503,    "Autogen bassline top",    2],
            [    503,    "Autogen bassline sidechain bottom",    2],
            [    505,    "rainbow good slow top",    16],
            [    505,    "Autogen Strobe",    1],
            [    521,    "Rainbow bad",    2],
            [    521,    "Autogen Strobe",    1],
            [    523,    "UV pulse",    1],
            [    523,    "Ghosts riser",    4],
            [    527,    "Ghosts riser",    4],
            [    527,    "RBBB 1 bar",    4],
            [    531,    "Autogen bassline sidechain bottom",    2],
            [    531,    "hooked wandering bottom",    16]
        ],
        "bpm": 138,
        "delay_lights": 0.089,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/Superhumanoids - Too Young For Love.ogg"
    }
}