effects = {
    "g_Telepathic Love": {
        "beats": [
            [    1,    "Autogen UV Strobe",    1],
            [    1,    "rainbow good slow top",    16],
            [    17,    "hooked wandering top",    16],
            [    17,    "hooked wandering top",    16],
            [    33,    "Autogen UV Strobe",    1],
            [    33,    "Rainbow bad",    2],
            [    35,    "Rainbow bad",    2],
            [    35,    "Rainbow bad",    2],
            [    37,    "Autogen Strobe",    1],
            [    37,    "Autogen bassline sidechain bottom",    2],
            [    39,    "rainbow good slow top",    16],
            [    39,    "Autogen bassline bottom",    2],
            [    55,    "rainbow good slow top",    16],
            [    55,    "Autogen UV Strobe",    1],
            [    71,    "Autogen bassline bottom",    2],
            [    71,    "Autogen bassline sidechain bottom",    2],
            [    73,    "Autogen bassline bottom",    2],
            [    73,    "UV pulse slow",    2],
            [    75,    "RBBB 1 bar",    4],
            [    75,    "Autogen UV Strobe",    1],
            [    79,    "hooked wandering bottom",    16],
            [    79,    "hooked wandering bottom",    16],
            [    95,    "Ghosts riser",    4],
            [    95,    "rainbow good slow top",    16],
            [    111,    "Autogen Strobe",    1],
            [    111,    "Autogen bassline sidechain bottom",    2],
            [    113,    "UV pulse slow",    2],
            [    113,    "hooked wandering bottom",    16],
            [    129,    "Autogen bassline bottom",    2],
            [    129,    "Ghosts riser",    4],
            [    133,    "hooked wandering bottom",    16],
            [    133,    "RBBB 1 bar",    4],
            [    149,    "RBBB 1 bar",    4],
            [    149,    "hooked wandering top",    16],
            [    165,    "hooked wandering bottom",    16],
            [    165,    "Autogen bassline bottom",    2],
            [    181,    "Autogen Strobe",    1],
            [    181,    "hooked wandering top",    16],
            [    197,    "UV pulse slow",    2],
            [    197,    "Autogen bassline bottom",    2],
            [    199,    "Autogen UV Strobe",    1],
            [    199,    "rainbow good slow top",    16],
            [    215,    "rainbow good slow top",    16],
            [    215,    "Autogen bassline sidechain bottom",    2],
            [    231,    "Ghosts riser",    4],
            [    231,    "UV pulse slow",    2],
            [    235,    "hooked wandering top",    16],
            [    235,    "UV pulse",    1],
            [    251,    "Autogen bassline sidechain bottom",    2],
            [    251,    "hooked wandering top",    16],
            [    267,    "RBBB 1 bar",    4],
            [    267,    "hooked wandering top",    16],
            [    283,    "Autogen bassline top",    2],
            [    283,    "rainbow good slow top",    16],
            [    299,    "Autogen UV Strobe",    1],
            [    299,    "hooked wandering top",    16],
            [    315,    "hooked wandering bottom",    16],
            [    315,    "RBBB 1 bar",    4],
            [    331,    "hooked wandering bottom",    16],
            [    331,    "rainbow good slow top",    16],
            [    347,    "Autogen bassline bottom",    2],
            [    347,    "hooked wandering top",    16],
            [    363,    "Autogen bassline top",    2],
            [    363,    "hooked wandering top",    16],
            [    379,    "hooked wandering top",    16],
            [    379,    "hooked wandering bottom",    16],
            [    395,    "Autogen UV Strobe",    1],
            [    395,    "Autogen bassline sidechain bottom",    2],
            [    397,    "Autogen bassline sidechain bottom",    2],
            [    397,    "Autogen bassline sidechain bottom",    2],
            [    399,    "hooked wandering top",    16],
            [    399,    "hooked wandering top",    16],
            [    415,    "Autogen bassline top",    2],
            [    415,    "UV pulse slow",    2],
            [    417,    "UV pulse",    1],
            [    417,    "Autogen bassline bottom",    2],
            [    419,    "Autogen bassline top",    2],
            [    419,    "Autogen bassline bottom",    2],
            [    421,    "hooked wandering top",    16],
            [    421,    "RBBB 1 bar",    4],
            [    437,    "hooked wandering bottom",    16],
            [    437,    "Ghosts riser",    4],
            [    453,    "rainbow good slow top",    16],
            [    453,    "Ghosts riser",    4],
            [    469,    "Autogen bassline bottom",    2],
            [    469,    "Ghosts riser",    4],
            [    473,    "hooked wandering bottom",    16],
            [    473,    "UV pulse",    1],
            [    489,    "Autogen bassline sidechain bottom",    2],
            [    489,    "Autogen bassline sidechain bottom",    2],
            [    491,    "Autogen Strobe",    1],
            [    491,    "rainbow good slow top",    16]
        ],
        "bpm": 128,
        "delay_lights": 0.4447,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/Telepathic Love.ogg"
    }
}