effects = {
    "g_Telepathic Love": {
        "beats": [
            [    1,    "hooked wandering bottom",    16],
            [    1,    "Autogen bassline top",    2],
            [    17,    "UV pulse slow",    2],
            [    17,    "Autogen bassline sidechain bottom",    2],
            [    19,    "UV pulse",    1],
            [    19,    "Ghosts riser",    4],
            [    23,    "hooked wandering top",    16],
            [    23,    "Autogen bassline top",    2],
            [    39,    "UV pulse slow",    2],
            [    39,    "Rainbow bad",    2],
            [    41,    "RBBB 1 bar",    4],
            [    41,    "Autogen bassline bottom",    2],
            [    45,    "rainbow good slow top",    16],
            [    45,    "Rainbow bad",    2],
            [    61,    "hooked wandering bottom",    16],
            [    61,    "Autogen UV Strobe",    1],
            [    77,    "Ghosts riser",    4],
            [    77,    "Autogen bassline sidechain bottom",    2],
            [    81,    "Ghosts riser",    4],
            [    81,    "hooked wandering bottom",    16],
            [    97,    "UV pulse slow",    2],
            [    97,    "Autogen bassline bottom",    2],
            [    99,    "UV pulse slow",    2],
            [    99,    "UV pulse slow",    2],
            [    101,    "Autogen bassline sidechain bottom",    2],
            [    101,    "UV pulse slow",    2],
            [    103,    "Autogen bassline sidechain bottom",    2],
            [    103,    "Autogen UV Strobe",    1],
            [    105,    "Rainbow bad",    2],
            [    105,    "rainbow good slow top",    16],
            [    121,    "Ghosts riser",    4],
            [    121,    "UV pulse",    1],
            [    125,    "Autogen Strobe",    1],
            [    125,    "hooked wandering top",    16],
            [    141,    "Autogen bassline bottom",    2],
            [    141,    "hooked wandering bottom",    16],
            [    157,    "Autogen bassline top",    2],
            [    157,    "Rainbow bad",    2],
            [    159,    "Autogen bassline bottom",    2],
            [    159,    "Autogen UV Strobe",    1],
            [    161,    "Autogen bassline top",    2],
            [    161,    "Autogen bassline top",    2],
            [    163,    "Autogen bassline sidechain bottom",    2],
            [    163,    "Autogen Strobe",    1],
            [    165,    "UV pulse",    1],
            [    165,    "Ghosts riser",    4],
            [    169,    "Autogen Strobe",    1],
            [    169,    "Rainbow bad",    2],
            [    171,    "Autogen bassline top",    2],
            [    171,    "Ghosts riser",    4],
            [    175,    "RBBB 1 bar",    4],
            [    175,    "Autogen bassline top",    2],
            [    179,    "Ghosts riser",    4],
            [    179,    "hooked wandering top",    16],
            [    195,    "Autogen bassline top",    2],
            [    195,    "RBBB 1 bar",    4],
            [    199,    "Autogen Strobe",    1],
            [    199,    "Autogen bassline top",    2],
            [    201,    "Rainbow bad",    2],
            [    201,    "rainbow good slow top",    16],
            [    217,    "RBBB 1 bar",    4],
            [    217,    "Autogen UV Strobe",    1],
            [    221,    "Autogen bassline sidechain bottom",    2],
            [    221,    "UV pulse",    1],
            [    223,    "RBBB 1 bar",    4],
            [    223,    "UV pulse",    1],
            [    227,    "Autogen Strobe",    1],
            [    227,    "Ghosts riser",    4],
            [    231,    "UV pulse slow",    2],
            [    231,    "RBBB 1 bar",    4],
            [    235,    "Autogen bassline top",    2],
            [    235,    "hooked wandering bottom",    16],
            [    251,    "UV pulse",    1],
            [    251,    "Autogen Strobe",    1],
            [    252,    "Ghosts riser",    4],
            [    252,    "Autogen Strobe",    1],
            [    256,    "UV pulse slow",    2],
            [    256,    "Ghosts riser",    4],
            [    260,    "Autogen bassline sidechain bottom",    2],
            [    260,    "Autogen bassline bottom",    2],
            [    262,    "Autogen bassline bottom",    2],
            [    262,    "rainbow good slow top",    16],
            [    278,    "Autogen bassline bottom",    2],
            [    278,    "Autogen Strobe",    1],
            [    280,    "Autogen bassline bottom",    2],
            [    280,    "RBBB 1 bar",    4],
            [    284,    "Autogen bassline top",    2],
            [    284,    "hooked wandering bottom",    16],
            [    300,    "rainbow good slow top",    16],
            [    300,    "Autogen bassline top",    2],
            [    316,    "Autogen bassline bottom",    2],
            [    316,    "UV pulse",    1],
            [    318,    "hooked wandering bottom",    16],
            [    318,    "UV pulse",    1],
            [    334,    "Ghosts riser",    4],
            [    334,    "UV pulse slow",    2],
            [    338,    "hooked wandering bottom",    16],
            [    338,    "hooked wandering top",    16],
            [    354,    "Autogen bassline sidechain bottom",    2],
            [    354,    "Ghosts riser",    4],
            [    358,    "hooked wandering top",    16],
            [    358,    "Autogen bassline sidechain bottom",    2],
            [    374,    "Autogen bassline top",    2],
            [    374,    "RBBB 1 bar",    4],
            [    378,    "hooked wandering top",    16],
            [    378,    "UV pulse",    1],
            [    394,    "Autogen UV Strobe",    1],
            [    394,    "hooked wandering bottom",    16],
            [    410,    "UV pulse",    1],
            [    410,    "Autogen UV Strobe",    1],
            [    411,    "Autogen bassline bottom",    2],
            [    411,    "hooked wandering bottom",    16],
            [    427,    "hooked wandering top",    16],
            [    427,    "hooked wandering top",    16],
            [    443,    "RBBB 1 bar",    4],
            [    443,    "RBBB 1 bar",    4],
            [    447,    "UV pulse",    1],
            [    447,    "UV pulse slow",    2],
            [    449,    "Autogen bassline bottom",    2],
            [    449,    "RBBB 1 bar",    4],
            [    453,    "Autogen bassline top",    2],
            [    453,    "hooked wandering top",    16],
            [    469,    "Ghosts riser",    4],
            [    469,    "Autogen bassline sidechain bottom",    2],
            [    473,    "Autogen bassline top",    2],
            [    473,    "Autogen bassline bottom",    2],
            [    475,    "Autogen Strobe",    1],
            [    475,    "RBBB 1 bar",    4],
            [    479,    "hooked wandering bottom",    16],
            [    479,    "Autogen bassline bottom",    2]
        ],
        "bpm": 128,
        "delay_lights": 0.4447,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/Telepathic Love.ogg"
    }
}