effects = {
    "g_\u30d6\u30ec\u30fc\u30e1\u30f3": {
        "beats": [
            [    1,    "Autogen bassline sidechain bottom",    2],
            [    1,    "RBBB 1 bar",    4],
            [    5,    "Ghosts riser",    4],
            [    5,    "Autogen bassline bottom",    2],
            [    9,    "Autogen UV Strobe",    1],
            [    9,    "Autogen Strobe",    1],
            [    10,    "Ghosts riser",    4],
            [    10,    "Autogen bassline bottom",    2],
            [    14,    "hooked wandering bottom",    16],
            [    14,    "hooked wandering top",    16],
            [    30,    "Rainbow bad",    2],
            [    30,    "UV pulse",    1],
            [    32,    "Ghosts riser",    4],
            [    32,    "Autogen bassline bottom",    2],
            [    36,    "RBBB 1 bar",    4],
            [    36,    "Ghosts riser",    4],
            [    40,    "UV pulse slow",    2],
            [    40,    "hooked wandering bottom",    16],
            [    56,    "hooked wandering top",    16],
            [    56,    "Autogen bassline bottom",    2],
            [    72,    "UV pulse",    1],
            [    72,    "Autogen Strobe",    1],
            [    73,    "Autogen Strobe",    1],
            [    73,    "Autogen Strobe",    1],
            [    74,    "hooked wandering bottom",    16],
            [    74,    "Autogen bassline sidechain bottom",    2],
            [    90,    "Autogen bassline bottom",    2],
            [    90,    "RBBB 1 bar",    4],
            [    94,    "RBBB 1 bar",    4],
            [    94,    "UV pulse slow",    2],
            [    98,    "Autogen bassline top",    2],
            [    98,    "Rainbow bad",    2],
            [    100,    "UV pulse",    1],
            [    100,    "Autogen bassline top",    2],
            [    102,    "rainbow good slow top",    16],
            [    102,    "UV pulse",    1],
            [    118,    "Autogen bassline top",    2],
            [    118,    "Rainbow bad",    2],
            [    120,    "Ghosts riser",    4],
            [    120,    "UV pulse",    1],
            [    124,    "UV pulse slow",    2],
            [    124,    "rainbow good slow top",    16],
            [    140,    "Autogen bassline sidechain bottom",    2],
            [    140,    "Ghosts riser",    4],
            [    144,    "Autogen Strobe",    1],
            [    144,    "rainbow good slow top",    16],
            [    160,    "RBBB 1 bar",    4],
            [    160,    "Autogen Strobe",    1],
            [    164,    "Ghosts riser",    4],
            [    164,    "UV pulse slow",    2],
            [    168,    "Rainbow bad",    2],
            [    168,    "rainbow good slow top",    16],
            [    184,    "hooked wandering bottom",    16],
            [    184,    "Ghosts riser",    4],
            [    200,    "UV pulse",    1],
            [    200,    "Autogen bassline bottom",    2],
            [    202,    "hooked wandering bottom",    16],
            [    202,    "hooked wandering top",    16],
            [    218,    "Rainbow bad",    2],
            [    218,    "UV pulse",    1],
            [    220,    "UV pulse",    1],
            [    220,    "hooked wandering bottom",    16],
            [    236,    "Autogen UV Strobe",    1],
            [    236,    "Rainbow bad",    2],
            [    238,    "Autogen bassline bottom",    2],
            [    238,    "Ghosts riser",    4],
            [    242,    "UV pulse slow",    2],
            [    242,    "Autogen UV Strobe",    1],
            [    244,    "Autogen UV Strobe",    1],
            [    244,    "Rainbow bad",    2],
            [    246,    "Autogen bassline top",    2],
            [    246,    "Autogen bassline bottom",    2],
            [    248,    "Rainbow bad",    2],
            [    248,    "Autogen Strobe",    1],
            [    250,    "hooked wandering bottom",    16],
            [    250,    "Autogen UV Strobe",    1],
            [    266,    "UV pulse slow",    2],
            [    266,    "hooked wandering bottom",    16],
            [    282,    "rainbow good slow top",    16],
            [    282,    "Rainbow bad",    2],
            [    298,    "Autogen bassline top",    2],
            [    298,    "hooked wandering bottom",    16],
            [    314,    "UV pulse slow",    2],
            [    314,    "Autogen bassline sidechain bottom",    2],
            [    316,    "hooked wandering bottom",    16],
            [    316,    "Autogen UV Strobe",    1],
            [    332,    "Rainbow bad",    2],
            [    332,    "RBBB 1 bar",    4],
            [    336,    "Rainbow bad",    2],
            [    336,    "Autogen UV Strobe",    1],
            [    338,    "Autogen bassline bottom",    2],
            [    338,    "rainbow good slow top",    16],
            [    354,    "Autogen bassline bottom",    2],
            [    354,    "UV pulse",    1],
            [    356,    "Autogen bassline bottom",    2],
            [    356,    "Autogen bassline bottom",    2],
            [    358,    "Autogen bassline top",    2],
            [    358,    "Autogen bassline sidechain bottom",    2],
            [    360,    "rainbow good slow top",    16],
            [    360,    "RBBB 1 bar",    4],
            [    376,    "rainbow good slow top",    16],
            [    376,    "Ghosts riser",    4],
            [    392,    "Autogen UV Strobe",    1],
            [    392,    "Autogen Strobe",    1],
            [    393,    "rainbow good slow top",    16],
            [    393,    "hooked wandering top",    16],
            [    409,    "Rainbow bad",    2],
            [    409,    "hooked wandering bottom",    16],
            [    425,    "Autogen bassline top",    2],
            [    425,    "Autogen UV Strobe",    1],
            [    427,    "Autogen UV Strobe",    1],
            [    427,    "UV pulse",    1],
            [    428,    "hooked wandering top",    16],
            [    428,    "Autogen UV Strobe",    1]
        ],
        "bpm": 95,
        "delay_lights": 0.46957894736842104,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/\u30d6\u30ec\u30fc\u30e1\u30f3.ogg"
    }
}