effects = {
    "g_\u30d6\u30ec\u30fc\u30e1\u30f3": {
        "beats": [
            [    1,    "Ghosts riser",    4],
            [    1,    "Rainbow bad",    2],
            [    5,    "Autogen Strobe",    1],
            [    5,    "Ghosts riser",    4],
            [    9,    "RBBB 1 bar",    4],
            [    9,    "UV pulse",    1],
            [    13,    "UV pulse slow",    2],
            [    13,    "Autogen Strobe",    1],
            [    15,    "Autogen Strobe",    1],
            [    15,    "UV pulse slow",    2],
            [    17,    "Autogen UV Strobe",    1],
            [    17,    "Autogen Strobe",    1],
            [    18,    "hooked wandering bottom",    16],
            [    18,    "hooked wandering top",    16],
            [    34,    "RBBB 1 bar",    4],
            [    34,    "Autogen bassline sidechain bottom",    2],
            [    38,    "rainbow good slow top",    16],
            [    38,    "Rainbow bad",    2],
            [    54,    "hooked wandering top",    16],
            [    54,    "UV pulse",    1],
            [    70,    "Ghosts riser",    4],
            [    70,    "Autogen bassline sidechain bottom",    2],
            [    74,    "Autogen UV Strobe",    1],
            [    74,    "Autogen UV Strobe",    1],
            [    75,    "Ghosts riser",    4],
            [    75,    "hooked wandering top",    16],
            [    91,    "rainbow good slow top",    16],
            [    91,    "UV pulse",    1],
            [    107,    "Ghosts riser",    4],
            [    107,    "Autogen bassline sidechain bottom",    2],
            [    111,    "Autogen bassline sidechain bottom",    2],
            [    111,    "Autogen bassline sidechain bottom",    2],
            [    113,    "Autogen UV Strobe",    1],
            [    113,    "UV pulse",    1],
            [    114,    "hooked wandering top",    16],
            [    114,    "Autogen bassline bottom",    2],
            [    130,    "UV pulse slow",    2],
            [    130,    "hooked wandering top",    16],
            [    146,    "Autogen bassline top",    2],
            [    146,    "Rainbow bad",    2],
            [    148,    "RBBB 1 bar",    4],
            [    148,    "Autogen Strobe",    1],
            [    152,    "Ghosts riser",    4],
            [    152,    "hooked wandering bottom",    16],
            [    168,    "Ghosts riser",    4],
            [    168,    "Rainbow bad",    2],
            [    172,    "Autogen bassline top",    2],
            [    172,    "Autogen bassline bottom",    2],
            [    174,    "rainbow good slow top",    16],
            [    174,    "rainbow good slow top",    16],
            [    190,    "UV pulse slow",    2],
            [    190,    "RBBB 1 bar",    4],
            [    194,    "rainbow good slow top",    16],
            [    194,    "Autogen Strobe",    1],
            [    210,    "Autogen bassline sidechain bottom",    2],
            [    210,    "UV pulse",    1],
            [    212,    "Autogen bassline bottom",    2],
            [    212,    "Rainbow bad",    2],
            [    214,    "UV pulse slow",    2],
            [    214,    "RBBB 1 bar",    4],
            [    218,    "Autogen bassline top",    2],
            [    218,    "hooked wandering top",    16],
            [    234,    "hooked wandering bottom",    16],
            [    234,    "Ghosts riser",    4],
            [    250,    "Autogen bassline bottom",    2],
            [    250,    "Autogen bassline sidechain bottom",    2],
            [    252,    "Rainbow bad",    2],
            [    252,    "UV pulse slow",    2],
            [    254,    "Autogen UV Strobe",    1],
            [    254,    "RBBB 1 bar",    4],
            [    258,    "Autogen UV Strobe",    1],
            [    258,    "UV pulse slow",    2],
            [    260,    "Autogen bassline bottom",    2],
            [    260,    "Rainbow bad",    2],
            [    262,    "Autogen bassline bottom",    2],
            [    262,    "Autogen bassline sidechain bottom",    2],
            [    264,    "RBBB 1 bar",    4],
            [    264,    "Autogen bassline sidechain bottom",    2],
            [    268,    "RBBB 1 bar",    4],
            [    268,    "Rainbow bad",    2],
            [    272,    "Ghosts riser",    4],
            [    272,    "Autogen UV Strobe",    1],
            [    276,    "Autogen Strobe",    1],
            [    276,    "rainbow good slow top",    16],
            [    292,    "Autogen UV Strobe",    1],
            [    292,    "hooked wandering bottom",    16],
            [    308,    "Autogen Strobe",    1],
            [    308,    "RBBB 1 bar",    4],
            [    312,    "Autogen Strobe",    1],
            [    312,    "Autogen bassline sidechain bottom",    2],
            [    314,    "hooked wandering bottom",    16],
            [    314,    "Autogen bassline sidechain bottom",    2],
            [    330,    "Autogen bassline bottom",    2],
            [    330,    "UV pulse",    1],
            [    332,    "UV pulse slow",    2],
            [    332,    "UV pulse",    1],
            [    334,    "hooked wandering bottom",    16],
            [    334,    "UV pulse slow",    2],
            [    350,    "Autogen UV Strobe",    1],
            [    350,    "Autogen UV Strobe",    1],
            [    351,    "Autogen bassline bottom",    2],
            [    351,    "Autogen bassline top",    2],
            [    353,    "Autogen bassline bottom",    2],
            [    353,    "RBBB 1 bar",    4],
            [    357,    "RBBB 1 bar",    4],
            [    357,    "UV pulse slow",    2],
            [    361,    "rainbow good slow top",    16],
            [    361,    "Rainbow bad",    2],
            [    377,    "Autogen UV Strobe",    1],
            [    377,    "Autogen Strobe",    1],
            [    378,    "Autogen bassline top",    2],
            [    378,    "Autogen Strobe",    1],
            [    380,    "Rainbow bad",    2],
            [    380,    "RBBB 1 bar",    4],
            [    384,    "hooked wandering top",    16],
            [    384,    "rainbow good slow top",    16],
            [    400,    "Autogen bassline sidechain bottom",    2],
            [    400,    "Autogen bassline top",    2],
            [    402,    "Autogen bassline sidechain bottom",    2],
            [    402,    "Autogen bassline top",    2],
            [    404,    "Ghosts riser",    4],
            [    404,    "Autogen UV Strobe",    1],
            [    408,    "UV pulse",    1],
            [    408,    "Rainbow bad",    2],
            [    410,    "hooked wandering top",    16],
            [    410,    "UV pulse",    1],
            [    426,    "Autogen Strobe",    1],
            [    426,    "Autogen bassline bottom",    2],
            [    428,    "RBBB 1 bar",    4],
            [    428,    "Autogen bassline top",    2],
            [    432,    "Ghosts riser",    4],
            [    432,    "Autogen bassline top",    2]
        ],
        "bpm": 95,
        "delay_lights": 0.46957894736842104,
        "profiles": ["Generated Shows"
        ],
        "skip_song": 0.0,
        "song_path": "songs/\u30d6\u30ec\u30fc\u30e1\u30f3.ogg"
    }
}